### PR TITLE
feat: Differentiate features available only for moderators

### LINKED ISSUE #6758: UI: identify features that are only available for moderators
### What
- Sometimes we, as moderators, think a feature is available to everybody while it is not. That can create confusion when talking with other users.

### Proposed solution

- We should visually identify features that are only available for moderators.

### Part of
- #9308

### PR DESCRIPTION
**Pull request by deveshidwivedi**
### What
Added visual signals to distinguish features exclusive to moderators. This helps prevent confusion and also makes it easier to spot specific functionalities.

### Related issue(s) and discussion

- Fixes #6758

### CODE REVIEW

**Comment by stephanegigandet** [comment]
Thanks for the PR @deveshidwivedi ! For PRs that change the website, it's a good idea to add a screenshot that show the results of the changes, so that people can see them without having to test your code locally.

image

In the issue @CharlesNepote said "We should visually identify features that are only available for moderators.", but there wasn't any details on how to do this visual differenciation.

With your PR there is a differenciation, but there is no way for users to understand what this visual differenciation is about. I think we should make it more clear, with some text "Moderator feature" maybe.

**Comment by teolemon** [comment]
@stephanegigandet We could also have a distinctive color, like "traffic light orange" or "construction yellow"

**Comment by deveshidwivedi** [comment]
@stephanegigandet I have tried to incorporate the above suggestions but am unable to view the edit page as an admin. I have implemented the css on another element to check if it works before committing. Could you please help me resolve this issue so that I could add the screenshot for everyone to view?

**Comment by hangy** [comment]
> @stephanegigandet I have tried to incorporate the above suggestions but am unable to view the edit page as an admin. I have implemented the css on another element to check if it works before committing. Could you please help me resolve this issue so that I could add the screenshot for everyone to view?

Make yourself a moderator, see https://github.com/openfoodfacts/openfoodfacts-server/issues/9684#issuecomment-2026130351

**Comment by deveshidwivedi** [comment]
Thank you! @hangy

**Comment by deveshidwivedi** [comment]
Hello everyone! Could you please give feedback on the recent updates based on the suggestions:

Screenshot 2024-03-29 131235
 
On hovering(specific element):
image

@stephanegigandet @alexfauquette @teolemon @hangy @alexgarel 
Thanks!

**Comment by stephanegigandet** [comment]
> . I have implemented the css on another element to check if it works before committing.

Hi @deveshidwivedi , thanks for adding the shield. It looks a bit weird on some of the elements:

image

The first one looks good I think, but on the checkbox and on the "manage images" dropdown, we don't have the yellow color and the shield position could be improved I think.

Have you been able to make yourself an admin and moderator?

**Comment by deveshidwivedi** [comment]
@stephanegigandet I was able to make myself the moderator and hence tested and updated the styling. Could you please take a look at the recent changes?

**Review by stephanegigandet — APPROVED** [review]
It looks good to me, thank you!

**Pull request merged**
