### PR TITLE
Process de:konzentriert

### PR DESCRIPTION
**Pull request by aleene**
**Description:**
Process de:konzentriert with all the details

### CODE REVIEW

**Comment by aleene** [comment]
Yay, all checks passed

**Comment by stephanegigandet** [comment]
Going to merge master and try to resolve conflicts.

**Comment by aleene** [comment]
Rather not. I'll do it, I am working on it.

**Comment by aleene** [comment]
OK, great. But now we have two conflicting commits (with passiert).

**Pull request merged**
