### PR TITLE
Display Robotoff on product pages

### LINKED ISSUE #1701: Display Robotoff questions on product pages
For each product, we now compute YES/NO questions.

https://robotoff.openfoodfacts.org/api/v1/questions/3456300009798?lang=fr
https://robotoff.openfoodfacts.org/api/v1/questions/3456300009798?lang=en
…

Display them on product pages for logged in users, along with buttons to answer them, so as to simplify contribution

### PR DESCRIPTION
**Pull request by hangy**
**Description:** Adds Robotoff questions for the displayed product as an alert/overlay.
**Related issues and discussion:** Fixes #1701

### CODE REVIEW

**Comment by hangy** [comment]
- [ ] Fix styling
- [ ] Load CSS/JS from outside the shadow root(?)
- [ ] Pass I18N for button captions/labels from the server

**Comment by teolemon** [comment]
@hangy is there anything still blocking the PR ?

**Comment by hangy** [comment]
> @hangy is there anything still blocking the PR ?

Nope, it's ready to be reviewed (hence it's not a draft any more).

**Comment by stephanegigandet** [comment]
Thank you, I'm going to install it on the dev server.

**Comment by stephanegigandet** [comment]
The code is on https://world.dev.openfoodfacts.org , but I don't see request to robotoff, maybe I didn't configure things properly, I need to take a closer look.

**Comment by teolemon** [comment]
@stephanegigandet you need to set `$robotoff_url = '';`

**Comment by hangy** [comment]
Works for me: 
image

**Comment by stephanegigandet** [comment]
Ok I see it now, maybe I wasn't connected or something, it works. Thank you!

**Comment by teolemon** [comment]
seing it on dev server, but I can't reach the button 
image

**Comment by teolemon** [comment]
exiting full screen mode solves this

**Pull request merged**
