### PR TITLE
Revert "DO NOT MERGE - New Crowdin translations"

### PR DESCRIPTION
**Pull request by teolemon**
Reverts openfoodfacts/openfoodfacts-server#2740

### CODE REVIEW

**Comment by teolemon** [comment]
The PR that was merged was not wrong per-se, but it wasn't squashed.

**Comment by VaiTon** [comment]
> 
> 
> Reverting it now won't help. We can't undo this without rewriting Git history and force-pushing to master.

Quoting

**Comment by teolemon** [comment]
It seems that this causes many issues on a public master with forks. Should I close this PR then ?

**Comment by VaiTon** [comment]
> 
> 
> It seems that this causes many issues on a public master with forks. Should I close this PR then ?

Yup.

**Pull request closed without merging**
