### PR TITLE
feat: allow barcode and edit link in search results

### LINKED ISSUE #5994: On web lists of products, add the product's barcode to its front picture, next to the Nutri-score and Eco-score
### Is your feature request related to a problem? Please describe.

[From @chevalstar report] When viewing web lists of similar products (eg. products with the same name such as "Vache qui rit'), it is not possible to make a difference between all the products shown: they share the same Nutri-Score and Eco-Score, the front picture is nearly the same. You have to open all the products manually to see the difference (barcode) between each product.

### Describe the solution you'd like

Some users would like to have the barcode displayed next to the Nutri-Score and the Eco-Score.

Ideally, the 4 last numbers should be in highlighted (bold or something like that).

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Number of products impacted

_No response_

### Time per product

_No response_

### PR DESCRIPTION
**Pull request by alexgarel**
### Description

Now in search preferences you can ask to have barcode and to have edit link.
It displays them in search results.

### Screenshot
Capture d’écran de 2022-03-14 19-05-36

Then:
Capture d’écran de 2022-03-14 19-08-26

The pen links to edition.

### Related issue(s) and discussion

- fixes #5994

### CODE REVIEW

**Review by teolemon — COMMENTED** [review]
- I would strongly recommend something visually more in line with other icons. The pencil looks like a knife.
  - https://thenounproject.com/search/icons/?iconspage=1&q=barcode
  - https://thenounproject.com/search/icons/?iconspage=1&q=edit
- What about an image of the barcode ?

**Comment by stephanegigandet** [comment]
For the name of the section "Search preferences": I would just rename it to "Preferences", those 2 options affect the behaviour of all lists of product pages, not just search results. And later we could add other preferences.

**Comment by alexgarel** [comment]
> * I would strongly recommend something visually more in line with other icons. The pencil looks like a knife.
>       
>       * https://thenounproject.com/search/icons/?iconspage=1&q=barcode
>       * https://thenounproject.com/search/icons/?iconspage=1&q=edit
> 
>     * What about an image of the barcode ?

The problem of nounproject icons is that they are not CC-0 but CC-by.
Or is there a specific page where to put those credits ?

The two icons, I designed myself :grimacing:

**Comment by stephanegigandet** [comment]
> The two icons, I designed myself grimacing

:)

Using Inkscape? For the icons I create, I try to mimmick the Material design icons, with a 24x24 grid.

**Comment by alexgarel** [comment]
I close this PR, I will do a new one.

**Pull request closed without merging**
