### PR TITLE
feat: Cooking duration taxonomy generation script

### PR DESCRIPTION
**Pull request by teolemon**
### What
- A small script to permit generating a cooking duration taxonomy
### Part of
- #5507

### CODE REVIEW

**Comment by stephanegigandet** [comment]
The script works, but what is the motivation for a cooking duration taxonomy? If we want to record cooking time (or in many cases cooking times as frozen products for instance have different times for microwave, oven etc.), then a numeric field would probably be more adapted.

**Comment by aleene** [comment]
Can this be closed?

**Comment by teolemon** [comment]
The intent was to provide a foundation for Robotoff detections.

**Comment by alexgarel** [comment]
@teolemon I think we should close that PR. 
If robotoff needs to generate this vocabulary, it will do it.

**Pull request closed without merging**
