### PR TITLE
taxonomy: Changes to juices

### PR DESCRIPTION
**Pull request by moon-rabbitOFF**
### Related issue(s) and discussion

- Fixes #[ISSUE NUMBER]

### CODE REVIEW

**Comment by aleene** [comment]
Great. I did not want to this yet.

**Review by stephanegigandet — APPROVED** [review]
Looks good to me

**Comment by stephanegigandet** [comment]
> Great. I did not want to this yet.

@aleene I think there's a word missing or something in your sentence, so I don't understand if the proposed changes are ok with you or not?

**Comment by aleene** [comment]
Ok for me.

**Comment by oyenuga17** [comment]
@moon-rabbitOFF  Hi i'm please i would love to connect with you whether via mail or social media

**Pull request merged**
