### PR TITLE
Remove the /lang directory

### PR DESCRIPTION
**Pull request by teolemon**
### What

- [x] Remove the /lang directory since I added the missing files to the new static repository: https://github.com/openfoodfacts/openfoodfacts-web/commit/5ac85c89160c5974a4ea26f8a8496a9f47a88b9f
- [ ] Move those tests to openfoodfacts-web

```
#   Failed test 'footer_legal_link link - lang: pt - textid: informacao-legal -- file /lang/pt/texts/informacao-legal.html does not exist'
#   at t/lang.t line 52.

#   Failed test 'footer_legal_link link - lang: fr - textid: mentions-legales -- file /lang/fr/texts/mentions-legales.html does not exist'
#   at t/lang.t line 52.

#   Failed test 'footer_terms_link link - lang: fr - textid: conditions-d-utilisation -- file /lang/fr/texts/conditions-d-utilisation.html does not exist'
#   at t/lang.t line 52.

#   Failed test 'footer_terms_link link - lang: pt - textid: termos-de-utilizacao -- file /lang/pt/texts/termos-de-utilizacao.html does not exist'
#   at t/lang.t line 52.
# Looks like you failed 4 tests of 376.
t/lang.t ......................... 
```

### Part of
- Static content

### CODE REVIEW

**Comment by hangy** [comment]
How do you want to integrate this into develpoment environments, ie. Docker? Also, the GitHub workflows will need to be fixed. For example, the PR validation does try to build language (I assume to validate the translations): https://github.com/openfoodfacts/openfoodfacts-server/blob/f33510efbba8ae2ceb357906a54fd47b470c8969/.github/workflows/pull_request.yml#L166

**Comment by stephanegigandet** [comment]
@hangy : if we leave an empty lang directory, then build_lang.pl will work (the /po directory is still there).

**Comment by hangy** [comment]
> @hangy : if we leave an empty lang directory, then build_lang.pl will work (the /po directory is still there).

Good idea, but don't we need some kind of submodule, so that developers can test locally easily?

**Comment by stephanegigandet** [comment]
> Good idea, but don't we need some kind of submodule, so that developers can test locally easily?

Maybe just a script that would do a git clone of openfoodfacts-web and link the /lang directory to the clone? Or maybe you have a better idea on how we could do it?

**Comment by stephanegigandet** [comment]
So we'll need to move those tests to openfoodfacts-web:

#   Failed test 'footer_legal_link link - lang: pt - textid: informacao-legal -- file /lang/pt/texts/informacao-legal.html does not exist'
#   at t/lang.t line 52.

#   Failed test 'footer_legal_link link - lang: fr - textid: mentions-legales -- file /lang/fr/texts/mentions-legales.html does not exist'
#   at t/lang.t line 52.

#   Failed test 'footer_terms_link link - lang: fr - textid: conditions-d-utilisation -- file /lang/fr/texts/conditions-d-utilisation.html does not exist'
#   at t/lang.t line 52.

#   Failed test 'footer_terms_link link - lang: pt - textid: termos-de-utilizacao -- file /lang/pt/texts/termos-de-utilizacao.html does not exist'
#   at t/lang.t line 52.
# Looks like you failed 4 tests of 376.
t/lang.t .........................

**Comment by stephanegigandet** [comment]
Done in PR https://github.com/openfoodfacts/openfoodfacts-server/pull/6113

**Pull request closed without merging**
