### PR TITLE
Reviewed  creams

### PR DESCRIPTION
**Pull request by aleene**
**Description:**
Performed an update of the creams section

### CODE REVIEW

**Comment by moon-rabbitOFF** [comment]
"Crème UHT" and "Crème stérilisée UHT" are the same thing. Ultra-High Temperature processing is particular type of sterilisation.

**Comment by moon-rabbitOFF** [comment]
Pasteurization is not considered as a sterilisation technique. It is carried out under 10°C, it kills bacteria but doesn't detroy bacterial spores (Wikipedien EN). So crème fraîche can be pasteurizated.

**Comment by aleene** [comment]
OK. Note that these are the words used in ingredient lists. So I did not make it up. I understood that there are multiple sterilisation methods, so I did not make UHT and sterilised synonyms.

**Comment by aleene** [comment]
I will removing many translations taken from wiikidata, as they seem to be wrong.

**Pull request merged**
