### PR TITLE
de:passiert

### PR DESCRIPTION
**Pull request by aleene**
**Description:**
de:passiert added

### CODE REVIEW

**Comment by stephanegigandet** [comment]
I tried Google Translation on the few examples of ingredients with "passiert" we have, and I have no idea what it means:

image
image

?

**Comment by aleene** [comment]
Indeed it is also happens. Check this, which hangy sent me: https://www.lebensmittellexikon.de/f0000920.php

You can buy it in France as passata (passierte Tomaten). Which makes me wonder whether de:mark should be under en:filtered.

**Comment by stephanegigandet** [comment]
Isn't it more an ingredient by itself, instead of a processing? If it's mainly tomatoes, then it's easier to just have an entry for it in the taxonomy.

**Comment by aleene** [comment]
Is possible. As it is a synonym of de:mark, I think it better to put into processing, otherwise we are still left with a line in the ingredients taxonomy. The tomato example was just to explain the word passiert (passata).

**Comment by aleene** [comment]
I will move de:passiert to en:sieved, fr:tamisé

**Comment by stephanegigandet** [comment]
> I will move `de:passiert` to `en:sieved`, `fr:tamisé`.

Sounds good.

**Pull request closed without merging**
