### PR TITLE
Added sugared pomegranate nectars

### PR DESCRIPTION
**Pull request by aleene**
**Description:**
Added to solve a missing ecoscore.

I wonder whether nectars with added sugar have been correctly classified.

### CODE REVIEW

**Comment by aleene** [comment]
https://world.openfoodfacts.org/cgi/search.pl?action=process&tagtype_0=categories&tag_contains_0=contains&tag_0=nectars&tagtype_1=ingredients&tag_contains_1=contains&tag_1=sugar&sort_by=unique_scans_n&page_size=20

**Review by stephanegigandet — CHANGES_REQUESTED** [review]
All fruits nectars are by definition fruit juice + sugar + water, that category should not exist, instead products should go into the existing one:

<en:Fruit nectars
en:Pomegranate nectars
de:Granatapfelnektare
es:Néctares de granada
fr:Nectars de grenade
it:Nettari di melograno, nettare di melograno, nettari di melagrana, nettare di melagrana
nl:Granaatappelnectars, Granaatappelnectar
pt:Néctares de romã

**Comment by teolemon** [comment]
@aleene

**Comment by aleene** [comment]
So this was not a relevant change.

**Pull request closed without merging**
