### PR TITLE
fix: update donation banner text

### PR DESCRIPTION
**Pull request by stephanegigandet**
image

### CODE REVIEW

**Review by teolemon — APPROVED** [review]

**Comment by teolemon** [comment]
Can we possibly add bold, and possibly "independant from the food industry" @stephanegigandet

**Comment by stephanegigandet** [comment]
> Can we possibly add bold, and possibly "independant from the food industry" @stephanegigandet

We can anything, please discuss it with Gala who sent me the new text.

**Comment by teolemon** [comment]
@g123k do you think we could have a simple non looping animation for the heart

**Comment by g123k** [comment]
> @g123k do you think we could have a simple non looping animation for the heart

You, it's totally possible with Rive
For the web? For the app?

**Comment by teolemon** [comment]
both would be nice @g123k 
the usecase here would be web, but we could put it in the app

**Pull request merged**
