### PR TITLE
ci: Make dependabot GH project compatible

### PR DESCRIPTION
**Pull request by teolemon**
### What

ci: Make dependabot GH project compatible
Not finished, but someone gave us a solution: https://github.com/actions/add-to-project/issues/93

### CODE REVIEW

**Comment by alexgarel** [comment]
@teolemon is this ready or not ? I don't understand. If it's not, put it as "draft".

**Comment by stephanegigandet** [comment]
Another question is: do we really want to have dependabot PRs in GitHub project?

**Comment by alexgarel** [comment]
> Another question is: do we really want to have dependabot PRs in GitHub project?

Yes I also strongly disagree, it's already so much noise !

**Comment by alexgarel** [comment]
@teolemon can we close ?

**Pull request closed without merging**
