### PR TITLE
Ecoscore details icons

### PR DESCRIPTION
**Pull request by stephanegigandet**
Added some icons for the Eco-score details (2 from the material design icons, 2 I drew in the same style).

Also changed the way we store origins ids + percents in the ecoscore_data structure. cc @aleene 

image

### CODE REVIEW

**Comment by aleene** [comment]
Great. What product comes this example from?

**Comment by stephanegigandet** [comment]
> Great. What product comes this example from?

It's a made-up product on the test platform: https://fr.openfoodfacts.dev/produit/3560070682683/biscuits-chocolat-au-lait-carrefour

**Comment by CharlesNepote** [comment]
Great job!

"What is Agribalyse?" might ask people. Maybe you could add a link to https://fr.wikipedia.org/wiki/Agribalyse or a `<span title="LCA Database from ADEME">Agribalyse</span>`? Or maybe the (i) symbol linking to https://fr.openfoodfacts.dev/eco-score should be repeated inside the box?

**Comment by stephanegigandet** [comment]
> Maybe you could add a link to https://fr.wikipedia.org/wiki/Agribalyse

Good idea, I'll do that.

**Pull request merged**
