### PR TITLE
Display "at a glance" attributes on top of product page based on user preferences

### PR DESCRIPTION
**Pull request by stephanegigandet**
This is a start to personalize (and later redesign) the product page (see #4391 )

What it does is to display some colored boxes on top of the individual product page to show the information that users have selected to be important.

Users can edit their preferences on page, and see the changes right away without reloading the page.

Those are the default preferences:

image

Of course the more preferences are selected, the more crowded it can get at the top:

image

### CODE REVIEW

**Comment by stephanegigandet** [comment]
If you want to try it out, it's currently on the dev server. You need to add &user_preferences=1 to get the new behavior (which we'll probably make the default once everything is perfected).

https://world.openfoodfacts.dev/product/3257980631336/lait-ecreme-cora?user_preferences=1

**Comment by teolemon** [comment]
- [ ] All cards should have the height of the tallest card on the line
image

- [ ] Icons should be on the left of the card (they have predictable dimensions, thus making the layout more predictable and the reading easier)
- [ ] Broken images: Not a fair trade product, Not an organic product (we have square images for them in FR: https://static.openfoodfacts.org/images/lang/fr/labels/bio.96x90.png, https://static.openfoodfacts.org/images/lang/fr/labels/commerce-equitable.96x90.png, and I have an image to symbolize fairtrade we can take inspiration from.)
- [ ] Blue Info links (Nutri-Score, NOVA, Nutrient levels)
- [ ] Details of computations (Nutri-Score, NOVA)
- [ ] Unexplainable vacuum with card on the right
image
- [ ] Food settings icon too small
image
- [ ] Adopting the new rounded style for the alert above, and possibly adding Apple/Google icons/ Edit button
image
- [ ] Mention: "Those preferences are only stored on this browser and are not password protected. Do not share this browser with others if you're inconfortable sharing your preferences or click on the Reset button to delete them. Deleting cookies will mean loosing your preferences."
image

**Comment by stephanegigandet** [comment]
Thanks for all the feedback!

> *  All cards should have the height of the tallest card on the line

Agreed, but not easy to do as the design is responsive and the number of cards on a line varies. One option is to force the same height on all cards, either to a fixed height (and we'll have to deal with content that is too long on some card), or possibly to the tallest card (which might make all of them quite tall and create a very bad experience on mobile where each line has only one card).

> *  Icons should be on the left of the card (they have predictable dimensions, thus making the layout more predictable and the reading easier)

I had tried it but it doesn't work very well, unless the content is very short and always fit on the right of the icon without going below it. It also does not work for icons that do not have the same width (only one right now, but the most important one : Nutri-Score)

> Broken images: Not a fair trade product, Not an organic product (we have square images for them in FR: https://static.openfoodfacts.org/images/lang/fr/labels/bio.96x90.png, https://static.openfoodfacts.org/images/lang/fr/labels/commerce-equitable.96x90.png, and I have an image to symbolize fairtrade we can take inspiration from.)

The French images are shown in French, but I was planning to make more generic logos (without text). Where is your fairtrade image?

> * Blue Info links (Nutri-Score, NOVA, Nutrient levels)
> * Details of computations (Nutri-Score, NOVA)

We will have to experiment with whether we should and how we can surface more information in the cards. I think the best approach is to start small and simple, and not to try to fit everything we have / we could have in the cards right from the start.

One thing to keep in mind is that those top cards are meant to be a "at a glance" summary. At this point at least, they are not supposed to replace the rest of the product page. So we'll need a balance. I was also considering going into the reverse direction: having a way to show only the icons and no text at all.

A separate issue is that any extra detail / content will have to be added to product attributes.

> *  Unexplainable vacuum with card on the right

I saw it but I have not found the fix for that yet. I'll try again.

>  * Food settings icon too small

Agreed but it's a more general issue. All icons are currently too small on the web site. The food icon has the same size as all other icons.

>  * Adopting the new rounded style for the alert above, and possibly adding Apple/Google icons/ Edit button

Rounded-style: we'll have to decide if we keep it for cards or if we apply it to all boxes / panels / warnings.
Icons: good idea. It's separate from the attributes though, that box is the existing box, it wasn't added/changed for the cards.

> *  Mention: "Those preferences are only stored on this browser and are not password protected. Do not share this browser with others if you're inconfortable sharing your preferences or click on the Reset button to delete them. Deleting cookies will mean loosing your preferences."

A fair point, but who shares browsers nowadays? That would be like your browser having a warning shown above the address bar saying "urls you visit are kept in the history of this browser and are not password protected". Maybe we can find a less scary formulation. :)

The preferences are stored in the browser local storage BTW, it's independent from cookies.

**Comment by teolemon** [comment]
- [ ] https://get.foundation/sites/docs/equalizer.html
- [ ] https://static.openfoodfacts.net/files/tests/off-environment/illustrations/tosort/Fair_Labor_Rights_58375.svg

**Comment by stephanegigandet** [comment]
I forgot that Foundation had a different thing for grids that solves the positioning issue. :)

image

**Review by teolemon — APPROVED** [review]

**Comment by teolemon** [comment]
You could use blockgrid within the cells to ensure valign of the text ?

**Pull request merged**
