### PR TITLE
ops: new check_perl and build_taxonomies targets

### LINKED ISSUE #6148: `make tests` is failing
### Describe the bug

`make tests` is failing both on local and on CI.

### To Reproduce

Clone the repo.
Run `make tests`

### Expected behavior

Tests should pass

### Screenshots

_No response_

### Additional context

_No response_

### Type of device

REST-API

### Browser version

_No response_

### Number of products impacted

_No response_

### Time per product

_No response_

### PR DESCRIPTION
**Pull request by alexgarel**
if sucessful, this will replace scripts/check_perl.js and scripts/refresh_taxonomies.js

@ocervell this will enable running make test, and all the workflow in docker.
I didn't change the pull_request.yml yet.

should help fix #6148

### CODE REVIEW

**Comment by alexgarel** [comment]
@ocervell if it is ok for you fill free to append the commits to #6147

**Comment by ocervell** [comment]
Hey @alexgarel, looks good to me but with the two unix shell-based commands in the Makefile, it means we drop the Windows support (make will fail with those in). Do we have a plan for Windows compatibility ?

**Comment by alexgarel** [comment]
@ocervell the two shell based commands are run inside the container (we run make inside backend container) where we know we have a shell, even on windows.

**Review by ocervell — APPROVED** [review]

**Comment by ocervell** [comment]
Please sync the `pull_request.yml` from the `main` branch before merging, to see if the developer workflow passes.

**Pull request merged**
