### PR TITLE
Added the Swedish word for "cheese" to allergens.

### PR DESCRIPTION
**Pull request by Kezxo**
Not sure how it was missing for so long.
https://world.openfoodfacts.org/allergen/sv:ost

I hope I'm doing this correctly.

### CODE REVIEW

**Review by Ban3 — APPROVED** [review]
> I hope I'm doing this correctly.

You are :slightly_smiling_face:

**Comment by aleene** [comment]
Allergens detection is a bit different at the moment. It is now hidden in ingredients.pm (?), and will be moved into the ingredients taxonomy in order to cover all synonyms. Allergens.txt is now only used to provide translations for the allergen categories.

**Comment by Ban3** [comment]
> Allergens detection is a bit different at the moment. It is now hidden in ingredients.pm (?), and will be moved into the ingredients taxonomy in order to cover all synonyms. Allergens.txt is now only used to provide translations for the allergen categories

AFAIK the allergens taxonomy is still used even if there's work to switch to ingredients taxonomy.

**Comment by stephanegigandet** [comment]
Right now, we still use the allergens taxonomy for detection of allergens in the ingredients list. At some point we will probably switch to the new properties of the ingredients taxonomy to do it instead, but it has not been coded yet.

**Comment by Ban3** [comment]
> At some point we will probably switch to the new properties of the ingredients taxonomy to do it instead, but it has not been coded yet.

We also need to remember to move synonyms from allergens taxonomy that are not yet in ingredients.

**Pull request merged**
