### PR TITLE
delete old version of Docker (aio)

### PR DESCRIPTION
**Pull request by NerOcrO**
Are you ok with that?

### CODE REVIEW

**Comment by hangy** [comment]
cc @nicolasleger

**Comment by nicolasleger** [comment]
There is not only Docker related changes why?

**Comment by NerOcrO** [comment]
It's my merge.
Just look f09a25e and f2c56e5.

**Comment by nicolasleger** [comment]
Can you rebase the branch ? would be clearer I think.

**Comment by NerOcrO** [comment]
There is no merge like you can see here https://github.com/openfoodfacts/openfoodfacts-server/commits/docker.
Github show you all the commit.
Like I said, just look f09a25e and f2c56e5.

**Comment by nicolasleger** [comment]
OK

**Comment by NerOcrO** [comment]
https://github.com/openfoodfacts/openfoodfacts-server/commit/6f3e58e1db3a1bc92b09d0e605bb02882dd5cba1

**Pull request closed without merging**
