### PR TITLE
fix: add UTZ Certified xx: and fr: translations

### LINKED ISSUE #6746: The UTZ Certified label has no French translation in the labels taxonomy
### What
- The UTZ Certified label appears untaxonomized in Smoothie
- Link for a scannable barcode: barcode-20968663

### Screenshots
image

### Part of
- https://github.com/openfoodfacts/openfoodfacts-server/milestone/37

### PR DESCRIPTION
**Pull request by stephanegigandet**
should fix #6746

### CODE REVIEW

**Review by teolemon — APPROVED** [review]
A small explanation would be awesome in addition to this

**Comment by stephanegigandet** [comment]
> A small explanation would be awesome in addition to this

Sorry I didn't understand, a small explanation where, and of what?

**Comment by teolemon** [comment]
Why UTZ is cool for ecoscore, currently it's a totally empty panel

**Comment by stephanegigandet** [comment]
> Why UTZ is cool for ecoscore, currently it's a totally empty panel

Well it's the case not just UTZ, it's all labels except Organic.

That info can be added in the labels taxonomy with the following syntax:

```
en:Organic, organically grown, organically produced, ingredient produced organically, from organic farming, From Organic
[..]
description:en:Organic food is food produced by methods complying with the standards of organic farming and features practices that cycle resources, promote ecological balance, and conserve biodiversity. 
description:nl:Biologische voeding is voedsel dat wordt geproduceerd met methoden die voldoen aan de normen van de biologische landbouw, welke een ecologisch evenwicht en het behoud van biodiversiteit nastreeft.
description:de:Bio-Lebensmittel müssen aus ökologisch kontrolliertem Anbau stammen, dürfen nicht gentechnisch verändert sein und werden ohne Einsatz von chemisch-synthetischen Pflanzenschutzmitteln, Kunstdünger oder Klärschlamm angebaut.
description:es:Se denomina alimento orgánico, alimento ecológico o alimento biológico al producto agrícola o agroindustrial que se produce bajo un conjunto de procedimientos denominados “ecológicos”: evitan el uso de productos sintéticos, como pesticidas, herbicidas y fertilizantes artificiales.
description:fr:Un aliment biologique est un aliment produit suivant les principes de l'agriculture biologique. L’agriculture biologique est une méthode de production agricole qui exclut le recours à la plupart des produits chimiques de synthèse, les organismes génétiquement modifiés par transgénèse et la conservation des cultures par irradiation.
environmental_benefits:en:Organic agriculture contributes to preserve biodiversity, climate, water quality and soil fertility.
environmental_benefits:fr:L'agriculture biologique contribue à préserver la biodiversité, le climat, la qualité de l'eau et la fertilité des sols.
```

It would be worthy of its own issue though, crafting the small explanation is not quick and easy.

**Pull request merged**
