### PR TITLE
refactor: enable perl signature `Data.pm`

### PR DESCRIPTION
**Pull request by dipietroR**
Replacing "shift" prototypes with perl signatures

### CODE REVIEW

**Comment by stephanegigandet** [comment]
Failing test:

Too few arguments for subroutine 'ProductOpener::Data::get_products_collection' at /opt/product-opener/lib/ProductOpener/Test.pm line 81.
tests/unit/import_convert_carrefour_france.t .. 
Dubious, test returned 255 (wstat 65280, 0xff00)

**Review by alexgarel — DISMISSED** [review]
Cool :-)

**Review by alexgarel — CHANGES_REQUESTED** [review]
Sorry I spotted a problem:
The problem you had [here](https://github.com/openfoodfacts/openfoodfacts-server/pull/7188#issuecomment-1218131799) about too few arguments, will happen for other functions in scripts. This is because many scripts still uses the old standard of verifying the number of arguments.

We can dismiss this problem by using an explicit $timeout=undef on all functions that use $timeout parameter.

**Review by alexgarel — APPROVED** [review]
Good.

**Pull request merged**
