### PR TITLE
Disable maketext for gettext

### PR DESCRIPTION
**Pull request by hangy**
As suggested by @maddingue

### CODE REVIEW

**Comment by teolemon** [comment]
https://metacpan.org/changes/release/SAPER/Locale-Maketext-Lexicon-Getcontext-0.05

Can you comment on what it does ?

**Comment by hangy** [comment]
> https://metacpan.org/changes/release/SAPER/Locale-Maketext-Lexicon-Getcontext-0.05
> 
> Can you comment on what it does ?

Probably best explained by maddingue:

https://github.com/maddingue/Locale-Maketext-Lexicon-Getcontext/issues/3#issuecomment-355433770
https://github.com/openfoodfacts/openfoodfacts-server/issues/771#issuecomment-355434159

**Comment by hangy** [comment]
@stephanegigandet I reverted the workaround and added a unit test to validate this. Looks fine IMHO.

**Comment by stephanegigandet** [comment]
Wonderful, thank you @hangy!

**Pull request merged**
