### PR TITLE
Add Health Star Rating System from Australia

### PR DESCRIPTION
**Pull request by CharlesNepote**
**Description:**

Health Star Rating System claims to be used by more 10,000 products in Australia.
At least we could add these labels.

http://healthstarrating.gov.au/

### CODE REVIEW

**Comment by teolemon** [comment]
It seems that you can have 3,5 @CharlesNepote @stephanegigandet

**Comment by aleene** [comment]
Is there a way we could calculate them?

**Comment by VaiTon** [comment]
Also, why are we adding the general label and then the specific ones? What's the purpose of the general label?

**Comment by teolemon** [comment]
http://www.healthstarrating.gov.au/internet/healthstarrating/publishing.nsf/Content/excel-calculator

**Comment by CharlesNepote** [comment]
> Also, why are we adding the general label and then the specific ones? What's the purpose of the general label?

@VaiTon it's important for some people or projects (e.g. public policies) to know the total number of products that have this label on the front of pack. We do the same thing with Nutri-Score:
* https://world.openfoodfacts.org/label/nutriscore
* https://world.openfoodfacts.org/label/nutriscore-grade-a
* [...]

Maybe we could compute the general label based on the specific ones.

**Pull request merged**
