### PR TITLE
build(deps): bump npm deps

### PR DESCRIPTION
**Pull request by hangy**
Aggregated some dependabot branches, and fixed build issue of the #8882 PR.

### CODE REVIEW

**Comment by stephanegigandet** [comment]
It's not very important, but when testing, I noticed the icon to go back up the page (after scrolling down) is now a slightly rounded square while it was a circle before.

before:
image

after:
image

**Review by stephanegigandet — APPROVED** [review]
Thank you!

**Comment by hangy** [comment]
> It's not very important, but when testing, I noticed the icon to go back up the page (after scrolling down) is now a slightly rounded square while it was a circle before.
> 
> before:
> image
> 
> after:
> image
> 

Interesting detail! Is it part of foundation? I'll try to have a look later today.

**Comment by hangy** [comment]
> > It's not very important, but when testing, I noticed the icon to go back up the page (after scrolling down) is now a slightly rounded square while it was a circle before.
> > before:
> > image
> > after:
> > image
> 
> Interesting detail! Is it part of foundation? I'll try to have a look later today.

Fixed @stephanegigandet. It was caused by the moved `@import` statements because of a new stylelint rule. I disabled the rule for the time being.

**Review by stephanegigandet — APPROVED** [review]
Looks good to me, thank you!

**Pull request merged**
