### PR TITLE
taxonomy: add :de: alias for Creme Fraiche without the accents

### PR DESCRIPTION
**Pull request by Strubbl**
### What

add :de: alias for Creme Fraiche without the accents e.g. as seen in ingredient list of https://de.openfoodfacts.org/produkt/4008366009763/schlemmerfilet-brokkoli-mandel-frosta

### CODE REVIEW

**Comment by benbenben2** [comment]
The ingredient in the product that you linked is "Créme fraîche" (with some accents, and it is also an unknown ingredient). Hence, I would suggest to add also "Créme fraîche" among the synonyms. What do you think?

**Comment by Strubbl** [comment]
The problem of "Créme fraîche" vs. "Creme Fraiche" is that it is hard to type the french version on a German keyboard. So yes, adding a synonym sounds good to me. How can i add it to the synonyms?

**Comment by stephanegigandet** [comment]
"Créme fraîche" (as written on the package) is actually a mispelling (should be "Crème fraîche). It's not a good idea to add mispellings in the taxonomy (even if some of them can be found on products). Instead we can improve the parser to match some mispellings.

For languages like German that use foreign words that are frequently listed / typed without accents, I think it's fine to add the unaccented version as a synonym as done in this PR.

**Comment by Strubbl** [comment]
Thanks for explaining the accent spelling mistake. I just checked the packaging from the same product which i have at home at the moment. It is fixed in the meantime. I need to update the picture soon.

**Review by hangy — APPROVED** [review]

**Review by stephanegigandet — APPROVED** [review]

**Pull request merged**
