### PR TITLE
fix: added sugars for non US countries 

### LINKED ISSUE #7981: "Added sugars" is not suggested in the nutrition table product edit form
Reported by @aleene. On https://us.openfoodfacts.org , we show "Added sugars" below "Sugars" by default, but we don't display it for other countries, and it's not suggested when starting to type "Added sugars" in the other nutriments box.

### PR DESCRIPTION
**Pull request by stephanegigandet**
fixes #7981

### CODE REVIEW

**Review by aleene — CHANGES_REQUESTED** [review]
Can you add "added-salt" as well?

**Comment by stephanegigandet** [comment]
> Can you add "added-salt" as well?

Are there nutrition table on products with "added salt"? I'm guessing that in most products with a significant amount of salt, almost of it could be considered "added".

**Comment by stephanegigandet** [comment]
image

**Comment by stephanegigandet** [comment]
@aleene sounds good, I added "added salt", can you approve the PR?

**Review by alexgarel — APPROVED** [review]

**Pull request merged**
