### PR TITLE
taxonomy: fix some unit test errors

### PR DESCRIPTION
**Pull request by benbenben2**
### What
Tackle error messages in perl unit tests (go to last closed PR, next to "merged commit", on the right, click on "View details", scroll down to "Perl unit tests", click on "Details", click on the gear on the right side, then "View raw logs", finally search for "ERROR - ")

I did ping the authors of the entries (using git blame) when I could not find a solution. Their help is welcome. If nobody reply within a few days I would suggest to ignore these errors.

Help for the reviewers below.

### Fixes details
EDIT: rollback some changes (strikethrough) because modified entries were used in unit tests.

1- (**NOT DONE**)
	nl:bamischijven already is associated to en:breaded-bami-patties - nl:bamischijven cannot be mapped to entry en:dutch-bami-disks
	nl:bamischijven already is associated to en:breaded-bami-patties - nl:bamischijven cannot be mapped to entry en:dutch-bami-disks
	in categories.txt, ping @aleene, can we put "en:Breaded Bami patties" and "en:Dutch Bami disks" in a single line (i.e., "en:Breaded Bami patties, Dutch Bami disks")?

2- (**DONE**)
en:cheeses-for-grilling already is a synonym of en:cheeses-for-grilling for entry en:cheeses-for-grilling - en:cheeses-for-grilling cannot be mapped to entry en:grilling-cheeses / en:grilling-cheeses
en:cheeses-for-grilling already is a synonym of en:cheeses-for-grilling for entry en:cheeses-for-grilling - en:cheeses-for-grilling cannot be mapped to entry en:grilling-cheeses / en:grilling-cheeses
nl:grillkazen already is associated to en:cheeses-for-grilling - nl:grillkazen cannot be mapped to entry en:grilling-cheeses
nl:grillkazen already is associated to en:cheeses-for-grilling - nl:grillkazen cannot be mapped to entry en:grilling-cheeses
in categories.txt, combine in 1 bloc

3- (**DONE**)
fr:mueslis-croustillants already is a synonym of fr:mueslis for entry en:mueslis - fr:mueslis-croustillants cannot be mapped to entry en:crunchy-mueslis / fr:mueslis-croustillants
fr:mueslis-croustillants already is a synonym of fr:mueslis for entry en:mueslis - fr:mueslis-croustillants cannot be mapped to entry en:crunchy-mueslis / fr:mueslis-croustillants
in categories.txt, rm from fr:mueslis, müesli, Mueslis croustillants, Granolas

4- (**DONE**)
nl:aspergesoepen already is associated to en:asparagus-soups - nl:aspergesoepen cannot be mapped to entry en:cream-of-asparagus-soups
nl:aspergesoepen already is associated to en:asparagus-soups - nl:aspergesoepen cannot be mapped to entry en:cream-of-asparagus-soups
in categories.txt, rm from "en:Cream of asparagus soups"

5- (**NOT DONE**)
	de:speck already is a synonym of de:marshmallows for entry en:marshmallows - de:speck cannot be mapped to entry en:bacon / de:speck
	de:speck already is a synonym of de:marshmallows for entry en:marshmallows - de:speck cannot be mapped to entry en:bacon / de:speck
	in categories.txt, ping @aleene, speck for marshmallows is short for Mausespeck, no idea how to fix duplicates.

6- (**DONE**)
en:strawberry-tart already is a synonym of en:strawberry-pies for entry en:strawberry-pies - en:strawberry-tart cannot be mapped to entry en:strawberry-tart / en:strawberry-tart
en:strawberry-tart already is a synonym of en:strawberry-pies for entry en:strawberry-pies - en:strawberry-tart cannot be mapped to entry en:strawberry-tart / en:strawberry-tart
en:strawberries-tart already is a synonym of en:strawberry-pies for entry en:strawberry-pies - en:strawberries-tart cannot be mapped to entry en:strawberry-tart / en:strawberry-tart
en:strawberries-tart already is a synonym of en:strawberry-pies for entry en:strawberry-pies - en:strawberries-tart cannot be mapped to entry en:strawberry-tart / en:strawberry-tart
fr:tartes-aux-fraises already is associated to en:strawberry-pies - fr:tartes-aux-fraises cannot be mapped to entry en:strawberry-tart
fr:tartes-aux-fraises already is associated to en:strawberry-pies - fr:tartes-aux-fraises cannot be mapped to entry en:strawberry-tart
in categories.txt, combine in 1 bloc

7- (**DONE**)
nl:taarten already is a synonym of nl:taarten for entry en:pies - nl:taarten cannot be mapped to entry en:tartlets / nl:taartjes
nl:taarten already is a synonym of nl:taarten for entry en:pies - nl:taarten cannot be mapped to entry en:tartlets / nl:taartjes
in categories.txt, rm taarten from en:Tartlets, move "nl_be:Taart, Taarten" under en:pies

8- (**DONE**)
nl:kreeft already is associated to en:lobster - nl:kreeft cannot be mapped to entry en:lobsters
nl:kreeft already is associated to en:lobster - nl:kreeft cannot be mapped to entry en:lobsters
in categories.txt, combine in 1 bloc (norway lobster and langoustine referred in agribalyse but lobsters and homards are written only. Also Langoustine in french is generic term which contains different species: https://fr.wikipedia.org/wiki/Langoustine, same goes for kreeft which contains zeekreeft and others species: https://nl.wikipedia.org/wiki/Kreeften)

9- (**DONE**)
fr:galettes-au-poisson already is a synonym of fr:crepes-au-poisson for entry en:crepes-filled-with-fish - fr:galettes-au-poisson cannot be mapped to entry en:fish-patties / fr:galettes-au-poisson
fr:galettes-au-poisson already is a synonym of fr:crepes-au-poisson for entry en:crepes-filled-with-fish - fr:galettes-au-poisson cannot be mapped to entry en:fish-patties / fr:galettes-au-poisson
in categories.txt, rm it from en:fish-patties 

10- (**DONE**)
bg:хранителни-добавки already is associated to en:food-additives - bg:хранителни-добавки cannot be mapped to entry en:dietary-supplements
bg:хранителни-добавки already is associated to en:food-additives - bg:хранителни-добавки cannot be mapped to entry en:dietary-supplements
in categories.txt, rm from en:Dietary (https://bg.wikipedia.org/iki/%D0%A5%D1%80%D0%B0%D0%BD%D0%B8%D1%82%D0%B5%D0%BB%D0%BD%D0%B0_%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BA%D0%B0)

11- (**DONE**)
	bg:натриев-цитрат already is a synonym of bg:e331 for entry en:e331 - bg:натриев-цитрат cannot be mapped to entry en:sodium-citrate / bg:натриев-цитрат
	bg:натриев-цитрат already is a synonym of bg:e331 for entry en:e331 - bg:натриев-цитрат cannot be mapped to entry en:sodium-citrate / bg:натриев-цитрат
	in additives.txt / in minerals.txt, ping @aleene  / @stephanegigandet, no idea how to fix duplicates.

12- (**DONE**)
hr:dl-alfa-tokoferil-acetat already is a synonym of hr:e307c for entry en:e307c - hr:dl-alfa-tokoferil-acetat cannot be mapped to entry en:dl-alpha-tocopheryl-acetate / hr:dl-alfa-tokoferil-acetat
hr:dl-alfa-tokoferil-acetat already is a synonym of hr:e307c for entry en:e307c - hr:dl-alfa-tokoferil-acetat cannot be mapped to entry en:dl-alpha-tocopheryl-acetate / hr:dl-alfa-tokoferil-acetat
keep in vitamin.txt, delete in additives.txt

~~13-
fi:c-vitamiini already is a synonym of fi:e300 for entry en:e300 - fi:c-vitamiini cannot be mapped to entry en:vitamin-c / fi:c-vitamiini
fi:c-vitamiini already is a synonym of fi:e300 for entry en:e300 - fi:c-vitamiini cannot be mapped to entry en:vitamin-c / fi:c-vitamiini
fr:vitamine-c already is a synonym of fr:e300 for entry en:e300 - fr:vitamine-c cannot be mapped to entry en:vitamin-c / fr:vitamine-c
fr:vitamine-c already is a synonym of fr:e300 for entry en:e300 - fr:vitamine-c cannot be mapped to entry en:vitamin-c / fr:vitamine-c
keep in vitamin.txt, delete in additives.txt~~

14- (**DONE**)
ca:acid-inosinic already is a synonym of ca:e630 for entry en:e630 - ca:acid-inosinic cannot be mapped to entry en:inosine-monophosphate / ca:acid-inosinic
ca:acid-inosinic already is a synonym of ca:e630 for entry en:e630 - ca:acid-inosinic cannot be mapped to entry en:inosine-monophosphate / ca:acid-inosinic
pt:acido-inosinico already is a synonym of pt:e630 for entry en:e630 - pt:acido-inosinico cannot be mapped to entry en:inosine-monophosphate / pt:acido-inosinico
pt:acido-inosinico already is a synonym of pt:e630 for entry en:e630 - pt:acido-inosinico cannot be mapped to entry en:inosine-monophosphate / pt:acido-inosinico
fr:acide-inosinique already is a synonym of fr:e630 for entry en:e630 - fr:acide-inosinique cannot be mapped to entry en:inosine-monophosphate / fr:acide-inosinique
fr:acide-inosinique already is a synonym of fr:e630 for entry en:e630 - fr:acide-inosinique cannot be mapped to entry en:inosine-monophosphate / fr:acide-inosinique
in nucleotides.txt / in additives.txt, rm from nucleotides.txt

15- (**DONE**)
fi:inosiinimonofosfaatti already is a synonym of fi:e630 for entry en:e630 - fi:inosiinimonofosfaatti cannot be mapped to entry en:inosine-monophosphate / fi:inosiinimonofosfaatti
fi:inosiinimonofosfaatti already is a synonym of fi:e630 for entry en:e630 - fi:inosiinimonofosfaatti cannot be mapped to entry en:inosine-monophosphate / fi:inosiinimonofosfaatti
in nucleotides.txt / in additives.txt, rm from additives.txt

~~16-
fr:chlorure-de-choline already is a synonym of fr:e1001 for entry en:e1001 - fr:chlorure-de-choline cannot be mapped to entry en:choline-chloride / fr:chlorure-de-choline
fr:chlorure-de-choline already is a synonym of fr:e1001 for entry en:e1001 - fr:chlorure-de-choline cannot be mapped to entry en:choline-chloride / fr:chlorure-de-choline
in other_nutritional_substances.txt / in additives.txt, not sure rm from additives.txt~~

17- (**DONE**)
de:gerinnungsmittel already is a synonym of de:koagulationsmittel for entry en:coagulant - de:gerinnungsmittel cannot be mapped to entry en:clotting-agents / de:gerinnungsmittel
de:gerinnungsmittel already is a synonym of de:koagulationsmittel for entry en:coagulant - de:gerinnungsmittel cannot be mapped to entry en:clotting-agents / de:gerinnungsmittel
in ingredients.txt / in additives_classes.txt, combine in 1 block in aditives_classes.txt (and remove from ingredients.txt)

18- (**NOT DONE**)
	bg:кисело-мляко already is associated to en:yogurt - bg:кисело-мляко cannot be mapped to entry en:soured-milk
	bg:кисело-мляко already is associated to en:yogurt - bg:кисело-мляко cannot be mapped to entry en:soured-milk
	in ingredients.txt, ping @stephanegigandet / @mahlzahn, the bulgarian name for yogurt is litteraly sour-yogurt, no idea how to fix duplicates.

19- (**NOT DONE**)
	nl:steenzout already is associated to en:rock-salt - nl:steenzout cannot be mapped to entry nl:steenzout
	nl:steenzout already is associated to en:rock-salt - nl:steenzout cannot be mapped to entry nl:steenzout
	in ingredient.txt, could not find duplicates (in sto file?)

20- (**DONE**)
bg:напълно-хидрогенирана-палмова-мазнина already is a synonym of bg:напълно-хидрогенирана-палмова-мазнина for entry en:totally-hydrogenated-palm-fat - bg:напълно-хидрогенирана-палмова-мазнина cannot be mapped to entry en:totally-hydrogenated-palm-oil / bg:напълно-хидрогенирано-палмово-масло
bg:напълно-хидрогенирана-палмова-мазнина already is a synonym of bg:напълно-хидрогенирана-палмова-мазнина for entry en:totally-hydrogenated-palm-fat - bg:напълно-хидрогенирана-палмова-мазнина cannot be mapped to entry en:totally-hydrogenated-palm-oil / bg:напълно-хидрогенирано-палмово-масло
in ingredients.txt, масло (oil) vs мазнина (fat, https://www.wikidata.org/wiki/Q127980), rm from oil.

21- (**DONE**)
nl:extra-vierge-olijfolie already is a synonym of nl:olijfolie-van-de-eerste-persing for entry en:virgin-olive-oil - nl:extra-vierge-olijfolie cannot be mapped to entry en:extra-virgin-olive-oil / nl:olijfolie-extra-vierge
nl:extra-vierge-olijfolie already is a synonym of nl:olijfolie-van-de-eerste-persing for entry en:virgin-olive-oil - nl:extra-vierge-olijfolie cannot be mappperled to entry en:extra-virgin-olive-oil / nl:olijfolie-extra-vierge
in ingredients.txt, rm from "en:virgin olive oil"

22- (**DONE**)
bg:ябълков-оцет already is associated to en:apple-vinegar - bg:ябълков-оцет cannot be mapped to entry en:apple-cider-vinegar
bg:ябълков-оцет already is associated to en:apple-vinegar - bg:ябълков-оцет cannot be mapped to entry en:apple-cider-vinegar
in ingredients.txt, rm from "en:apple cider vinegar"

23- (**DONE**)
bg:брашно-тип-500 already is a synonym of bg:бяло-пшенично-брашно-тип-500 for entry en:wheat-flour-type-500 - bg:брашно-тип-500 cannot be mapped to entry en:wheat-flour-type-550 / bg:бяло-пшенично-брашно-тип-550
bg:брашно-тип-500 already is a synonym of bg:бяло-пшенично-брашно-тип-500 for entry en:wheat-flour-type-500 - bg:брашно-тип-500 cannot be mapped to entry en:wheat-flour-type-550 / bg:бяло-пшенично-брашно-тип-550
in ingredients.txt, rm from "en:wheat flour type 550"

24- (**DONE**)
es:maiz-dulce already is associated to en:sweet-corn - es:maiz-dulce cannot be mapped to entry en:sweetcorn
es:maiz-dulce already is associated to en:sweet-corn - es:maiz-dulce cannot be mapped to entry en:sweetcorn
fr:mais-doux already is associated to en:sweet-corn - fr:mais-doux cannot be mapped to entry en:sweetcorn
fr:mais-doux already is associated to en:sweet-corn - fr:mais-doux cannot be mapped to entry en:sweetcorn
in ingredients.txt, merge 2nd bloc into 1st one.

<en:corn
en:sweet corn
de:Süßmais, Zuckermais
es:maíz dulce, maiz dulce
fr:maïs doux, mais doux
nl:suikermaïs

<en:corn
en:sweetcorn
bg:сладка царевица
de:Süssmais
es:maíz dulce
fi:sokerimaissi
fr:maïs doux
hu:csemegekukorica
it:mais dolce
ja:スイートコーン
nl:zoete maïs
\# ingredient/fr:maïs-doux 103 products in 5 languages @2018-09-24

25- (**DONE**)
nl:gekarameliseerde-suiker already is a synonym of nl:e150a for entry en:e150a - nl:gekarameliseerde-suiker cannot be mapped to entry en:caramelised-sugar / nl:gekarameliseerde-suiker
nl:gekarameliseerde-suiker already is a synonym of nl:e150a for entry en:e150a - nl:gekarameliseerde-suiker cannot be mapped to entry en:caramelised-sugar / nl:gekarameliseerde-suiker
in ingredients.txt / in additives.txt, rm from additives.txt (other langagues have "color" not "sugar")

26- (**DONE**)
bg:набухвател already is a synonym of bg:набухвател for entry en:raising-agent - bg:набухвател cannot be mapped to entry en:baking-powder / bg:бакпулвер
bg:набухвател already is a synonym of bg:набухвател for entry en:raising-agent - bg:набухвател cannot be mapped to entry en:baking-powder / bg:бакпулвер
in ingredients.txt / in additives_classes.txt, rm from ingredients.txt (translate the bg entry for https://www.wikidata.org/wiki/Q29476)

27- (**DONE**)
bg:мая already is associated to en:yeast - bg:мая cannot be mapped to entry en:baker-s-yeast
bg:мая already is associated to en:yeast - bg:мая cannot be mapped to entry en:baker-s-yeast
in ingredients.txt, rm from "en:baker-s-yeast"

~~28-
	bg:закваска already is a synonym of bg:закваска for entry en:ferment - bg:закваска cannot be mapped to entry en:sourdough / bg:квас
	bg:закваска already is a synonym of bg:закваска for entry en:ferment - bg:закваска cannot be mapped to entry en:sourdough / bg:квас
	in ingredients.txt, ping @Roto15 / @stephanegigandet, no idea how to fix duplicates.~~

29- (**DONE**)
fr:phosphate already is a synonym of fr:orthophosphate for entry fr:orthophosphate - fr:phosphate cannot be mapped to entry en:phosphate / fr:phosphates
fr:phosphate already is a synonym of fr:orthophosphate for entry fr:orthophosphate - fr:phosphate cannot be mapped to entry en:phosphate / fr:phosphates
in minerals.txt / in ingredients.txt, rm in minerals and add orthophosphate as synonym in ingredients.

30- (**NOT DONE**)
	bg:e500ii already is associated to en:e500ii - bg:e500ii cannot be mapped to entry bg:e500ii
	bg:e500ii already is associated to en:e500ii - bg:e500ii cannot be mapped to entry bg:e500ii
	in additives.txt, could not find duplicates (in sto file?)

31- (**DONE**)
bg:кресон already is associated to en:watercress - bg:кресон cannot be mapped to entry en:garden-cress
bg:кресон already is associated to en:watercress - bg:кресон cannot be mapped to entry en:garden-cress
in ingredients.txt, rm from en:Watercress, same "genre" (lepidium) in wikipedia pages (https://bg.wikipedia.org/wiki/%D0%9A%D1%80%D0%B5%D1%81%D0%BE%D0%BD , https://fr.wikipedia.org/wiki/Cresson_al%C3%A9nois)

32- (**NOT DONE**)
	bg:подправка already is associated to en:condiment - bg:подправка cannot be mapped to entry en:spice
	bg:подправка already is associated to en:condiment - bg:подправка cannot be mapped to entry en:spice
	in ingredients.txt, ping @Roto15, no idea how to fix duplicates.

33- (**NOT DONE**)
	bg:смес-от-подправки already is associated to en:mixed-condiments - bg:смес-от-подправки cannot be mapped to entry en:mixed-spices
	bg:смес-от-подправки already is associated to en:mixed-condiments - bg:смес-от-подправки cannot be mapped to entry en:mixed-spices
	in ingredients.txt, ping @svensven  / @Roto15, no idea how to fix duplicates.

34- (**NOT DONE**)
	fr:epices-et-plantes-aromatique already is associated to en:herbs-and-spices - fr:epices-et-plantes-aromatique cannot be mapped to entry fr:epices-et-plantes-aromatique
	fr:epices-et-plantes-aromatique already is associated to en:herbs-and-spices - fr:epices-et-plantes-aromatique cannot be mapped to entry fr:epices-et-plantes-aromatique
	in ingredients.txt, could not find duplicates (in sto file?)

35- (**DONE**)
bg:куркумин already is a synonym of bg:e100 for entry en:e100 - bg:куркумин cannot be mapped to entry en:turmeric / bg:куркума
bg:куркумин already is a synonym of bg:e100 for entry en:e100 - bg:куркумин cannot be mapped to entry en:turmeric / bg:куркума
in ingredients.txt / additives.txt, delete from ingredient.txt (comparison between wikidata items)

36- (**DONE**)
bg:водорасли already is associated to en:algae - bg:водорасли cannot be mapped to entry en:seaweed
bg:водорасли already is associated to en:algae - bg:водорасли cannot be mapped to entry en:seaweed
in ingredients.txt, rm from "en:seaweed" (https://bg.wikipedia.org/wiki/%D0%92%D0%BE%D0%B4%D0%BE%D1%80%D0%B0%D1%81%D0%BB%D0%B8)

37- (**NOT DONE**)
	fr:oeufs-d-elevage-au-sol already is associated to en:barn-eggs - fr:oeufs-d-elevage-au-sol cannot be mapped to entry fr:oeufs-d-elevage-au-sol
	fr:oeufs-d-elevage-au-sol already is associated to en:barn-eggs - fr:oeufs-d-elevage-au-sol cannot be mapped to entry fr:oeufs-d-elevage-au-sol
	in ingredients.txt, could not find duplicates (in sto file?)

38- (**DONE**)
bg:глазура already is a synonym of bg:покритие for entry en:coating - bg:глазура cannot be mapped to entry en:glaze / bg:глазура
bg:глазура already is a synonym of bg:покритие for entry en:coating - bg:глазура cannot be mapped to entry en:glaze / bg:глазура
in ingredients.txt, rm it from en:coating (глазура = glazura in latin letters)

39- (**DONE**)
de:natriumcarbonat already is a synonym of de:e500 for entry en:e500 - de:natriumcarbonat cannot be mapped to entry en:e500i / de:e500i
de:natriumcarbonat already is a synonym of de:e500 for entry en:e500 - de:natriumcarbonat cannot be mapped to entry en:e500i / de:e500i
in additives.txt, rm from de:E500 (only plural should be in E500)

40- (**DONE**)
en:puffed-lentil-cakes has an undefined parent 
in categories.txt, split simple pulse vs puffed
rm:
<en:Legumes and their products
en:Puffed pulse cakes
de:Hülsenfruchtwaffeln
es:Tortitas de legumbres
fr:Galettes de légumineuses soufflées
it:Galetti di legumi
nl:Peulvruchtenwafels

<en:Cakes of pulses
en:Puffed lentil cakes
de:linsenwaffeln
es:tortitas de lentejas infladas
fr:galettes de lentilles soufflées
it:galetti di lenticchie soffiate
nl:linzenwafels
pt:geletes de lentilha

replace by:
<en:Legumes and their products
en:pulse cakes, cakes of pulses
de:hülsenfruchtwaffeln
es:tortitas de legumbres
it:galetti di legumi
nl:peulvruchtenwafels

<en:pulse cakes
en:Puffed pulse cakes
fr:galettes de légumineuses soufflées

<en:pulse cakes
en:lentil cakes
de:linsenwaffeln
nl:Linzenwafels
pt:Geletes de lentilha

<en:lentil cakes
en:Puffed lentil cakes
es:Tortitas de lentejas infladas
fr:Galettes de lentilles soufflées
it:Galetti di lenticchie soffiate

41- (**DONE**)
fr:pain-de-mie-au-son-de-ble has an undefined parent 
fr:pain-de-mie-aux-cereales has an undefined parent 
fr:pain-de-mie-complet has an undefined parent 
in ingredients.txt, update parent to "<en:special bread", update parent of "fr:pain de mie" to be also "<en:special bread"

### CODE REVIEW

**Comment by stephanegigandet** [comment]
> in additives.txt / in minerals.txt, ping @aleene / @stephanegigandet, no idea how to fix duplicates.

entries that are in additives.txt or minerals.txt can be removed from ingredients.txt, but we don't have a good system yet for entries that are both in additives and minerals unfortunately, so currently we need to leave them, and ignore the error messages for those.

**Comment by stephanegigandet** [comment]
> EDIT: rollback some changes (strikethrough) because modified entries were used in unit tests.

We can change the unit tests, but I suggest we make it afterwards, in a separate PR, with just the changes that affect unit tests.

**Comment by benbenben2** [comment]
> > in additives.txt / in minerals.txt, ping @aleene / @stephanegigandet, no idea how to fix duplicates.
> 
> entries that are in additives.txt or minerals.txt can be removed from ingredients.txt, but we don't have a good system yet for entries that are both in additives and minerals unfortunately, so currently we need to leave them, and ignore the error messages for those.

Then, let's ignore that one.


> > EDIT: rollback some changes (strikethrough) because modified entries were used in unit tests.
> 
> We can change the unit tests, but I suggest we make it afterwards, in a separate PR, with just the changes that affect unit tests.

I totally agree.

**Comment by aleene** [comment]
We need a rethink/redesign for these special ingredients.

**Review by stephanegigandet — APPROVED** [review]

**Comment by stephanegigandet** [comment]
@benbenben2 I approved the changes, do you want to merge them as-is, and then we can have a new PRs for all the "NOT DONE" items?

**Comment by alexgarel** [comment]
@benbenben2 kudos for this big work !

**Pull request merged**
