### PR TITLE
build: Migrate to Compose V2

### PR DESCRIPTION
**Pull request by hangy**
Docker Compose V1 (`docker-compose`)  is deprecated and should not be used any more. ([Source](https://docs.docker.com/compose/migrate/)) This replaces the old command with `docker compose`, which is Compose V2, and bundled with current Docker distributions.

### CODE REVIEW

**Review by alexgarel — APPROVED** [review]
LGTM ! Do you think we need to change version number ? is it big enough a change ?

Thanks @hangy :-)

**Comment by hangy** [comment]
> Do you think we need to change version number ? is it big enough a change ?

I don't know. Right now, this is mostly used for development, and the dev server, right? In some way, it could be regarded as a breaking change, because it won't work with old versions of Docker any more.

**Review by alexgarel — CHANGES_REQUESTED** [review]
@hangy your PR is fine, but I block it until I have install docker compose plugin on the staging environment !

**Review by alexgarel — APPROVED** [review]
staging is ready: `apt install docker-ce  docker-compose-plugin`

**Pull request merged**
