### PR TITLE
taxonomy: Add Idared (red) apples

### PR DESCRIPTION
**Pull request by Freso**
### What

Adds [Idared (red) apples](https://en.wikipedia.org/wiki/Idared) to the ingredients list, including related Danish and Swedish translations/synonyms.

### Screenshot
[missing ingredient](https://se.openfoodfacts.org/product/4056489447665/r%C3%B6da-%C3%A4pplen#health)

### Related issue(s) and discussion
- https://se.openfoodfacts.org/product/4056489447665/r%C3%B6da-%C3%A4pplen#health

### CODE REVIEW

**Comment by teolemon** [comment]
@Freso for what it's worth, I've rediscovered this on the wiki: https://wiki.openfoodfacts.org/Global_cultivar_taxonomy

**Review by aleene — APPROVED** [review]
Great you already did it. Solves this case. Still need to check how plurals in swedish and danish ae supported.

**Comment by benbenben2** [comment]
Great work @Freso!

**Pull request merged**
