### PR TITLE
Correct rdf data export (#811) and prevent broken CSV (#1585)

### LINKED ISSUE #1585: Dataset shouldn't contain specials chars between \000-\007 and \013-\037
**Summary:**

Chars between \000-\007 and \013-\037 decimal codes are not used anymore -- they come from the old times where they were useful to control printers and so on. They break the CSV file which can't be processed by common tools such as csvkit.

**Steps to reproduce:**

A file listing every line containing bad chars can be produced with a simple command line (see [bad-chars.txt](https://github.com/openfoodfacts/openfoodfacts-server/files/2698784/bad-chars.txt)):
```
$ perl -ne 'print if /[\000-\007\013-\037]/' fr.openfoodfacts.org.products.csv > bad-chars.csv
```

**Expected behavior:**

Every data entered in the database should be controlled.

### PR DESCRIPTION
**Pull request by CharlesNepote**
**Description:**

1. Encode URIs for RDF export (see #811).
2. Filter bad chars which break CSV and log it in a file (prevent but doesn't resolve #1585).

It seems to work with a test dataset of 177 products, but you might try it before deploying in production. I don't know how to test on the whole database.

You should review commit by commit if you want to see clearly what I've done. Commit 9fb9f6f is a mistake and I'm not very confident on commit deletion.

### CODE REVIEW

**Comment by CharlesNepote** [comment]
i made some tests with the whole database. There is still database content issues which break the CSV export. Strange database issue: there is a carriage return (\n) at the end of the GPS coordinates related to villecomtal-sur-arros-gers-france: 43.400279,0.199525.

So we have to sanitize the content of more fields than I expected.

I suggest to create a `sanitize_field_value()` function, probably in `ProductOpener::Data`, with two arguments:

- `$field_value`: the content to be sanitized;
- `$log`: optionally the output where to log each problem (example:  a filehandler, STDOUT, etc.)

The function would return the sanitized content. Non visible ASCII chars would be replaced by a space, except trailing whitespace or "\n", which would be trimed. Example:

`sanitize_field_value("something\nanother\n", $LOG)` => "something another"

The function would be used both in input (web app, imports) and in ouput (CSV exports).

@hangy @stephanegigandet ?

**Comment by hangy** [comment]
> i made some tests with the whole database. There is still database content issues which break the CSV export. Strange database issue: there is a carriage return (\n) at the end of the GPS coordinates related to villecomtal-sur-arros-gers-france: 43.400279,0.199525.

If there's just one case of bad source data, cleaning the source file might be easier?

> The function would return the sanitized content. Non visible ASCII chars would be replaced by a space, except trailing whitespace or "\n", which would be trimed.

Sounds good! If you want to replace all control characters, you could also use `\p{Cc}`.

> There might be an issue related to \n in some fields: do we have to delete it all the time?

I don't think so. For CSV, [RFC 4180](https://tools.ietf.org/html/rfc4180#section-2) clearly states that fields containing CRLF should be possible (but be quoted with double quotes). In XML, line breaks should be fine in attributes and values, even though they might need to be used with `<![CDATA[` to avoid incorrect with some XML parsers. Therefore, multi-line text should be valid field/attribute/column content.

**Comment by CharlesNepote** [comment]
Ok I made more testings and enhance the exporter:
- prevent perl warnings
- avoid control chars in rdf file

All seems to be fine. CSV file is ok. RDF file is valid (tested with `xmllint --stream en.openfoodfacts.localhost.products.rdf` doesn't provide any more issues).

For the moment I keep `sanitize_field_content()` in the `./scripts/export_database.pl`. I'll see later if it's interesting to move it to a perl OFF lib.

> If there's just one case of bad source data, cleaning the source file might be easier?

Yes we will have to clean to the source, but my experience is that the source might be corrupted again by the time, so I prefer to also clean the output.

> Sounds good! If you want to replace all control characters, you could also use `\p{Cc}`.

I never tested `\p{Cc}` so I keep char codes for the moment. Maybe I'll try later if it's quicker or if it consume less memory.

>> There might be an issue related to \n in some fields: do we have to delete it all the time?

> I don't think so. For CSV, RFC 4180 clearly states that fields containing CRLF should be possible (but be quoted with double quotes). In XML, line breaks should be fine in attributes and values, even though they might need to be used with `<![CDATA[` to avoid incorrect with some XML parsers. Therefore, multi-line text should be valid field/attribute/column content.

Yes RFC states CRLF is possible if fields are quoted. I think it's ok for small files, with few columns. But I think it's dangerous for huge files with dozens of columns as Open Food Facts dataset. In theory CSV tools should deal with CRLF in quoted fields but in fact some of them doesn't play well with that. Also you can't use regular unix text tools when your CSV contain CRLF inside fields: `sort`, `wc -l`, `head`, `grep`, etc., will not work well. It makes CSV manipulation more complex.

So I think we should avoid CRLF inside fields in the CSV export. RDF file might be another discussion.

My question was more related to the usages. Is there some OFF usages where CRLF are important inside a field? Maybe we could replace CRLF inside some field by a string: "---" or "\\\\" for example.

By the way we can see later and deploy this pull request which is a first good step.

**Comment by hangy** [comment]
> > Sounds good! If you want to replace all control characters, you could also use `\p{Cc}`.
> 
> I never tested `\p{Cc}` so I keep char codes for the moment. Maybe I'll try later if it's quicker or if it consume less memory.

It's just the Unicode category [Other, Control](https://www.fileformat.info/info/unicode/category/Cc/list.htm). It includes the range you already mentioned, plus different control characters outside of that range.

> My question was more related to the usages. Is there some OFF usages where CRLF are important inside a field? Maybe we could replace CRLF inside some field by a string: "---" or "\\" for example.

Fair point. I don't know about that. 🙂

**Comment by CharlesNepote** [comment]
> > > Sounds good! If you want to replace all control characters, you could also use `\p{Cc}`.
> > 
> > I never tested `\p{Cc}` so I keep char codes for the moment. Maybe I'll try later if it's quicker or if it consume less memory.
> 
> It's just the Unicode category [Other, Control](https://www.fileformat.info/info/unicode/category/Cc/list.htm). It includes the range you already mentioned, plus different control characters outside of that range.

Thanks for the link, I'll make some tests to see if there are issues with control chars outside of the range I focused on.

At first, I think we can merge and deploy my pull request as it solves a real issue. @stephanegigandet ?

**Pull request merged**
