### PR TITLE
fix: Deleted the Pros' Meet-Up link in Menu

### LINKED ISSUE #10070: Delete the button "Join the next Pro meetup" on the Pro platform
Delete the button "Join the next Pro meetup" on the Pro platform in the hamburger menu. 
After being tested several times, it turns out this format of support sessions doesn't really work for producers so we don't need the button anymore. 

Image

### PR DESCRIPTION
**Pull request by himanshisrestha**
### What
Deleted the button "Join the next Pros' Meet-Up" on the Pro platform in the hamburger menu.

### Screenshot

Before: 
Screenshot 2024-04-02 at 6 54 12 PM

After:
Screenshot 2024-04-02 at 6 54 32 PM

### Related issue(s) and discussion

- Fixes #10070

### CODE REVIEW

**Review by alexgarel — COMMENTED** [review]
Good, but could you also remove the "join_the_next_pros_meet_up" in the po files ? (at least in common.pot)

**Comment by himanshisrestha** [comment]
@alexgarel I should remove all the three of them right ? 
`msgctxt "join_the_next_pros_meet_up"
msgid "Join the next Pros' Meet-up"
msgstr ""`
this one for .po files and 
`msgctxt "join_the_next_pros_meet_up"
msgid "Join the next Pros' Meet-up"
msgstr "Join the next Pros' Meet-up"` 
this one for .pot files

Also is there any commands to be ran after these changes

**Comment by alexgarel** [comment]
@himanshisrestha 
> I should remove all the three of them right ?
Yes

> Also is there any commands to be ran after these changes
No

**Comment by himanshisrestha** [comment]
Thank you for the quick response 😄

**Comment by himanshisrestha** [comment]
Thank you for the quick guidance 😄

**Pull request merged**
