### PR TITLE
feat: parse origins of ingredients field

### PR DESCRIPTION
**Pull request by stephanegigandet**
Fixes partially #4461 (we could add support for more ways to describe ingredients, like "Strawberries from Spain").

Needed in particular for one producer who sent us data in the origins of ingredients field, in order to have it used for the Eco-Score computations.

### CODE REVIEW

**Review by alexgarel — CHANGES_REQUESTED** [review]
If it's not too much I would like a refactor to avoid duplicating.

**Comment by alexgarel** [comment]
Also @stephanegigandet  what about using more verbose regexp in our code: https://perldoc.perl.org/perlre#/x-and-/xx

This is very handy to comment what you are doing in an expression.

**Review by alexgarel — APPROVED** [review]
Let's merge and refactor later on as proposed by @stephanegigandet

**Comment by stephanegigandet** [comment]
> Also @stephanegigandet what about using more verbose regexp in our code: https://perldoc.perl.org/perlre#/x-and-/xx
> 
> This is very handy to comment what you are doing in an expression.

Yes, we should do that, definitely.

**Comment by stephanegigandet** [comment]
> 

Thanks, opened an issue for not forgetting it: https://github.com/openfoodfacts/openfoodfacts-server/issues/7028

And start of refactor is here: https://github.com/openfoodfacts/openfoodfacts-server/pull/7026

**Pull request merged**
