### PR TITLE
chore: dutch taxonomy

### PR DESCRIPTION
**Pull request by aleene**
### What
Going through latest added products and added products in 2020, to see if the taxonomies are complete.

### CODE REVIEW

**Comment by aleene** [comment]
Time to recommence my work on the dutch products.

**Comment by aleene** [comment]
@alexgarel or @stephanegigandet this is a fail, which is to difficult for me.

**Comment by aleene** [comment]
Thanks

**Review by stephanegigandet — APPROVED** [review]
Thank you!

**Pull request merged**
