### PR TITLE
Delete comment-ajouter-un-produit.html

### PR DESCRIPTION
**Pull request by teolemon**

### CODE REVIEW

**Comment by teolemon** [comment]
@stephanegigandet it can be fully deleted: we have 3 copies of it
https://github.com/openfoodfacts/openfoodfacts-server/blob/master/lang/fr/texts/comment-ajouter-un-produit.html
https://github.com/openfoodfacts/openfoodfacts-server/blob/master/lang/en/texts/comment-ajouter-un-produit.html
https://github.com/openfoodfacts/openfoodfacts-server/blob/master/html/images/misc/comment-ajouter-un-produit.html

**Comment by teolemon** [comment]
Besides, we have:
https://github.com/openfoodfacts/openfoodfacts-server/blob/master/lang/en/texts/how-to-add-a-product.html
https://github.com/openfoodfacts/openfoodfacts-server/blob/master/lang/fr/texts/how-to-add-a-product.html

**Comment by VaiTon** [comment]
@stephanegigandet what should we do?

**Comment by teolemon** [comment]
it's fixed in master. closing

**Pull request closed without merging**
