### PR TITLE
Reenable the call to translations on more languages

### PR DESCRIPTION
**Pull request by teolemon**
### What
- Reenable the call to translations on more languages
- Related to https://github.com/openfoodfacts/openfoodfacts-server/pull/5646

### Why
Speed up translations
image

### How can I see it ?
https://ru.openfoodfacts.org/ (you have to be logged in, bottom right)

### CODE REVIEW

**Review by stephanegigandet — CHANGES_REQUESTED** [review]
The syntax is incorrect, this would make all web pages fail to render at all.

Changes to the template should really be tested with docker first.

I'll fix the syntax and try to add tests for the templates so that they can't be merged if there are errors.

**Comment by stephanegigandet** [comment]
Trying the new templates tests.

**Comment by teolemon** [comment]
@stephanegigandet you need to rebase before

**Comment by teolemon** [comment]
done

**Comment by stephanegigandet** [comment]
Test is failing. Good :)

```
#   Failed test at t/templates.t line 41.
# failed to fetch template: file error - parse error - web/common/site_layout.tt.html line 302: unexpected token (in)
#   [% IF lc in "aa","ar","ber","br","co","fa","ga","hy","iu","kk","lb","me","mr","ne","no","ry","sd","sl","sq","st","tg","tr","tzl","val","wa","zea","zu","ach","as","bg","bs","crs","eo","fi","gd","hi","id","ja","km","ku","lo","mg","ms","nr","pa","qu","sa","sg","sma","sr","sv","th","ts","ug","ve","wo","zh",af","ast","bm","ca","cs","el","fil","gl","hr","ii","jv","kmr","kw","mi","mt","pl","rm","sat","sh","sn","sr_CS","sw","ti","tt","uk","vec","xh","ak","az","bn","ce","cv","et","fo","gu","ht","is","ka","kmr_TR","ky","lt","ml","my","oc","ro","sc","si","so","sr_RS","ta","tl","tw","ur","vi","yi","am","be","bo","chr","cy","eu","ha","hu","kab","kn","la","lv","mn","nb","nn","ru","sco","sk","son","ss","te","tn","ty","uz","vls","yo" %]
```

**Review by stephanegigandet — APPROVED** [review]
This works.

**Pull request merged**
