### PR TITLE
fix: Barcode is not visible in the edit mode

### LINKED ISSUE #7786: NEW DESIGN: The barcode is not visible in edit mode
### What
- NEW DESIGN: The barcode is not visible in edit mode
- example: https://world-fr.openfoodfacts.org/cgi/product.pl?type=edit&code=07370793

### Part of
- #7295

### PR DESCRIPTION
**Pull request by Sakshamgupta90**
### Screenshot
Screenshot 2022-12-16 at 8 24 17 PM

### Related issue(s) and discussion
- Fixes #7786

### CODE REVIEW

**Comment by Sakshamgupta90** [comment]
Hi @stephanegigandet, sorry due to some issue the previous PR gets deleted. I have make the changes as you have said. :)

**Comment by alexgarel** [comment]
@Sakshamgupta90 small tip: pay attention to your PR titles.
We use conventional commit spec, with those possible prefixes:

  fix
  docs
  style
  refactor
  test
  build
  ci
  chore
  revert
  l10n
  taxonomy

**Review by alexgarel — APPROVED** [review]
Perfect, thanks @Sakshamgupta90  !

**Comment by Sakshamgupta90** [comment]
Hi @alexgarel, Thanks a lot and I will definitely keep in my mind this, sorry for that. One more thing, I have planned that first of all I will try to fix those issues which are related to the new Design. So should I proceed with it, or I should start contributing in some bugs and all?

**Pull request merged**
