### PR TITLE
taxonomy: adding Cocamidopropyl betaine in allergens

### PR DESCRIPTION
**Pull request by fuddl**
I need to watch out for Cocamidopropyl betaine because I might be allergic to it. It wasn't yet listed as a allergent. [According to Wikipedia](https://en.wikipedia.org/wiki/Cocamidopropyl_betaine#Safety) the allergent status is  controversial. 🤷

### CODE REVIEW

**Comment by alexgarel** [comment]
@stephanegigandet and @teolemon I think we have a precise policy for this allergens taxonomy. How is it ?

**Comment by benbenben2** [comment]
@fuddl, you have to prefix the title of your pull request by "taxonomy: " (all in lower case, it seems that the capital letter does not work)

**Comment by stephanegigandet** [comment]
> @stephanegigandet and @teolemon I think we have a precise policy for this allergens taxonomy. How is it ?

For food, we limit the allergens to the 14 or so allergens that must be marked on the package.

For cosmetics, we don't have an official list to rely on. The issue is that almost all ingredients can be allergens to some people, so instead of using the allergens taxonomy, it's probably better to rely on an ingredients taxonomy, and build features so that anyone can state which ingredients they are allergic to.

**Review by stephanegigandet — APPROVED** [review]

**Comment by stephanegigandet** [comment]
We can add it. Note that Open Beauty Facts deployments are currently frozen, as we have not deployed the new design on OBF yet.

**Pull request merged**
