### PR TITLE
update nginx config from production

### PR DESCRIPTION
**Pull request by stephanegigandet**
There may be updates that were done on github that we want to put in production.

off-fr is a special config we use so that we can cache things etc. when OFF goes on TV in France.

### CODE REVIEW

**Comment by hangy** [comment]
> off-fr is a special config we use so that we can cache things etc. when OFF goes on TV in France.

Sorry for being that annoying guy, but why treat France differently? Wouldn't it be better to apply that same caching algorithm to all subdomains, so that there's no difference in application behaviour between subdomains? What's the downside? This is pretty confusing, as present by #2091.

**Comment by stephanegigandet** [comment]
Well off-fr is something we have done while the server was unresponsive under heavy load, trying to make it go back to life as quickly as possible. It hasn't been planned. It's also a way to protect the rest of OFF when one country gets overloaded: we turn off certain features like search, and we do very aggressive caching (e.g. serving static files from nginx).

**Comment by VaiTon** [comment]
We could keep the configuration and just rename and change it so that its effect is available side-wide.

**Comment by stephanegigandet** [comment]
Can we merge this?

**Pull request merged**
