### PR TITLE
Rename haute-valeur-environnementale-90x90.svg + Halal Labels

### PR DESCRIPTION
**Pull request by teolemon**
Rename haute-valeur-environnementale-90x90.svg to haute-valeur-environnementale.90x90.svg

### CODE REVIEW

**Comment by teolemon** [comment]
Re-requesting review, since I added halal labels

**Comment by stephanegigandet** [comment]
The way the images work:

html/images/lang/en/labels/[English name of the label, if it exists in the taxonomy].90x90.png
html/images/lang/fr/labels/[French name of the label, if it exists in the taxonomy].90x90.png

So we should not have html/images/lang/en/labels/controle-de-la-mosquee-d-evry-courcouronnes.90x90.png for instance

**Comment by teolemon** [comment]
Well, if we do the way you suggest, we don't get the labels displayed on the English version @stephanegigandet

**Comment by teolemon** [comment]
EG: AB-Bio that I had to copy paste in prod

**Pull request merged**
