### PR TITLE
Pr/1662

### PR DESCRIPTION
**Pull request by teolemon**
Based on @aleene 's branch

### CODE REVIEW

**Comment by teolemon** [comment]
@aleene @stephanegigandet 
I took @aleene 's version without questionning it.

**Comment by aleene** [comment]
See you picked an old version. I add a few ingredients every day, so you should stop me, if you want to do somthing which takes some time.

**Comment by teolemon** [comment]
I picked your branch at latest revision ?

**Comment by stephanegigandet** [comment]
This pull requet can be deleted.

**Pull request closed without merging**
