### PR TITLE
test repair

### PR DESCRIPTION
**Pull request by aleene**
**Description:**
Repaired the test.

There is an issue with en:turmeric/kurkuma and en:E100/curcumine. The ingredients and additives interfere.

Need to move turmeric from ingredients to additives.

**Related issues and discussion:** #5791

### CODE REVIEW

**Review by stephanegigandet — COMMENTED** [review]
I don't think turmeric should be moved in E100, only curcumin is listed for E100 in https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02008R1333-20141106&rid=1

**Comment by stephanegigandet** [comment]
e.g. for French, we have 783 products that list "curcuma" as an ingredient, but none that lists it as colouring.

So we should keep turmeric as an ingredient, and curcumine as an additive. And there should be no overlap between their synonyms.

**Comment by aleene** [comment]
Is indeed better. However I guess that most turmeric is just added a colorant. And it does contain some curcumine. So if we say E100, it is not wrong.

**Review by stephanegigandet — APPROVED** [review]
Thanks

**Pull request merged**
