### PR TITLE
Added translations in Bulgarian in Taxonomies

### PR DESCRIPTION
**Pull request by Roto15**
**Checklist:**

Make sure you've done all the following (You can delete the checklist before submitting)

- [x] Code is well documented
- [ ] Include unit tests for new functionality
- [ ] Code passes GitHub workflow checks in your branch
- [ ] If you have multiple commits please combine them into one commit by squashing them.
- [ ] Read and understood the [contribution guidelines](https://github.com/openfoodfacts/openfoodfacts-server/blob/main/CONTRIBUTING.md)

**Description:**

Describe the changes made and why they were made instead of how they were made.

**Related issues and discussion:** #[ISSUE NUMBER]

### CODE REVIEW

**Review by stephanegigandet — APPROVED** [review]
Thank you!

**Comment by Roto15** [comment]
Ok,so if the changes are approved and will be visible in the app soon, should I close this pull request?Thanks

**Comment by stephanegigandet** [comment]
Closing and reopening to rerun tests on new main branch.

**Comment by stephanegigandet** [comment]
@Roto15 if the tests don't pass, could you make a pull on main, and merge it with your branch?

**Pull request merged**
