### PR TITLE
Spanish Synonyms

### PR DESCRIPTION
**Pull request by mrmd8**
Adding several Spanish synonyms. Zumo = Jugo (juice)

Thanks

### CODE REVIEW

**Comment by stephanegigandet** [comment]
> Adding several Spanish synonyms. Zumo = Jugo (juice)

Hi @mrmd8 , in fact at the top of ingredients.txt, we have this:

synonyms:es:zumo, jugo

It makes jugo a synonym of zumo for all entries that contain it, so it's not needed to repeat it everywhere.

We also have 
es:soja, soya

So all entries that include soja will also match soya.

There is an issue when there are 2 synonyms (e.g. when we have "zumo de soja" in the taxonomy, and we want to match "jugo de soya"). I'll fix the code so that it works.

**Comment by aleene** [comment]
Note that this is also in the ingredients processing. And it is kept separate as `zumo` is only applicable to fruit.

**Comment by mrmd8** [comment]
> > Adding several Spanish synonyms. Zumo = Jugo (juice)
> 
> Hi @mrmd8 , in fact at the top of ingredients.txt, we have this:
> 
> synonyms🇪🇸zumo, jugo
> 
> It makes jugo a synonym of zumo for all entries that contain it, so it's not needed to repeat it everywhere.
> 
> We also have
> es:soja, soya
> 
> So all entries that include soja will also match soya.
> 
> There is an issue when there are 2 synonyms (e.g. when we have "zumo de soja" in the taxonomy, and we want to match "jugo de soya"). I'll fix the code so that it works.

Hi @stephanegigandet , thanks. I had read the comments but missed that. I added the synonyms this way because I uploaded a few fruit juices through the app but "jugo de _fruit_" was being recognized as _fruit_ instead of "_fruit_ juice". I first started correcting the ingredients list changing "jugo" to "zumo" which worked great, but I though it would be the best for the ingredients to be recognized as they are officially listed 

Thanks again!

**Comment by stephanegigandet** [comment]
> "jugo de _fruit_" was being recognized as _fruit_ instead of "_fruit_ juice"

@mrmd8 : This is in fact intended, as @aleene was saying in another comment above. Whenever there is "juice of something" / "something juice", we mark the ingredient as "something" with the ingredient processing "juice".

That way we do not have to list all "juice of something".

**Comment by mrmd8** [comment]
> > "jugo de _fruit_" was being recognized as _fruit_ instead of "_fruit_ juice"
> 
> @mrmd8 : This is in fact intended, as @aleene was saying in another comment above. Whenever there is "juice of something" / "something juice", we mark the ingredient as "something" with the ingredient processing "juice".
> 
> That way we do not have to list all "juice of something".

@stephanegigandet I see. What is not clear to me is why it behaves differently when a product states "jugo de _ any fruit_" (registering it as _fruit_, the unprocessed fruit) and when it states "zumo de _fruit_", registering it as "_fruit_-juice". Perhaps I'm misunderstanding something (since I'm too new to this project), or something is lost in translation, so I'l put a few examples:

 1) [7798085680165](https://ar.openfoodfacts.org/producto/7798085680165/jugo-de-pomelo-con-pulpa-citric) Jugo de pomelo stands for grapefruit juice but is recognized as grapefruit instead
2) [01261615](https://ar.openfoodfacts.org/producto/01261615/pronto-manzana-baggio) "jugo concentrado de manzana" -> "concentrated apple juice" but recognized as apple. _With this one I might be mixing things since "concentrated apple juice" is translated as es:jarabe de manzana_

This was the behavior with every juice last week, now "jugo de" seems to be recognized the same way as "zumo de" in most cases

Again, I'm sorry if I'm misunderstanding sorry or going against the flow. Thanks

**Comment by mrmd8** [comment]
Done. Thanks

**Pull request merged**
