### PR TITLE
taxonomy: Taxonomy hr 20230401

### PR DESCRIPTION
**Pull request by benbenben2**
used chatgpt to pluralize categories in HR
+ added few ingredients/labels

### CODE REVIEW

**Review by stephanegigandet — APPROVED** [review]
We can merge as-is, but it would be a good idea to also keep the singular as a synonym, so that we can match the category if someone uses the singular (or if we get it from a producer import)

**Comment by benbenben2** [comment]
Yes, yes, yes. I will apply those changes

**Comment by benbenben2** [comment]
@stephanegigandet, singular are kept in the last commit

**Review by stephanegigandet — APPROVED** [review]
Perfect, thank you!

**Pull request merged**
