### PR TITLE
taxonomy: Add `sv:krispiga flingor` to ingredients

### PR DESCRIPTION
**Pull request by Freso**
### What

Adds taxonomy ingredient entry for `sv:krispiga flingor`.

I wasn’t exactly sure where to put it, but given that the [only current occurrences](https://se.openfoodfacts.org/ingredient/krispiga-flingor) are corn/rice/wheat/rye/sv:korn based, I put it as a child of `cereal flakes`.

I also didn’t know whether to add the English translation or not, so I added it, but commented‐out. 🙃 This way, non-Swedish speakers at least have an idea of what it is when looking at the list.

### Screenshot

[unknown ingredient](https://se.openfoodfacts.org/product/7311312007100/crunchy-granola-%C3%A4pple-kanel-risenta#health)

### Related issue(s) and discussion

- https://openfoodfacts.slack.com/archives/C06A7LENM/p1723472446091359?thread_ts=1721573740.332399&cid=C06A7LENM

### CODE REVIEW

**Comment by Freso** [comment]
Let me know if I should remove the commented‐out English entirely, if I should un‐out‐comment it, or do something else with it.

**Comment by stephanegigandet** [comment]
> Let me know if I should remove the commented‐out English entirely, if I should un‐out‐comment it, or do something else with it.

Thank you @Freso ! For ingredients, we try to always put an English name first, so please un-comment it.

**Review by stephanegigandet — APPROVED** [review]
Thank you!

**Comment by Freso** [comment]
> For ingredients, we try to always put an English name first, so please un-comment it.

Not sure if I made it clear, but the English name is just an off-the-cuff translation I made, not one that I have seen anywhere. If it’s still useful to have it properly in there, I will uncomment, just want to make very explicit that it’s just a loose translation and not a wording that is found on any products that I am aware of. :)

**Comment by stephanegigandet** [comment]
> > For ingredients, we try to always put an English name first, so please un-comment it.
> 
> Not sure if I made it clear, but the English name is just an off-the-cuff translation I made, not one that I have seen anywhere. If it’s still useful to have it properly in there, I will uncomment, just want to make very explicit that it’s just a loose translation and not a wording that is found on any products that I am aware of. :)

OK. Maybe we can keep a comment to indicate that, but still have the en: translation.

**Pull request merged**
