### PR TITLE
Fix decomposition of ingredients, add ?regexp=pattern parameter

### PR DESCRIPTION
**Pull request by stephanegigandet**

### CODE REVIEW

**Comment by stephanegigandet** [comment]
I fixed the bug reported by @aleene (#2119), and I needed to easily filter the ingredients lists, so I added a regexp parameter that works like this:

https://fr.dev.openfoodfacts.org/ingredients?regexp=arome

**Comment by hangy** [comment]
Could the regexp parameter be subject to code injection? http://www.pal-blog.de/entwicklung/perl/sql-injection-2-0-regular-expression-injection.html

**Comment by stephanegigandet** [comment]
I tried it and I get an error: "Eval-group not allowed at runtime, use re 'eval' in regex", it seems we would need to put "use re 'eval';" in the code for that to work.

But it's needlessly dangerous, I'll escape the regexp.

**Comment by stephanegigandet** [comment]
@hangy : it's now fixed.

**Pull request merged**
