### PR TITLE
Support /.well-known/change-password URL

### LINKED ISSUE #4140: Support for /.well-known/change-password
New versions of web browsers have password managers that let you change your password easily if it has been compromised in a breach (and that you have reused it many times on many websites).

To make it easy for user to change password, a new .well-known path has been proposed
https://web.dev/change-password-url/

/.well-known/change-password

### PR DESCRIPTION
**Pull request by hangy**
**Description:** Adds a new redirect, login form, and change password form to support the `/.well-known/change-password`.

**Related issues and discussion:** Closes #4140

### CODE REVIEW

**Review by stephanegigandet — CHANGES_REQUESTED** [review]
The /.well-known directory is used for other things (in particular to store the acme-challenges created by letsencrypt to renew SSL certificates), so I think it's best to keep it served by nginx instead of passing it to Apache. We can just add an nginx rewrite rule to redirect /.well-known/change-password to /cgi/change_password.pl

**Comment by hangy** [comment]
> The /.well-known directory is used for other things (in particular to store the acme-challenges created by letsencrypt to renew SSL certificates)

Is it still used for that? AFAIK, Let's Encrypt doesn't create wildcard certs with the HTTP challenge.

> so I think it's best to keep it served by nginx instead of passing it to Apache. We can just add an nginx rewrite rule to redirect /.well-known/change-password to /cgi/change_password.pl

I can do that, but do we need to? A lot of the URIs listed at http://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml seem to be related to application specific data. (For example OIDC, which I'd still prefer to the current API access.)

**Comment by stephanegigandet** [comment]
> Is it still used for that? AFAIK, Let's Encrypt doesn't create wildcard certs with the HTTP challenge.

For OFF, we use DNS validation with acme.sh, but for madenearme etc. we still use letsencrypt HTTP validation, so we should not change the nginx config for those.

**Comment by hangy** [comment]
> > Is it still used for that? AFAIK, Let's Encrypt doesn't create wildcard certs with the HTTP challenge.
> 
> For OFF, we use DNS validation with acme.sh, but for madenearme etc. we still use letsencrypt HTTP validation, so we should not change the nginx config for those.

Fixed 🙂

**Review by stephanegigandet — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
