### PR TITLE
Global safety taxonomy for OBF

### PR DESCRIPTION
**Pull request by teolemon**
Global safety taxonomy for OBF

### CODE REVIEW

**Comment by stephanegigandet** [comment]
Can you add the URL of the source as a comment? It would be useful if we want to reextract it later.

**Comment by teolemon** [comment]
I remember taking them from the EU translation memory. I need to find the source.

**Comment by teolemon** [comment]
Source: https://eur-lex.europa.eu/legal-content/FR/TXT/?qid=1598442551582&uri=CELEX:31993L0021

**Comment by teolemon** [comment]
@stephanegigandet updated with EU directive source.

**Review by stephanegigandet — APPROVED** [review]

**Pull request merged**
