### PR TITLE
Salty canistrelli

### PR DESCRIPTION
**Pull request by moon-rabbitOFF**

### CODE REVIEW

**Comment by svensven** [comment]
I think the test doesn't like that "Crème glacée à base de plante" is now a synonym of two different things. Perhaps it should be a synonym of "Crèmes glacées végétales" instead?

**Comment by moon-rabbitOFF** [comment]
I tried to correct this synonymy. All the other changes correspond to what have been added to the taxonmy since I did this pull request.

**Comment by svensven** [comment]
> I tried to correct this synonymy. All the other changes correspond to what have been added to the taxonmy since I did this pull request.

You don't need to apply the other changes that have happened since from other pull requests, the merge process will usually combine them automatically, unless two PRs have edited the same lines. Want me to try resolving the conflict?

**Comment by moon-rabbitOFF** [comment]
> > I tried to correct this synonymy. All the other changes correspond to what have been added to the taxonmy since I did this pull request.
> 
> You don't need to apply the other changes that have happened since from other pull requests, the merge process will usually combine them automatically, unless two PRs have edited the same lines. Want me to try resolving the conflict?

Yes, if you can, thank you! I have troubles with Git Hub

**Comment by svensven** [comment]
> Yes, if you can, thank you! I have troubles with Git Hub
Does it look okay now?

**Comment by moon-rabbitOFF** [comment]
> > Yes, if you can, thank you! I have troubles with Git Hub
> 
> Does it look okay now?

Yes, perfect! Thank you

**Review by stephanegigandet — APPROVED** [review]
Thanks you!

**Pull request merged**
