### PR TITLE
docs: Use `compose` command from Docker CLI

### PR DESCRIPTION
**Pull request by hangy**
Use [Compose V2](https://docs.docker.com/compose/cli-command/) commands.

### CODE REVIEW

**Comment by hangy** [comment]
This works well in Docker Desktop for Windows 3.5.1. Can anyone verify other platforms? 🙂

**Comment by VaiTon** [comment]
On Ubuntu 20.04 LTS still not supported. Could we add it as a suggestion instead of replacing the old command?

**Comment by hangy** [comment]
I think we can leave it as-is for the moment. Apparently, the new docker CLI command also works as a drop-in replacement for docker-compose.

**Review by ocervell — APPROVED** [review]
Looks good to me

**Comment by VaiTon** [comment]
> 
> 
> I think we can leave it as-is for the moment. Apparently, the new docker CLI command also works as a drop-in replacement for docker-compose.

@hangy do you want to close this? Put it as a WIP?

**Comment by ocervell** [comment]
@hangy We run Debian 10 on Proxmox VMs, but the `docker compose` command is not supported there either

**Comment by alexgarel** [comment]
@hangy hum sorry, this would have been cool if it was supported…

**Comment by hangy** [comment]
> @hangy hum sorry, this would have been cool if it was supported…

Yup, but this PR was badly outdated given the recent changes to Docker infrastructure and build scripts.

**Pull request closed without merging**
