### PR TITLE
feat: ingredient analysis translations

### PR DESCRIPTION
**Pull request by teolemon**
### What
feat: ingredient analysis translations

### CODE REVIEW

**Comment by alexgarel** [comment]
@teolemon is this a draft or a PR ?

**Comment by teolemon** [comment]
I'm not fluent in all those languages. Other than that, PR

**Comment by alexgarel** [comment]
I will fix tests.

**Comment by alexgarel** [comment]
@teolemon there are problems with this PR:

```
ERROR - ar:نباتي already is associated to en:vegan - ar:نباتي cannot be mapped to entry en:vegetarian
ERROR - el:χορτοφάγος already is associated to en:vegan - el:χορτοφάγος cannot be mapped to entry en:vegetarian
ERROR - th:มังสวิรัติ already is associated to en:vegan - th:มังสวิรัติ cannot be mapped to entry en:vegetarian
ERROR - zh:素食主义者 already is associated to en:vegan - zh:素食主义者 cannot be mapped to entry en:vegetarian
ERROR - ar:ربما-نباتي already is associated to en:maybe-vegan - ar:ربما-نباتي cannot be mapped to entry en:maybe-vegetarian
ERROR - th:อาจจะเป็นมังสวิรัติ already is associated to en:maybe-vegan - th:อาจจะเป็นมังสวิรัติ cannot be mapped to entry en:maybe-vegetarian
ERROR - zh:也许是素食主义者 already is associated to en:maybe-vegan - zh:也许是素食主义者 cannot be mapped to entry en:maybe-vegetarian
ERROR - th:มังสวิรัติ already is associated to en:vegan - th:มังสวิรัติ cannot be mapped to entry en:non-vegetarian
Errors in the ingredients_analysis taxonomy definition at /opt/product-opener/lib/ProductOpener/Tags.pm line 1145.
```

**Comment by benbenben2** [comment]
Errors due to duplicates have been fixe @teolemon @alexgarel

**Review by alexgarel — APPROVED** [review]
Thanks @benbenben2 :clap:

**Pull request merged**
