### PR TITLE
Ingredients patch 23

### PR DESCRIPTION
**Pull request by aleene**

### CODE REVIEW

**Comment by stephanegigandet** [comment]
If the build fails because of differences in the ingredients taxonomy, can you use a new branch for further changes, so that it's easier to understand why the build fails?

**Comment by aleene** [comment]
Can do, but that will create a lot of branches.

**Comment by aleene** [comment]
There are now only two fails related to the additives.

**Comment by aleene** [comment]
But I will checks the fails more often.

**Comment by stephanegigandet** [comment]
Some parents don't exist:

ERROR - parent  is not defined in lc  for tag bg:медни-комплекси-на-хлорофили
ERROR - parent  is not defined in lc  for tag en:blend-of-eu-and-non-eu-honeys
ERROR - parent  is not defined in lc  for tag en:carnauba-wax-coating-agents
ERROR - parent  is not defined in lc  for tag en:cocoa-bean
ERROR - parent  is not defined in lc  for tag en:emulsifier-mono-and-diglycerides-of-fatty-acids
ERROR - parent  is not defined in lc  for tag en:lemon-balm
ERROR - parent  is not defined in lc  for tag en:macruronus-novaezelandiae
ERROR - parent  is not defined in lc  for tag en:mate
ERROR - parent  is not defined in lc  for tag en:meadowsweet
ERROR - parent  is not defined in lc  for tag en:nettle
ERROR - parent  is not defined in lc  for tag en:oncorhynchus-gorbuscha
ERROR - parent  is not defined in lc  for tag en:organic-long-grain-white-rice
ERROR - parent  is not defined in lc  for tag en:panulirus-argus
ERROR - parent  is not defined in lc  for tag en:plantain
ERROR - parent  is not defined in lc  for tag en:spondyliosoma-cantharus
ERROR - parent  is not defined in lc  for tag fr:colorant-e133
ERROR - parent  is not defined in lc  for tag fr:oeufs-frais-dates-du-jour-de-ponte-de-poules-elevees-en-cage
ERROR - parent  is not defined in lc  for tag fr:pate-de-cacao-issus-de-l-agriculture-biologique-et-beurre-de-cacao-issus-de-l-agriculture-biologique
ERROR - parent  is not defined in lc  for tag fr:pin-sylvestre
ERROR - parent  is not defined in lc  for tag fr:pur-jus-de-pommes-a-cidre-bio
ERROR - parent  is not defined in lc  for tag fr:riz-long-biologique
ERROR - parent  is not defined in lc  for tag fr:riz-noir
ERROR - parent  is not defined in lc  for tag fr:viande-de-volaille-traitee-en-salaison
ERROR - parent  is not defined in lc  for tag la:craterellus-cornucopioides
ERROR - parent  is not defined in lc  for tag en:chicken-meat
ERROR - parent  is not defined in lc  for tag en:white-chocolate
ERROR - parent  is not defined in lc  for tag de:alkohol-und-weisweinessig
ERROR - parent  is not defined in lc  for tag fr:thai-riz-noir
ERROR - parent  is not defined in lc  for tag en:turkey-meat

**Comment by aleene** [comment]
Is it possible to get an overview of the errors earlier? I can repair some. Other are just missing english parents, which is not always repairable.

**Comment by stephanegigandet** [comment]
For the tests not passing? If you click on the red crosses, you can get the logs of the test (which are very long). Search for "fail" and you will see why the tests are not passing. Usually it's because the test expects some result, and the taxonomy changes have changed the results.

Do you have an example of missing English parents that are not repairable?

**Comment by aleene** [comment]
I tried that, but it seems it stopped after the first two fails.

With unrepairable, I mean that I have no idea what the english should be.

**Comment by stephanegigandet** [comment]
The error messages are not very clear. It's not that the English is missing, it's that an entry specifies a parent that does not exist.

e.g.

ERROR - parent is not defined in lc for tag en:chicken-meat

<en:poultry meat
<en:chickens
en:chicken meat

-> there's no en:Poultry meat entry defined.

**Comment by aleene** [comment]
Ok, I check those kind of errors as well.

**Comment by aleene** [comment]
I get these after a test build: https://travis-ci.org/openfoodfacts/openfoodfacts-server/builds/545730712?utm_source=slack&utm_medium=notification

Does not help me much

**Pull request merged**
