### PR TITLE
disallow edits from apps to product data and images sent by manufacturers

### PR DESCRIPTION
**Pull request by stephanegigandet**
https://github.com/openfoodfacts/openfoodfacts-server/issues/1810

### CODE REVIEW

**Comment by VaiTon** [comment]
> It would be better to at least communicate the problem with the caller, so that they know that their data has _not_ been saved.

I strongly agree with that

**Comment by stephanegigandet** [comment]
The thing is that the current API does not have a feedback mechanism to indicate that some fields were saved and some were not. And we do not want apps to resubmit the data. Returning something else than the current status: ok response is likely to have unwanted behavior in some apps (like not being able to submit a product).

Let me provide some context: we have 12 000 products (and growing) with data like ingredients and nutrition facts that has been provided by producers (and that is almost always correct). And we have bogus data that overwrite this data. In particular there are some bugs in the offline mode of the OFF apps that make ingredients and nutritions facts being erased.

So while I agree that the silent ignore is not ideal, it's bad data that is being ignored. I think it's time that we define a new version of the API, and this time we should incorporate a better feedback mechanism (like which fields were saved, or rejected and why).

**Comment by hangy** [comment]
> So while I agree that the silent ignore is not ideal, it's bad data that is being ignored.

Oh, that's a bad situation ... and rejecting the whole edit might also be not too good for contributors ...

> I think it's time that we define a new version of the API, and this time we should incorporate a better feedback mechanism (like which fields were saved, or rejected and why).

Feel free to jump in on #1687 😉

**Comment by hangy** [comment]
> > So while I agree that the silent ignore is not ideal, it's bad data that is being ignored.
> 
> Oh, that's a bad situation ... and rejecting the whole edit might also be not too good for contributors ...

I just stumbled upon this again while skimming the source, and was confused why it was done this way, again. 😆 To be honest, it's *potentially* bad data being ignored. The apps that write data using the API might very well be providing corrections/improvements to the data provided by a producer. Silently discarding parts of the edits might drive well-behaved, motivated contributors away.

**Pull request merged**
