### PR TITLE
Update contribuer.html

### PR DESCRIPTION
**Pull request by teolemon**

### CODE REVIEW

**Comment by VaiTon** [comment]
Woudn't it be better if we update the eng version? Crowdin would do the rest.

**Comment by teolemon** [comment]
We have legacy files for French. Eventually, I want to kill them alltogether.

**Comment by teolemon** [comment]
lang/fr/texts/contribuer.html (legacy)
lang/fr/texts/contribute.html (standardized)

**Comment by VaiTon** [comment]
Merging this. Let's try to make eng default.

**Pull request merged**
