### PR TITLE
feat: packaging add Denmark

### PR DESCRIPTION
**Pull request by benbenben2**
### What
packaging codes add Denmark

### Screenshot
Screenshot_20240603_192405

### Related issue(s) and discussion
Part of https://github.com/openfoodfacts/openfoodfacts-server/issues/338

More details based on previous work (#8921, #8958, #10264, #10318, #10351):
- lib/ProductOpener/Display.pm
add description (name, street, city) based on columns in the file or hardcoded
- lib/ProductOpener/PackagerCodes.pm
add country and suffix of the code
- scripts/update_packager_codes.pl
add code formatting ('country' 'code' 'suffix', for example if code does not already contain 'country' or 'suffix')
add the column name for the $code variable
- packager-codes/
add the csv file (mind the naming)
- scripts/packager-codes/
add your script (remove api keys if any)
- update sto files
```
docker exec -it po_off-backend-1 bash
./scripts/update_packager_codes.pl
```

### CODE REVIEW

**Comment by benbenben2** [comment]
Get this warning...

> remote: warning: See https://gh.io/lfs for more information.
> remote: warning: File packager-codes/packager_codes.sto is 73.63 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
> remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.

**Review by stephanegigandet — APPROVED** [review]
Thank you!

**Review by teolemon — APPROVED** [review]
🎉

**Comment by alexgarel** [comment]
Thank you for those incredible contributions @benbenben2 !

**Pull request merged**
