### PR TITLE
fix: ciqual_food_code and ciqual_proxy_food_code on ingredients analysis panel

### LINKED ISSUE #9534: For moderators, Show the presence of a CIQUAL/Agribalyse match in the panel for ingredient analysis
### Problem
- Make it easy to spot holes in Agribalyse/CIQUAL coverage, and easier to look for proxies, without overwhelming all users

### Proposed solution
- For moderators, Show the presence of a CIQUAL/Agribalyse match in the panel for ingredient analysis

### Part of
- #6499

### PR DESCRIPTION
**Pull request by himanshisrestha**
### What
This will issue https://github.com/openfoodfacts/openfoodfacts-server/issues/9534 , in which we should show which ingredients have a ciqual_food_code or a ciqual_proxy_food_code.
The file Display.pm in lib/ProductOpener had the function named "display_ingredients_analysis_details" which was calling for a function named "display_nested_list_of_ingredients". In the function, it searches for the properties for the ingredient in which the required fields (ciqual_food_code or a ciqual_proxy_food_code) if present was added to the string formed to get the desired output. As suggested earlier, the order of the search property was changed a little bit.

### Screenshot

Screenshot 2024-03-20 at 11 21 42 AM

### Related issue(s) and discussion

- Fixes #9534

### CODE REVIEW

**Review by stephanegigandet — APPROVED** [review]
Looks good, thank you!

**Comment by himanshisrestha** [comment]
> Looks good, thank you!

Looking forward to contribute in bulk @ OFF

**Comment by stephanegigandet** [comment]
@himanshisrestha Could you run "make update_tests_results" and commit the changes? A few expected results are changed because they now have the ciqual code.

**Comment by himanshisrestha** [comment]
> @himanshisrestha Could you run "make update_tests_results" and commit the changes? A few expected results are changed because they now have the ciqual code.

Sure @stephanegigandet . Updating you in a while

**Comment by himanshisrestha** [comment]
Screenshot 2024-03-22 at 8 45 23 PM
@stephanegigandet its still stuck at Error 22. :-(

**Comment by stephanegigandet** [comment]
@himanshisrestha I ran "make update_tests_results" and it worked for me, so I commited the changes to your branch.

**Comment by himanshisrestha** [comment]
@stephanegigandet Thank you for reviewing this. So is there anything that I should do next for this PR

**Pull request merged**
