### PR TITLE
taxonomy: Lithuanian category taxonomies

### PR DESCRIPTION
**Pull request by DanieliusAsm**
### What

- Added a bunch of Lithuanian category taxonomies
- Fix: under Latvian Vodka there were translations de, nl, fr that said Lithuanian vodka
- Added new category [Traditional Lithuanian-Polish cakes](https://world.openfoodfacts.org/category/lt:%C5%A1ako%C4%8Diai) ([Q6882841](https://www.wikidata.org/wiki/Q6882841))

### CODE REVIEW

**Comment by DanieliusAsm** [comment]
New to git. Why did already approved commits were included ?

**Comment by aleene** [comment]
Not sure how it works. After an approval I start a new branch, which seems to help.

**Comment by alexgarel** [comment]
Hi @DanieliusAsm thanks for working on this. Maybe it's better to do small changes and get them merged than having a long living branch (prone to conflicts). So do not hesitate to just push part of your work for approval and then continue.

**Comment by DanieliusAsm** [comment]
@alexgarel Thanks for letting me know this. Who do I mention to review ?

**Comment by DanieliusAsm** [comment]
@aleene Requesting for review

**Review by alexgarel — APPROVED** [review]

**Pull request merged**
