### PR TITLE
fix: Correct handling of fractions without leading zero in Salt/Sodium content field Fixes #6717

### LINKED ISSUE #6717: Editing Salt/Sodium content field does not work correctly with fractions without leading zero
### Describe the bug

On the product edit page, setting fractional salt or sodium value without leading zero produces incorrect calculated value for the corresponding field.

### To Reproduce

1. Open a product edit page
2. Set Salt content to `.53` and move to the next field
3. Sodium content is calculated as `.21.200000000000003`

### Expected behavior

Calculation to work without setting leading zero to the fraction.

### Screenshots

Screenshot_2022-04-29_10-07-34

### Additional context

```js
	function swapSalt(from, to, multiplier) {
		var source = from.val().replace(",", ".");
		var regex = /^(.*?)([\d]+(?:\.[\d]+)?)(.*?)$/g;
		var match = regex.exec(source);
		if (match) {
			var target = match[1] + (parseFloat(match[2]) * multiplier) + match[3];
			to.val(target);
		} else {
			to.val(from.val());
		}
	}
```
The swap salt function concatenates `match[1]` in front of the result which leads to having the decimal point twice.

### Type of device

Browser

### Browser version

Version 100.0.4896.127 (Official Build) (64-bit)

### Number of products impacted

_No response_

### Time per product

_No response_

### PR DESCRIPTION
**Pull request by danwyk**
### What   

 Correct handling of fractions without leading zero in Salt/Sodium content field Fixes   

### Screenshot   
image   

### Related issue(s) and discussion   
- Fixes #6717

### CODE REVIEW

**Review by stephanegigandet — APPROVED** [review]
Looks good, thank you!

**Review by stephanegigandet — APPROVED** [review]
Looks good, thank you!

**Comment by danwyk** [comment]
> Looks good, thank you!

Thanks for getting me through the required test. I accidentally clicked "Update branch" when I saw my PR is behind the latest branch. And therefore it requires permission to run the required test again. Sorry about any inconvenience. Could you please grant me a permission again? Much obliged!

**Comment by stephanegigandet** [comment]
@danwyk Sure. I also sent you an invite to join the team of the openfoodfacts-server repo so that it does not require approval to run tests.

**Comment by danwyk** [comment]
> @danwyk Sure. I also sent you an invite to join the team of the openfoodfacts-server repo so that it does not require approval to run tests.

Really appreciate it! I've joined it. Thanks for inviting me.

**Pull request merged**
