### PR TITLE
Support TSV for packager codes

### PR DESCRIPTION
**Pull request by hangy**
**Description:**

Instead of using both separators (`;` and `\t`) when loading packager codes, only use the one that matches the file extension.

**Related issues and discussion:** #1671

### CODE REVIEW

**Comment by stephanegigandet** [comment]
Perfect, thank you!

**Comment by teolemon** [comment]
@stephanegigandet We need to run this script

**Comment by stephanegigandet** [comment]
I just ran it and restarted the server.

**Comment by stephanegigandet** [comment]
Everything looks good. :) Thanks @hangy !

**Pull request merged**
