### PR TITLE
add robots.txt

### PR DESCRIPTION
**Pull request by stephanegigandet**
I included the major SEO robots. We had one on OFF, but we were missing it on OBF etc.

### CODE REVIEW

**Comment by hangy** [comment]
What about https://github.com/openfoodfacts/openfoodfacts-server/blob/829b38da7e87dc1b5830c23537f1c9e5b59203b7/html/files/robots.txt?

**Comment by VaiTon** [comment]
Why are we disallowing them? noob question

**Comment by stephanegigandet** [comment]
> What about https://github.com/openfoodfacts/openfoodfacts-server/blob/829b38da7e87dc1b5830c23537f1c9e5b59203b7/html/files/robots.txt?

I was under the impression we had one somewhere, but I didn't find it. I'll include yours in the one in /html/ as that's what's get served by nginx.

**Comment by stephanegigandet** [comment]
> Why are we disallowing them? noob question

Most of those are robots for SEO, for sites that allow webmasters to see who links to them. They have absolutely no value to us, but very often they request tens of thousands of pages and overload our server.

**Pull request merged**
