### PR TITLE
Sticky edit comment

### LINKED ISSUE #609: Keep the edit and save button always visible in the edit page (responsive mode)
Keep the edit and the save buttons always visible in the product and edit pages. 
Currently you have to scroll down to the bottom of the page to save.

image

This is really important for the new mobile app that lets you edit products.

### PR DESCRIPTION
**Pull request by hangy**
Code by @CloCkWeRX https://github.com/openfoodfacts/openfoodfacts-server/issues/1028#issuecomment-355023253

Closes #609

### CODE REVIEW

**Comment by stephanegigandet** [comment]
It looks good on mobile, but on desktop it's a bit odd, it may be just a habit issue, I'm not used to fixed stuff on desktop.

image

Otherwise code looks good.

**Comment by hangy** [comment]
Maybe browser dependent? For me, it looked exactly like @CloCkWeRX screenshot on desktop (https://github.com/openfoodfacts/openfoodfacts-server/issues/1028#issuecomment-355023253). Let's do some cross-browser tests first. :)

**Comment by stephanegigandet** [comment]
I didn't run the exact code in the fix so that's why the Save button looks a bit different. What's troubling me (a bit, I can get used to it) is the fact that if you scroll all the way down, the save button goes in the page footer. But don't worry about it.

**Comment by hangy** [comment]
Closing old non-reviewed PRs.

**Pull request merged**
