### PR TITLE
A good product for you - example product for apps

### PR DESCRIPTION
**Pull request by stephanegigandet**
Passing "example" as the code parameter to the API will return this fake product:
https://world.openfoodfacts.org/product/093270067481501/a-good-product-for-you-open-food-facts

### CODE REVIEW

**Comment by teolemon** [comment]
- will close https://github.com/openfoodfacts/smooth-app/issues/1003

**Review by monsieurtanuki — APPROVED** [review]
@stephanegigandet LGTM!

**Comment by alexgarel** [comment]
A pity there is no photo https://world.openfoodfacts.org/product/093270067481501/a-good-product-for-you-open-food-facts

**Comment by stephanegigandet** [comment]
> A pity there is no image https://world.openfoodfacts.org/product/093270067481501/a-good-product-for-you-open-food-facts

We don't need one for Smoothie, but I'll add one. :)

**Pull request merged**
