### PR TITLE
chore: Intake revisited

### PR DESCRIPTION
**Pull request by aleene**
### What
The new intake descriptions are revisited

### CODE REVIEW

**Review by stephanegigandet — APPROVED** [review]
Thanks!

Those are still the Intake UK categories right? For modified FR categories, we should use a new property intake24_fr_category_code, so that we still have matching for Intake UK.

**Comment by aleene** [comment]
Will do that

**Comment by aleene** [comment]
@stephanegigandet can you look at the failing test? It does not say what failed.

**Comment by stephanegigandet** [comment]
> @stephanegigandet can you look at the failing test? It does not say what failed.

@aleene I fixed the tests, it was just a comma missing that prevented the expected JSON to be parsed

**Comment by stephanegigandet** [comment]
@aleene tests fixed, can we merge?

**Pull request merged**
