### PR TITLE
Categories translations

### PR DESCRIPTION
**Pull request by aleene**
Merged translations from the ingredients and categories taxonomy.

### CODE REVIEW

**Comment by stephanegigandet** [comment]
The categories are in plural though, whereas the ingredients are in singular. I don't know if there's a way to get the plurals from wikidata?

**Comment by aleene** [comment]
No, singular-plural difference is not in the wikidata. 
In dutch plurals for categories does not work, should be mostly in singular.
I wonder if the users think of categories in plural or singular.

**Comment by aleene** [comment]
I put the plurals in front in the categories and viceversa in the ingredients. So should be okay.

**Comment by aleene** [comment]
If there are plurals available, I put them first in category taxonomy. But the wikidata does not always have those. Are you ok with this approach?

**Comment by stephanegigandet** [comment]
OK, sounds good.

**Pull request merged**
