### PR TITLE
fix: exclude nutrition id containing nutrition-score

### PR DESCRIPTION
**Pull request by benbenben2**
excluding all nutriments containing "nutrition-score" (nutrition-score, nutrition-score-fr)

Tested that negative value is still working for common nutriment. **But** it is not possible to test negative nutrition-score itself because there are no examples in the test data and I do not know how to create such negative nutrition-score.

could fix #7988

### CODE REVIEW

**Review by alexgarel — APPROVED** [review]
:clap: thank you so much @benbenben2 !

**Comment by stephanegigandet** [comment]
Thank you @benbenben2 !

**Comment by CharlesNepote** [comment]
Thanks @benbenben2 !

**Comment by CharlesNepote** [comment]
@stephanegigandet is it possible to deploy it today as the number of this data quality error is increasing quickly:
* [1486 two days ago](https://mirabelle.openfoodfacts.org/previous?sql=select+count%28code%29%0D%0Afrom+%5Ball%5D%0D%0Awhere+data_quality_errors_tags+like+%22%25negative%25%22%0D%0Aorder+by+rowid+limit+21) (2023-01-28)
* [1910 yesterday](https://mirabelle.openfoodfacts.org/products?sql=select+count%28code%29%0D%0Afrom+%5Ball%5D%0D%0Awhere+data_quality_errors_tags+like+%22%25negative%25%22%0D%0Aorder+by+rowid+limit+21) (2023-01-29).

As a result, data quality errors percentage is increasing while it was continuously decreasing since 2 months :(

**Pull request merged**
