### PR TITLE
taxonomy: vegetable protein added to the ingredients list

### LINKED ISSUE #7266: Tapioca Starch isn't recognized as an ingredient
This could be fixed by adding Tapioca Starch as a synonym to Tapioca Flour in the taxonomies.

### PR DESCRIPTION
**Pull request by aakankshabhende**
### What
Added vegetable protein to the ingredients list

### Related issue(s) and discussion
- Fixes #7266

### CODE REVIEW

**Comment by yuktea** [comment]
@aakankshabhende: Thank you so much for this PR. Could you please "uncommit" the gitpod file? I think it got there erroneously

**Comment by aakankshabhende** [comment]
Done @yuktea

**Comment by alexgarel** [comment]
@aakankshabhende thanks so much for contributing :-) (taxonomies are essential)

@aleene can you check this PR ?

**Comment by aleene** [comment]
I think it still needs a small change. Need to check whether it fits somewhere in the tree.

**Review by aleene — CHANGES_REQUESTED** [review]
This entry is already a synonym of en:plant protein.

The pull request can be deleted.

**Comment by VaiTon** [comment]
@aleene you're right, but the issue persists: https://us.openfoodfacts.org/ingredients?status=unknown

**Pull request closed without merging**
