### PR TITLE
chore: Week 9 additions

### PR DESCRIPTION
**Pull request by aleene**
### What
Some requested additions and some apple juice work

### CODE REVIEW

**Comment by aleene** [comment]
@stephanegigandet I was able to remove a lot of test errors, but I do not see where this one originates.

**Comment by stephanegigandet** [comment]
@aleene I'm looking into the failing tests

**Comment by stephanegigandet** [comment]
@aleene "Orange marmelade" is marked "vegan" because it is a child of "Orange".

<en:orange
en:orange marmalade

I think we should remove the parent (same for other kinds of marmalade).  "Orange marmelade" is not a type of "Orange".

**Review by stephanegigandet — APPROVED** [review]
Looks good

**Pull request merged**
