### PR TITLE
Fix adding tags in MS Edge

### LINKED ISSUE #3251: Adding tags in product edit form is impossible on Microsoft Edge browser
Typing to add a tag does nothing.

image

### PR DESCRIPTION
**Pull request by GendelfLugansk**
This fixes #3251 by adding polyfill for `window.customElements`

### CODE REVIEW

**Comment by stephanegigandet** [comment]
Hi @GendelfLugansk ,
I tried to deploy it on https://world.openfoodfacts.org but I couldn't get it to work on Edge, I still have the same symptoms. Maybe I'm doing something incorrectly.
I also tried loading /js/dist/custom-elements.min.js in the product_multilingual.pl file, but no change either.
Any idea?

**Comment by GendelfLugansk** [comment]
@stephanegigandet I'll re-check

**Comment by GendelfLugansk** [comment]
@stephanegigandet I decided to replace polyfill with another one (should work better accross different versions) and added it to `product_multilingual.pl`. Please check if it works for you

**Comment by stephanegigandet** [comment]
Thanks @GendelfLugansk . I deployed it on https://world.openfoodfacts.org but I still have the same issue: I can't add tags with Edge (Windows 10 - Microsoft Edge 44.18362.449.0). Does it work for you on the production site?

In Edge, I get 404 for 2 js files (no idea what is trying to load them):

image

I did add the webcomponent script on the product display page (not the edit form), and that removes the IE error on the product display page:

in lib/ProductOpener/Display.pm :

````
sub display_product($)
{
	my $request_ref = shift;

	my $request_code = $request_ref->{code};
	my $code = normalize_code($request_code);
	local $log->context->{code} = $code;

	my $product_id = product_id_for_owner($Owner_id, $code);

	my $html = '';
	my $blocks_ref = [];
	my $title = undef;
	my $description = "";

		$scripts .= <<SCRIPTS
<script src="/js/dist/webcomponentsjs/webcomponents-loader.js"></script>
<script src="$static_subdomain/js/dist/display-product.js"></script>
SCRIPTS
;

**Comment by GendelfLugansk** [comment]
@stephanegigandet I can't add tags on production, too but can when I use my fork

**Comment by GendelfLugansk** [comment]
@stephanegigandet I also see that 404 errors in Edge but not in Chromium

**Comment by GendelfLugansk** [comment]
@stephanegigandet when you deploy, do you run `npm install` and `gulp` commands? Because I can not reproduce tags problem locally, only on world.openfoodfacts.org.

If possible, try to run following command: `rm -rf html/js/dist/ html/css/dist/ node_modules/ && npm install && gulp`

**Comment by stephanegigandet** [comment]
I run "npm install" and "npm run build" (which runs gulp).

I'm going to merge this PR so that I can test things more easily.

**Comment by stephanegigandet** [comment]
@GendelfLugansk after removing node_modules and the dist dir and re-running npm install and npm run build, it works. I probably made a mistake somewhere earlier.

Thanks a lot for your help, that bug was blocking some contributors who use Edge on their employer issued laptops.

**Pull request merged**
