### PR TITLE
More processes and translations

### PR DESCRIPTION
**Pull request by aleene**

### CODE REVIEW

**Comment by aleene** [comment]
I can remove `natural`, but does it any harm?. Maybe the processes taxonomy should be extended to `organic` and `fair trade` as well? And we'll call it `ingredient adjectives`.

**Comment by stephanegigandet** [comment]
@aleene : it looks like this branch has no actual changes anymore (as I guess all the changes were merged through another branch)

**Comment by aleene** [comment]
I understand now. You accepted already a newer version. So I'll delete this one.

**Comment by stephanegigandet** [comment]
For organic and fair trade, we handle them already, with the labels taxonomy, which is also used for ingredients parsing. I want to keep labels and processings separate.

**Comment by aleene** [comment]
> For organic and fair trade, we handle them already, with the labels taxonomy, which is also used for ingredients parsing. I want to keep labels and processings separate.

Sounds as you mix labels and ingredients.

**Pull request closed without merging**
