### PR TITLE
Update bug issue template.

### PR DESCRIPTION
**Pull request by hangy**
The "bug" label has been renamed to "🐞 bug".

### CODE REVIEW

**Comment by stephanegigandet** [comment]
I'm not a fan of icons in issue labels, is that a change made by github, or by us? cc @teolemon

**Comment by hangy** [comment]
> I'm not a fan of icons in issue labels, is that a change made by github, or by us? cc @teolemon

Wasn't me 🤷‍♂

**Comment by teolemon** [comment]
GitHub. Not sure if they have an opt-out

**Comment by VaiTon** [comment]
@hangy why don't we just rename the label again?

**Comment by hangy** [comment]
> @hangy why don't we just rename the label again?

I assumed that someone with admin permissions changed it intentionally. Since it has been re-renamed to "bug" now, I'll just close this PR. :)

**Pull request closed without merging**
