### PR TITLE
build: name github workflow jobs

### PR DESCRIPTION
**Pull request by VaiTon**

### CODE REVIEW

**Review by teolemon — APPROVED** [review]

**Review by hangy — APPROVED** [review]

**Comment by VaiTon** [comment]
@teolemon I am not able to merge

**Comment by teolemon** [comment]
gulp lint and test  are: "Expected — Waiting for status to be reported
Required" 
Do a blank edit

**Comment by VaiTon** [comment]
@stephanegigandet @teolemon I don't know what to do.

**Comment by stephanegigandet** [comment]
@VaiTon It's because GitHub's branch protection specifies the tests that must pass with their name, so changing the names of the tests makes those rules fail. I'll update the rules.

**Pull request merged**
