### PR TITLE
fix: gzip all JSON OCRs when saving OCR file on disk

### PR DESCRIPTION
**Pull request by raphael0202**
To save space, all OCR files were gzipped, but new generated files are still saved as plain text JSON files.
Also add a `created_at` field in the OCR JSON file containing the timestamp of generation of the OCR file. This is useful to know if we should generate again old OCR files.

### CODE REVIEW

**Comment by raphael0202** [comment]
@alexgarel I haven't set up Product Opener locally, will give it a try ;)

**Comment by raphael0202** [comment]
@alexgarel it should be good now!

**Comment by raphael0202** [comment]
I checked locally, the generated gzipped JSON file saved correctly.

**Review by alexgarel — APPROVED** [review]
Great @raphael0202 !

**Pull request merged**
