### PR TITLE
Update ingredients_analysis.txt

### PR DESCRIPTION
**Pull request by teolemon**
I am not sure how it is formatted into something the app can still understand

### CODE REVIEW

**Comment by stephanegigandet** [comment]
Yes, that doesn't work indeed, it would change things on the web site as well. :(

**Comment by stephanegigandet** [comment]
Here we do want to keep our current message: https://fr.openfoodfacts.org/ingredients-analysis

**Comment by stephanegigandet** [comment]
Leave the current message I guess. We'll see if app users understand it correctly.

**Comment by teolemon** [comment]
I'm closing this draft.

**Pull request closed without merging**
