### PR TITLE
docs: Add new light/dark mode logo for README

### PR DESCRIPTION
**Pull request by teolemon**
### What
doc: Add new light/dark mode logo for README

### CODE REVIEW

**Comment by stephanegigandet** [comment]
I tried that, but it fails on Firefox:

image

**Comment by stephanegigandet** [comment]
@teolemon see the discussion in https://github.com/openfoodfacts/smooth-app/pull/2288

The Smoothie repo currently has a black logo on Firefox.

**Comment by teolemon** [comment]
Let me change the code, I believe I might have a fix

**Comment by teolemon** [comment]
does the new code work ?

**Comment by stephanegigandet** [comment]
> does the new code work ?

Well it works in the sense that it shows the 2 logos on both Firefox and Chrome, so one of them is the right one :)

**Comment by teolemon** [comment]
A new PR was opened with the same branch by @stephanegigandet 
Closing this one

**Pull request closed without merging**
