### PR TITLE
Start of German translation

### PR DESCRIPTION
**Pull request by croesch**
## Description

Reading through your website I discovered several dead links and found out that the contents aren't translated, yet. So I started to translate some pages.

## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [x] Code is well documented
 - [x] Include unit tests for new functionality
 - [x] Code passes Travis builds in your branch
 - [ ] If you have multiple commits please combine them into one commit by squashing them.
 - [x] Read and understood the [contribution guidelines](https://github.com/openfoodfacts/openfoodfacts-server/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by croesch** [comment]
Do you prefer squashed commits? Or is the one commit per page OK?

Remaining pages will come in the next days, depending on my time. So this is only the start (hopefully) but still consistent in itself.

**Comment by teolemon** [comment]
You can do the translations directly in https://translate.openfoodfacts.org

**Comment by teolemon** [comment]
@croesch I moved all the translations to the standardized translation system I mentionned above. 

Ok to close this Pull Request ?

**Comment by croesch** [comment]
Sure .. but I'll have a look at your mentioned opportunity.

**Pull request closed without merging**
