### PR TITLE
ci: Tweak Perl Critic for annotations

### PR DESCRIPTION
**Pull request by teolemon**
### Checklist
ci: Tweak Perl Critic for annotations

### CODE REVIEW

**Comment by alexgarel** [comment]
I don't think we want that (@stephanegigandet ?)

We will have [37000 annotation](https://api.github.com/repos/openfoodfacts/openfoodfacts-server/check-runs/6117963778)… it will clutter the reviews (as codecov is cluttering robotoff reviews…)

Why would you want to go to "brutal ?" @teolemon

**Review by alexgarel — CHANGES_REQUESTED** [review]
see my comment

**Comment by stephanegigandet** [comment]
Where/when would those annotations be shown? They don't prevent the test from passing, so I don't really understand how they would be used?

**Comment by dipietroR** [comment]
I think that PR #7024 solves this issue

**Pull request closed without merging**
