### PR TITLE
add strings for ingredients analysis

### PR DESCRIPTION
**Pull request by stephanegigandet**
add missing strings in common.pot, already in en.po

### CODE REVIEW

**Comment by stephanegigandet** [comment]
@teolemon : what's the proper process for me to add French strings when I add new strings in common.po and en.po ?
Is there a way for me to somehow load this branch in crowdin, translate the strings to French or other languages, and then get back the updated fr.po in my branch?

**Comment by teolemon** [comment]
common.pot and then let Crowdin propagate

**Comment by stephanegigandet** [comment]
@teolemon : "let Crowdin propagate" --> when does that propagation happen? when common.pot is commited to any branch? to a specific branch? (master?)

**Comment by teolemon** [comment]
To master for actual file commit back to Product Opener, but I think translations are made available to translators when still a branch.

**Pull request merged**
