### PR TITLE
feat: Categories taxonomy improvements for Wikidata and IGPs

### PR DESCRIPTION
**Pull request by teolemon**
### What
- [ ] A lot of fixes to the Categories taxonomies (typos…)
  - [ ] A lot of Wikidata additions to allow us to show links to Wikipedia articles and other magic things 
  - [ ] Some improvements on the IGP front, with a normalization from countries to origins to empower the origin automatic addition (#3426 )

PS: I'm really sorry that the changes are too big for the web editor :-/

### Part of
- #5506

### CODE REVIEW

**Comment by teolemon** [comment]
Errors in the categories taxonomy definition:
ERROR - it:marrone-del-mugello has an undefined parent 
ERROR - it:marrone-della-valle-di-susa has an undefined parent 
ERROR - it:marrone-di-caprese-michelangelo has an undefined parent 
ERROR - it:marrone-di-castel-del-rio has an undefined parent 
ERROR - it:marrone-di-combai has an undefined parent 
ERROR - it:marrone-di-roccadaspide has an undefined parent 
ERROR - it:marrone-di-san-zeno has an undefined parent 
ERROR - it:marrone-di-serino has an undefined parent 
ERROR - it:peperone-di-pontecorvo has an undefined parent 
ERROR - it:peperone-di-senise has an undefined parent 
ERROR - it:clementine-di-calabria has an undefined parent 
ERROR - it:pera-dell-emilia-romagna has an undefined parent

**Comment by teolemon** [comment]
Errors in the categories taxonomy definition:
ERROR - it:peperone-di-pontecorvo has an undefined parent 
ERROR - it:peperone-di-senise has an undefined parent 
ERROR - it:clementine-di-calabria has an undefined parent 
ERROR - it:pera-dell-emilia-romagna has an undefined parent

**Comment by stephanegigandet** [comment]
<en:Colas
 en:Cola with sugar and artificial sweetener, Cola with sugar and artificial sweeteners
@@ -4632,6 +4964,7 @@ fr:Sodas au cola sans caféine
 it:Bibite alla cola senza caffeina, Cole senza caffeina
 nl:Caffeinevrije colas
 ro:Cola fără cafeină
+#wikidata:en:

The 2988 empty wikidata entries make the PR a pain to review. If you really want to add them, I suggest to first remove them, file a PR, get it merged, and then add back the empty entries, so that we don't have them in the middle of the other changes.

The same strategy could be used for things were one field is renamed in another. Otherwise it's very hard to see the manual changes (the ones that would be useful to review) from the rest.

**Comment by teolemon** [comment]
It's ironically the opposite as your comment in Slack. We'll have to use a case by case approach to see where we can safely do so
```
09:35
Stéphane Gigandet @Pierre (teolemon) for your PR, please split it in 2 PRs, one for categories, and the other for the rest, so that we can review and merge independently
regarding categories:
<en:Beers
 en:Beers from Germany, German beers
@@ -1556,26 +1585,29 @@ hu:Német sörök, Sörök németországból
 it:Birre tedesche, Birre della Germania
 nl:Duitse bieren
 ro:Beri germane, Beri Germania, Bere germană, Bere Germania, Bere germana
-country:en:Germany
+origins:en: en:Germany

the "origins" field is for the origin of ingredients. I'm not sure we can automatically assume a German beer is made from German ingredients.
```

**Comment by teolemon** [comment]
Thanks a lot for the review @stephanegigandet 🎉 
This PR is going to unlock a trove of knowledge for Open Food Facts

**Comment by alexgarel** [comment]
Kudos for this PR @teolemon

**Pull request merged**
