### PR TITLE
Display Recent Changes

### LINKED ISSUE #908: Implement a Recent Changes page
https://wikidata.org/wiki/Special:RecentChanges
image
image

Wikidata does a streaming live version of changes with Color Codes, a quick diff link to see what has changes, and the contributor responsible for it.

### PR DESCRIPTION
**Pull request by hangy**
Closes #908

### CODE REVIEW

**Comment by hangy** [comment]
@teolemon Do you want this to be linked somewhere?

**Comment by teolemon** [comment]
Not for the moment.

For the time being, I'd like to experiment it with a limited group of contributors, so that we can get feedback. 
Do you have a screenshot ?

**Comment by hangy** [comment]
Right now, it's pretty much just a functional copy of the change log on the bottom of the product edit page:
image

**Comment by hangy** [comment]
@stephanegigandet @teolemon Note for deployment: `scripts/update_recent_changes.pl` could be run once after this release is deployed to seed the MongoDB collection with the previous changes.sto entries.

**Comment by stephanegigandet** [comment]
Oops, it looks like I merged things accidentally in there. :-( Sorry about that.

How can I revert those?

stephanegigandet added some commits 11 days ago
 @stephanegigandet
add unselect image and wipe ingredients button for admins -- issue #983
ec18560
 @stephanegigandet
Merge pull request #987 from openfoodfacts/master  …
Verified
e1c8c6e
 @stephanegigandet
update config file with new needed variables
2b99456
 @stephanegigandet
Merge pull request #990 from openfoodfacts/issue/120-praise-translators  …
Verified
da4453a
 @stephanegigandet
small changes for the foundation override styles
a18d5f8
 @stephanegigandet
Merge pull request #991 from openfoodfacts/issue/391-wikidata-in-api  …
Verified
46daf71
 @stephanegigandet
Merge pull request #992 from openfoodfacts/issue/912-quality  …
Verified
6069abe
 @stephanegigandet
Merge branch 'kitchensink' into issue/390-map-wikidata
Verified
3f86fc7
 @stephanegigandet
Merge pull request #993 from openfoodfacts/issue/390-map-wikidata  …
Verified
71bff5c
 @stephanegigandet
Merge branch 'kitchensink' into issue/908-recent-changes
Verified
507f8bb

**Comment by hangy** [comment]
I think it should be possible to rewrite history. I'll try to reset this branch/pr to 662249caab544dad583dfe498af1fa663c5149d0 and see whether it could merge to master without errors. :)

**Comment by hangy** [comment]
Closing old non-reviewed PRs.

**Pull request merged**
