### PR TITLE
Icons and colors for the ingredient analysis

### PR DESCRIPTION
**Pull request by teolemon**
Icons and colore for the ingredient analysis

### CODE REVIEW

**Comment by aleene** [comment]
Seems silly. You should do this on the device, not the server.

**Comment by stephanegigandet** [comment]
@aleene : this is so that we can update it on the server, without needing to deploy new versions of the apps each time we had a new thing we recognize in ingredients. The icons and colors could be in a separate file I guess. Which would make it easier to populate and test new ingredients analysis without having them appear right away on devices.

**Comment by teolemon** [comment]
I can do that @aleene @stephanegigandet, but I'm not sure 2 files is easier than 1.

**Comment by teolemon** [comment]
``` 
[
["en:vegan",
["en:vegan", { "icon_url" : "egg", "color": #00aa00},],
["en:maybe-vegan", { "icon_url" : "egg", "color": #ff6600},],
["en:non-vegan", { "icon_url" : "egg", "color": #ff0000},]
],
["en:vegetarian",
["en:vegetarian", { "icon_url" : "leaf", "color": "#00aa00"},],
["en:maybe-vegetarian", { "icon_url" : "leaf", "color": "#ff6600"},],
["en:non-vegetarian", { "icon_url" : "leaf", "color": "#ff0000"},]
],
["en:palm-oil",
["en:palm-oil-free", { "icon_url" : "monkey_happy", "color": "#00aa00"},],
["en:may-contain-palm-oil", { "icon_url" : "monkey_uncertain", "color": "#ff6600"},],
["en:palm-oil", { "icon_url" : "monkey_unhappy", "color": "#ff0000"},]
],
```

**Comment by teolemon** [comment]
fixed according to suggestions @stephanegigandet

**Pull request merged**
