### PR TITLE
feat: Add in-context translation (solves #1738)

### PR DESCRIPTION
**Pull request by teolemon**
### What
https://support.crowdin.com/in-context-localization/#optional-parameters
To test before deploying widely. This will only work with a special locale called `lol`
https://github.com/openfoodfacts/openfoodfacts-server/blob/master/po/common/lol.po

### Part of
- #5528

### CODE REVIEW

**Comment by hangy** [comment]
I tried adding the JavaScript with Chrome DevTools, but even after logging in, it doesn't display any translations for me. image I suppose there would need some way to let Crowdin know which text is which, as the internal ID is different from the displayed text (which is why we have a custom version of gettext). Also, we shouldn't always include that script, since it immediately forces the Crowdin login dialog on the user: 
image

**Review by hangy — CHANGES_REQUESTED** [review]
- See https://github.com/openfoodfacts/openfoodfacts-server/pull/2421#issuecomment-541399738

**Comment by teolemon** [comment]
My understanding is that they have this pseudo language called `lolcat`. So the user would need to switch the website to lolcat, and then indicate the language.
Something like
`fr-lolcat.openfoodfacts.org` would possibly work.
`translate-fr` or `fr-translate` would be more intuitive

**Comment by teolemon** [comment]
@hangy you can try renaming lol.po to de.po https://github.com/openfoodfacts/openfoodfacts-server/blob/master/po/common/lol.po

**Pull request closed without merging**
