### PR TITLE
Ingredients taxonomy: update Finnish translations

### PR DESCRIPTION
**Pull request by Ban3**
**Description:**

- Fix incorrect translations
- Add new translations
- Add some unknown ingredients from fi.openfoodfacts.org
- Formatting (whitespace cleanup, re-sorting translations)

Build errors don't seem to be related to these changes:
[build_errors.txt](https://github.com/openfoodfacts/openfoodfacts-server/files/3800741/build_errors.txt)

### CODE REVIEW

**Comment by Ban3** [comment]
Looks like the failing test expects `en:flour` and `en:wheat` to be in different order in ingredient tags.

**Comment by stephanegigandet** [comment]
Thanks for the translations @Ban3 !

> Looks like the failing test expects `en:flour` and `en:wheat` to be in different order in ingredient tags.

I think that's because one more sub-level of one of those tags was added to the taxonomy, the sort order depends on the level of each tag (how many sublevels they have).

Could you update the order in the test?

**Comment by Ban3** [comment]
@stephanegigandet I can't reproduce the failure locally running `prove`. Am I missing something? I'll close & reopen to make travis look at it again, just in case it was a fluke.

**Comment by stephanegigandet** [comment]
In order to reproduce locally, you first need to rebuild the taxonomy.

It's done with this script:
cd scripts
export PERL5LIB=.
./build_tags_taxonomy.pl ingredients publish

**Comment by Ban3** [comment]
Thanks, it indeed was outdated taxonomy. Tests now pass locally and hopefully Travis is happy.

**Comment by stephanegigandet** [comment]
Wonderful, thank you very much @Ban3 ! I will merge and deploy it.

**Pull request merged**
