### PR TITLE
feat: Added view_this_revision button

### LINKED ISSUE #9943: Convert the view link into a "View this revision" button
### Problem
- Convert the view link into a "View this revision" button

### Screenshot
image

### Part of
- #5612

### PR DESCRIPTION
**Pull request by himanshisrestha**
### What
Removed this anchor tag showing "view" and replaced it with a button stating "View this Revision"

### Screenshot

Before
Screenshot 2024-04-06 at 1 24 04 AM
After
Screenshot 2024-04-07 at 11 49 37 AM

### Related issue(s) and discussion

- Fixes #9943

### CODE REVIEW

**Comment by himanshisrestha** [comment]
Just a small suggestion, could we just remove the "-" character between the buttons "View this revision" and "Revert to this  revision" with a non-breaking space ? Just to improve the look of the page

**Review by hangy — APPROVED** [review]

**Comment by alexgarel** [comment]
> Just a small suggestion, could we just remove the "-" character between the buttons "View this revision" and "Revert to this revision" with a non-breaking space ? Just to improve the look of the page

feel free to do it !

**Comment by alexgarel** [comment]
@himanshisrestha if you have make update test result failing, in this case, you can also just update the failing test: 
```
make build_taxonomies_test build_lang_test
make test-int test="web_html.t :: --update-expected-results"
```

**Review by stephanegigandet — APPROVED** [review]
Thanks!

**Pull request merged**
