### PR TITLE
build: speed up build actions

### PR DESCRIPTION
**Pull request by alexgarel**
This is an attempt at speeding up build time, by uploading docker images as artifacts

### CODE REVIEW

**Comment by alexgarel** [comment]
@stephanegigandet this take down checks to 18mn (5 min for build + 12 min for unit tests), make dev and check perl are made in parallel.

**Comment by alexgarel** [comment]
I think build_taxonomies  is still slow but I'm not sure why…

**Comment by stephanegigandet** [comment]
> @stephanegigandet we maybe should investigate rebuilding taxonomies on a regular basis, maybe with a reccuring action ?

Well could a GitHub action check if a taxonomy is changed, and in that case not only build the taxonomy, but also commit the result in the same branch?

**Comment by alexgarel** [comment]
> Well could a GitHub action check if a taxonomy is changed, and in that case not only build the taxonomy, but also commit the result in the same branch?

The problem is that on multiple commits, it will rebuild and commit. I do not find it very practical because you then have to pull before adding commit, or pull with rebase)

But maybe we can do a check and block merging if you did not rebuild all the taxonomies ?

**Pull request merged**
