### PR TITLE
Issue 1930/ingredients classes

### PR DESCRIPTION
**Pull request by stephanegigandet**
Add support for parsing ingredients like this:

Fraise origine France, Cassis (origine Afrique du Sud), Framboise (origine : Belgique), Pamplemousse bio, Orange (bio), Citron (issue de l'agriculture biologique), cacao et beurre de cacao (commerce équitable)

### CODE REVIEW

**Comment by aleene** [comment]
And what is the result of this support?

**Comment by stephanegigandet** [comment]
@aleene : you can see some examples of the results in the test file: https://github.com/openfoodfacts/openfoodfacts-server/pull/2093/files#diff-735f7de98089fa4950b2f4fa57c0f7f9

**Comment by teolemon** [comment]
@stephanegigandet will this pass ?
`Sel marin, 98% chlorure de sodium (France, Italie)`

**Comment by teolemon** [comment]
```  80% jus de pomme biologique
20% de coing biologique```

**Comment by stephanegigandet** [comment]
> @stephanegigandet will this pass ?
> `Sel marin, 98% chlorure de sodium (France, Italie)`
> https://world-fr.openfoodfacts.org/produit/7640129850334/sel-marin

Now it does.



> ```
> 80% jus de pomme biologique
> 20% de coing biologique
> ```

Yes, that already works.

**Pull request merged**
