### PR TITLE
Build Docker images using GitHub Actions

### PR DESCRIPTION
**Pull request by hangy**
**Description:** Automatically build Docker images [openfoodfacts/productopener-backend](https://cloud.docker.com/u/openfoodfacts/repository/docker/openfoodfacts/productopener-backend) and  [openfoodfacts/productopener-frontend](https://cloud.docker.com/u/openfoodfacts/repository/docker/openfoodfacts/productopener-frontend) right from GitHub Actions.

**Related issues and discussion:** N/A

### CODE REVIEW

**Comment by hangy** [comment]
This is supposed to remove the external [Azure DevOps pipeline](https://dev.azure.com/openfoodfacts/Product%20Opener/_build?definitionId=1&_a=summary). Note that the secrets `DOCKER_USERNAME` and `DOCKER_PASSWORD` will need to be set to a user that has the correct permissions to Docker Hub.

**Comment by teolemon** [comment]
@hangy can I merge ?

**Comment by hangy** [comment]
> @hangy can I merge ?

You'd need to set the secrets, so that the workflow can push the image. Do you have a user account that's authorized to the DockerHub?

**Comment by hangy** [comment]
> > @hangy can I merge ?
> 
> You'd need to set the secrets, so that the workflow can push the image. Do you have a user account that's authorized to the DockerHub?

We can now use the GitHub container registry, so that the DockerHub account is not required any more. I just ran a test and got apparently good images: https://github.com/hangy/openfoodfacts-server/packages/58972 and https://github.com/hangy/openfoodfacts-server/packages/58973

**Comment by VaiTon** [comment]
Let's try merging this.

**Pull request merged**
