### PR TITLE
style: Fixed filter bar

### PR DESCRIPTION
**Pull request by sultanowski**
### What
* Tweaked filter bar to look better on both desktop and mobile.
* Deleted inline styles and created new classes in external file.

### Screenshots
https://imgur.com/a/6vSD9P3

### Related issue(s) and discussion

- #7505 -> at least, partly.

### CODE REVIEW

**Comment by stephanegigandet** [comment]
Thanks!

Would there be a way for the icons to not be reduced on very small screens?

image

**Comment by stephanegigandet** [comment]
> I saw that every icon in button has this issue. Maybe we should refactor whole button component/class?

Is it every button? I'm trying to find others with the same issue, but the icons don't seem to be reduced:

image

**Comment by sultanowski** [comment]
"Get an App" button in Navigation Bar also shrinks icon. I would say that there's few of them. Every of them should work the same.

**Comment by sultanowski** [comment]
@stephanegigandet Now icons should not shrink on resize.

**Comment by stephanegigandet** [comment]
@sultanowski Perfect, thank you!

**Review by stephanegigandet — APPROVED** [review]

**Pull request merged**
