### PR TITLE
Add missing images/misc/ images

### PR DESCRIPTION
**Pull request by stephanegigandet**
This PR contains images that were put on the production server, but not on GitHub.

### CODE REVIEW

**Review by alexgarel — APPROVED** [review]
LGTM, but how much does it had to our already fat git ?

**Comment by stephanegigandet** [comment]
It adds 331 Mb:

off@off1:~/openfoodfacts-server/html/images$ du -ms misc
199	misc
off@off1:~/openfoodfacts-server/html/images$ git checkout images-misc
Checking out files: 100% (421/421), done.
Switched to branch 'images-misc'
off@off1:~/openfoodfacts-server/html/images$ du -ms misc
531	misc

**Comment by stephanegigandet** [comment]
Most of which is this app store thing:
315	Download-on-the-App-Store

I'll make another PR and remove it.

**Comment by stephanegigandet** [comment]
PR with less files: https://github.com/openfoodfacts/openfoodfacts-server/pull/6118

**Pull request closed without merging**
