### PR TITLE
taxonomy: Massively update the Keyhole label information

### PR DESCRIPTION
**Pull request by Freso**
### What

This massively updates the taxonomy information for the Nordic “Keyhole” label.

The Keyhole is a label governed by the states of Sweden (since 1989), Denmark and Norway (since 2009), and Iceland (since 2013) allowing food manufacturers to mark that their products live up to certain (inter)national standards/criteria of what “healthy food” is.

- primary synonyms were changed to the form used by their government institutions
- Icelandic name was added
- synonyms that duplicated the `xx` entries were removed (see linked Slack discussion)
- added `auth_urls` for the 4 relevant governmental institutions
- added `wikidata` and `wikipedia` links
- added additional synonyms to catch currently used and unrecognised terms, cf.
  - https://dk.openfoodfacts.org/labels?filter=n%C3%B8gle
  - https://no.openfoodfacts.org/labels?filter=n%C3%B8kkel
  - https://se.openfoodfacts.org/labels?filter=nyckel
- update label logo
  - the logo with the “®” symbol was deprecated as of 2024-01-01
  - the SVG used here is based on `EPS - nyckelhal_RGB_gron.eps` fetched via https://www.livsmedelsverket.se/foretagande-regler-kontroll/regler-for-livsmedelsforetag/information-markning-och-pastaenden/nyckelhalet---foretagsinformation/nedladdning-av-nyckelhalet
    - imported into Inkscape, changed dimensions to 90×90, changed the green to `#007A33` as per Livsmedelsverket’s design manual for the logo (none of the vector downloads have that as their colour for some reason), and exported as simple SVG
    - manually changed `viewBox="0 0 89.99… 89.99…"` to `viewBox="0 0 90 90"`
    - ran [`svgcleaner`](https://github.com/RazrFalcon/SVGCleaner) 0.9.5 on it (resulting in 49.93% size reduction)
  - the PNG used is `PNG - nyckelhal_RGB_gron.png` also fetched via https://www.livsmedelsverket.se/foretagande-regler-kontroll/regler-for-livsmedelsforetag/information-markning-och-pastaenden/nyckelhalet---foretagsinformation/nedladdning-av-nyckelhalet
    - `mogrify -resize 90x90 keyhole.90x90.png` (ImageMagick 7.1.1-36)
    - `oxipng --opt max --preserve --strip safe --fix --zopfli keyhole.90x90.png` (oxipng 9.1.2)

### Related issue(s) and discussion

- https://openfoodfacts.slack.com/archives/C02VDSWHT/p1723477545757929?thread_ts=1723116366.754529&cid=C02VDSWHT
- https://dk.openfoodfacts.org/labels?filter=n%C3%B8gle
- https://no.openfoodfacts.org/labels?filter=n%C3%B8kkel
- https://se.openfoodfacts.org/labels?filter=nyckel

### CODE REVIEW

**Comment by Freso** [comment]
If there’s any more (meta)data I could add (like `wikidata` or `auth_url` lines), please let me know.

Also, I wasn’t sure whether to add the Wikipedia links for all the languages or if I should have just not added any since there’s no English page for it.

**Comment by teolemon** [comment]
- Note that we have a wiki page about it: https://wiki.openfoodfacts.org/The_Keyhole

**Review by teolemon — APPROVED** [review]
That's great @Freso 👍 
We might want to keep the PNG for retrocompatibility though

**Review by stephanegigandet — APPROVED** [review]
Wonderful, thank you, and thanks for the great description in the PR. Maybe some of this info would be relevant on https://wiki.openfoodfacts.org

**Pull request merged**
