### PR TITLE
Improve RTL support

### PR DESCRIPTION
**Pull request by hangy**
**Description:**
Based off #3845, this modifies a few UI elements to improve usability with languages that use right to left text orientation.

**Related issues and discussion:** #4024

 Interesting reads:
- https://hacks.mozilla.org/2015/09/building-rtl-aware-web-apps-and-websites-part-1/
- https://hacks.mozilla.org/2015/10/building-rtl-aware-web-apps-websites-part-2/
- https://meiert.com/en/blog/css-how-to-host-right-to-left-styling/

### CODE REVIEW

**Comment by teolemon** [comment]
Is the spreadsheet applied to only languages that are actually RTL ?

**Comment by hangy** [comment]
> Is the spreadsheet applied to only languages that are actually RTL ?

`app-ltr.css` is applied to LTR languages, `app-rtl.css` to RTL languages. We need separate stylesheets because of the way that Foundation handles RTL support internally. I decided to add a `text_direction` translation for the switch, so that translators can decide if/when a translation is good enough to enable RTL mode.

**Comment by hangy** [comment]
> Thank you! Looks good to me, I'll merge it, and install it on the dev server.

Thanks!

> One thing is that all the donate html files are generated through crowdin, so we may lose the change from app.css to app-ltr.css at some point. But we can worry about it later.

I know, but I was hoping that crowdin might pick it up, because the original was changed, too. It's not a big issue, if it doesn't. 😄

**Comment by teolemon** [comment]
I'll make sure we won't get crowdin *** back.

**Pull request merged**
