### PR TITLE
feat: display "app_version" in  product edit history

### PR DESCRIPTION
**Pull request by davidpryor**
### What
Exposing the "app_version" variable from a products changes.sto file in the product edit history if populated. This allows apps to identify if data quality issues are coming from new or old versions which, in-turn, allows to track new bugs, regressions, etc in submissions.

### Screenshot
image

### Related issue(s) and discussion
**Discussion from slack**

### CODE REVIEW

**Review by stephanegigandet — APPROVED** [review]
Looks good, thank you!

**Comment by teolemon** [comment]
Thanks a lot @davidpryor 
It means the world to us that reusers are stepping in to help maintain the common good 👍

**Comment by davidpryor** [comment]
Thank you @stephanegigandet and @teolemon!
I noticed one of the test suites are failing but the failures seem unrelated to my changes.
If I need this particular job to pass, could you please trigger the job to run again. Thank you!

**Comment by stephanegigandet** [comment]
Thanks @davidpryor , it's merged.

**Pull request merged**
