### PR TITLE
log processing to populate a new popularity facet, bug #1943

### PR DESCRIPTION
**Pull request by stephanegigandet**
This is a new popularity facet based on scan logs, to be used in particular for quality review.

Details are on bug #1943

It is not perfect, but it does the job. When we have a scans database, we can make a better system.

### CODE REVIEW

**Comment by stephanegigandet** [comment]
The results can be seen on the dev server: https://world.dev.openfoodfacts.org/popularity

**Comment by teolemon** [comment]
Seems to work well in dev.

**Comment by teolemon** [comment]
I've noticed edits by scanbot in dev, but couldn't access them because the login is broken for me. What are they ?
Is the scan count updated to rank products by popularity in advanced search ?

**Comment by stephanegigandet** [comment]
The edits are added countries, when we have at least 3 ips from one country that have scanned a product.

**Pull request merged**
