### PR TITLE
Create fodmap-ingredients

### PR DESCRIPTION
**Pull request by Etatdesprit**
**Description:**

I have added some fodmap ingredients missing in taxonomie table.

### CODE REVIEW

**Comment by stephanegigandet** [comment]
This format is the format of the analysis of ingredients, but that's the result of it.

To add an ingredient to the taxonomy, you need to add it to the ingredients.txt file, in the same format.

e.g. to add the French luzerne, you would need to add:


en:alfalfa
fr:luzerne

in ingredients.txt

**Comment by teolemon** [comment]
@stephanegigandet do we need the test result file ?
taxonomies/fodmap-ingredients.txt
if not, can it be deleted @Etatdesprit ?

**Comment by stephanegigandet** [comment]
@teolemon most of those ingredients are already there in fact, they should not be added twice.

I'll create a new PR with the missing ingredients.

**Comment by stephanegigandet** [comment]
I added the new ingredients to https://github.com/openfoodfacts/openfoodfacts-server/pull/4846
closing this PR.

**Comment by teolemon** [comment]
hey @Etatdesprit @stephanegigandet moved your PR, and it will be merged soon 👍

**Pull request closed without merging**
