### PR TITLE
build: dev tooling

### PR DESCRIPTION
**Pull request by alexgarel**
First steps progress in using enabling use with vscode.

* perlcritic works
* perl language server is blocked by a bug.

**IMPORTANT:** to try this branch you will need to launch `make dev` or `docker-compose build`

### CODE REVIEW

**Comment by alexgarel** [comment]
@priyanka0906 you may test to use perlcritic on your side ?

**Comment by priyanka0906** [comment]
> @priyanka0906 you may test to use perlcritic on your side ?

@alexgarel sure I will do.

**Comment by stephanegigandet** [comment]
@alexgarel same for me, the perlcritic extension is installed, I ran make dev, what should I be looking for?

Am I supposed to run vscode in a container? If I do, I get this error:

image

**Comment by stephanegigandet** [comment]
Ah, I now do have some warnings from perlcritic I think

image

**Comment by priyanka0906** [comment]
I have installed the perlcritic extension and when I ran make dev it is building successfully.
But I didnot  add a `perlcritic.sh` at the root of your project, as I am not getting what exactly have to do in this step.

**Comment by priyanka0906** [comment]
> @alexgarel same for me, the perlcritic extension is installed, I ran make dev, what should I be looking for?
> 
> Am I supposed to run vscode in a container? If I do, I get this error:
> 
> image

**Comment by priyanka0906** [comment]
@alexgarel @stephanegigandet  I have mistakenly closed it, sorry for that .

**Comment by alexgarel** [comment]
@priyanka0906, sorry did not check this issue early enough.

So no, you should not run vscode in a container. The goal here is just to add perlcritic extension and have the extension run the perlcritic command in the container. You have to add the perlcritic.sh file, because this is the way the extension will run perlcritic inside our container.

**Comment by priyanka0906** [comment]
> @priyanka0906, sorry did not check this issue early enough.
> 
> So no, you should not run vscode in a container. The goal here is just to add perlcritic extension and have the extension run the perlcritic command in the container. You have to add the perlcritic.sh file, because this is the way the extension will run perlcritic inside our container.

okay.

**Comment by alexgarel** [comment]
@stephanegigandet can we merge this PR even if it's not yet perfect ?

**Review by stephanegigandet — APPROVED** [review]

**Comment by stephanegigandet** [comment]
> @stephanegigandet can we merge this PR even if it's not yet perfect ?

Sure, please do.

**Comment by stephanegigandet** [comment]
I'll fix the broken taxonomies.

**Comment by stephanegigandet** [comment]
@alexgarel If you merge https://github.com/openfoodfacts/openfoodfacts-server/pull/6553 in, it should fix the broken tests.

**Pull request merged**
