### PR TITLE
taxonomy: translate categories in Croatian

### PR DESCRIPTION
**Pull request by benbenben2**
### What
translate categories in Croatian

### Related issue(s) and discussion
- Fixes #-

### CODE REVIEW

**Comment by benbenben2** [comment]
> The new categories are in lowercase, is that intended? Just curious, did you use some kind of automated script / AI to translate and add the categories?

Yes, a script was used for that.

I updated to start by upper case for first character

**Comment by benbenben2** [comment]
I just tried to update integration test manually because I could not do it, nor run tests inside the container:
```
docker exec -it po_off-backend-1 bash
perl tests/integration/web_html.t
```
> Can't locate Test/File/Contents.pm in aINC (you may need to install the Test::File::Contents module) 
(can't install the package, Permission denied)

Also outside the container:
```
make test-int test="web_html.t"
```
> OCI runtime exec failed: exec failed: unable to start container process: exec: "yath": executable file not found in $PATH: unknown
make: *** [Makefile:299 : test-int] Erreur 126

**Comment by stephanegigandet** [comment]
@benbenben2 You may need to run "make dev" again to install the new modules that have been added in recent weeks.

**Review by stephanegigandet — APPROVED** [review]
Thank you!

**Pull request merged**
