### PR TITLE
Fixed spelling for German 'Papaya'

### PR DESCRIPTION
**Pull request by KommX**
**Description:**

Just fixed a spelling mistake, so that 'Papaya' gets recognized.

### CODE REVIEW

**Comment by KommX** [comment]
I only changed a single character in a string. How could this make of the tests fail?

**Comment by aleene** [comment]
One of the tests assumes `papaye`. Needs to be changed as well.

**Comment by KommX** [comment]
@aleene 
Thank you for making me aware! I hadn't figured this out.

**Review by stephanegigandet — APPROVED** [review]
Thank you!

**Pull request merged**
