### PR TITLE
move data and selected photos to another language, bug #3062

### PR DESCRIPTION
**Pull request by stephanegigandet**
see bug #3062 and please test on .dev

image

### CODE REVIEW

**Comment by teolemon** [comment]
There's no hint of the new feature in the language switcher if there's only one language.

**Comment by aleene** [comment]
Did you already deploy on dev? I do not see anything.

**Comment by teolemon** [comment]
You have to switch the main language first.

**Comment by aleene** [comment]
So:
- select new main language
- move data and images
- save

Sounds OK

**Pull request merged**
