### PR TITLE
fix regular expression and add tests, bug #2895

### PR DESCRIPTION
**Pull request by stephanegigandet**
This bug prevents products with ingredients in Russian to be saved.

### CODE REVIEW

**Comment by hangy** [comment]
I always wondered why the regexes in that file are not stored as compiled regexes in the first place. Doing so should enable validation of the regex through the Perl compiler.

**Comment by stephanegigandet** [comment]
> I always wondered why the regexes in that file are not stored as compiled regexes in the first place. Doing so should enable validation of the regex through the Perl compiler.

They are not the complete regexes though, only parts of them.
They are combined with other parts after:

e.G.
`````
if ((defined $phrases_before_ingredients_list{$language}) and (defined $product_ref->{"ingredients_text_$language"})) {

			foreach my $regexp (@{$phrases_before_ingredients_list{$language}}) {
				if ($product_ref->{"ingredients_text_$language"} =~ /(\s*)\b$regexp(\s*)(-|:|\r|\n)+(\s*)/is) {

**Comment by hangy** [comment]
> > I always wondered why the regexes in that file are not stored as compiled regexes in the first place. Doing so should enable validation of the regex through the Perl compiler.
> 
> They are not the complete regexes though, only parts of them.
> They are combined with other parts after:
> 
> e.G.
> 
> ```
> if ((defined $phrases_before_ingredients_list{$language}) and (defined $product_ref->{"ingredients_text_$language"})) {
> 
> 			foreach my $regexp (@{$phrases_before_ingredients_list{$language}}) {
> 				if ($product_ref->{"ingredients_text_$language"} =~ /(\s*)\b$regexp(\s*)(-|:|\r|\n)+(\s*)/is) {
> ```

That should not be a problem, see https://github.com/openfoodfacts/openfoodfacts-server/blob/2df4bf58aca9cc62f7b02573d287053e7f328b86/lib/ProductOpener/Ingredients.pm#L137

**Comment by stephanegigandet** [comment]
OK, it's something we can explore. I'll merge this as it fix crashes in production, we can try after to use qr//

**Pull request merged**
