### PR TITLE
refactor: enable Perl signatures 

### PR DESCRIPTION
**Pull request by stephanegigandet**
Based on the discussion in #6956, this is a new ProductOpener::Module to put boilerplate code that we want in every module. 

It replaces Modern::Perl so that we can enable signatures.

Also switched one module, Nutriscore.pm, to signatures.

### CODE REVIEW

**Review by dipietroR — APPROVED** [review]
So we would replace the prototype:
```
sub something($) {
  my $var1 = shift;
```

with a signature:
```
sub something($var) {
```
?
I think that would be great!

**Comment by Ban3** [comment]
Functionally, it's fine, but I'd go for a more descriptive name. How about `PerlStandards` suggested by @hangy? It would be clear from the name what it does.

**Review by hangy — APPROVED** [review]

**Review by alexgarel — APPROVED** [review]
Really cool.

**Comment by stephanegigandet** [comment]
> So we would replace the prototype:
> 
> ```
> sub something($) {
>   my $var1 = shift;
> ```
> 
> with a signature:
> 
> ```
> sub something($var) {
> ```
> 
> ?

Yes, exactly.

**Pull request merged**
