### PR TITLE
Attempt to create a magic mailtolink for followup

### PR DESCRIPTION
**Pull request by teolemon**
Attempt to create a magic mailtolink for D+5 followup after account creation.
You can use https://mailtolink.me/

### CODE REVIEW

**Comment by stephanegigandet** [comment]
characters like $ and @ also need escaping as otherwise Perl will interpret them.

I'll adapt the code to do the url encoding in Perl, that way we can at least have readable text

**Comment by stephanegigandet** [comment]
I'll make changes on the branch, please don't change it for now.

**Comment by teolemon** [comment]
@stephanegigandet Can't approve my own pr

**Review by stephanegigandet — APPROVED** [review]
I like my changes a lot.

**Pull request merged**
