### PR TITLE
Dutch specific additions

### PR DESCRIPTION
**Pull request by aleene**
**Description:**
I tried to add (some) dutch recycling instructions. But I am not sure I add them to the right files. The instructions often have the structure `<packaging> in/bij <recycling bin>`. Where can I add the structure? And what to do about adding logo's for Robotoff?

### CODE REVIEW

**Comment by aleene** [comment]
Need to add these https://kidv.nl/media/weggooiwijzer/2021_kidv_weggooiwijzer_handleiding_nl_juni_2021.pdf?1.2.2

**Comment by stephanegigandet** [comment]
> The instructions often have the structure `<packaging> in/bij <recycling bin>`.

We should add some of those in the tests t/packaging.txt, to make sure that we parse them correctly.

**Comment by aleene** [comment]
I'll create some tests. What about the recycling instruction part? Where can I add/test that?

**Comment by stephanegigandet** [comment]
> I'll create some tests. What about the recycling instruction part? Where can I add/test that?

It's in packaging.txt as well.

We may need to do some code changes, as the code is expecting something like "[shape] in [material] to [discard/recycle]", whereas in Dutch we have something like "[shape] to recycle in [material] bin". e.g. "XYZ bij oud papier." does not necessarily mean that XYZ is in paper, it could be cardboard I guess.

**Comment by aleene** [comment]
> We may need to do some code changes, as the code is expecting something like "[shape] in [material] to [discard/recycle]", whereas in Dutch we have something like "[shape] to recycle in [material] bin". e.g. "XYZ bij oud papier." does not necessarily mean that XYZ is in paper, it could be cardboard I guess.
Correct in NL you throw the cardboard items into the paper bin. So we do not know what XYZ is made of.

**Comment by aleene** [comment]
I commented out the tests. The taxonomies need to be committed before I can add those.

**Review by stephanegigandet — APPROVED** [review]
Thank you!

**Pull request merged**
