### PR TITLE
chore: Updated logo on donation form

### LINKED ISSUE #7122: Update new Open Food Facts logo on the donation form
On this page : https://world.openfoodfacts.org/donate-to-open-food-facts?utm_source=off&utm_medium=web&utm_campaign=donate-2022&utm_term=en-text-button, the logo of Open Food Facts is not up to date

### PR DESCRIPTION
**Pull request by pratyaksh1610**
### Related issue(s) and discussion
- Fixes #7122

### Before
off1

### After
off2

### CODE REVIEW

**Comment by pratyaksh1610** [comment]
I tried generating the CSS file, it is showing `file not found` error.

**Comment by pratyaksh1610** [comment]
@VaiTon PTAL.

**Review by VaiTon — APPROVED** [review]

**Comment by alexgarel** [comment]
@pratyaksh1610 shan't we do it for all languages ?

cc @teolemon 

> I tried generating the CSS file, it is showing file not found error.
You need to have docker-compose running as the CSS is generated by the dynamicfront container (using gulp.js)

**Comment by pratyaksh1610** [comment]
@alexgarel I am not sure, if we are having the new logo in all languages.

Another approach I think, can be we can update the logo on donation form irrespective of language , to an icon maybe.

**Comment by pratyaksh1610** [comment]
@alexgarel Any update on this ?

**Comment by pratyaksh1610** [comment]
Is it ready for merge ?

**Review by VaiTon — APPROVED** [review]

**Comment by teolemon** [comment]
In time when daily sync occurs

**Pull request merged**
