### PR TITLE
Agribalyse 21 octobre

### PR DESCRIPTION
**Pull request by teolemon**
Agribalyse 21 octobre

### CODE REVIEW

**Comment by teolemon** [comment]
Errors in the categories taxonomy definition:
ERROR - fr:pate-sablee already is a synonym of fr:pates-sablees for entry fr:pates-sablees - fr:pate-sablee cannot be mapped to entry en:shortbread-dough

**Comment by teolemon** [comment]
Errors in the categories taxonomy definition:
ERROR - fr:pate-sablee already is a synonym of fr:pates-sablees for entry fr:pates-sablees - fr:pate-sablee cannot be mapped to entry en:shortbread-dough
ERROR - fr:pate-a-pizza already is a synonym of fr:pates-a-pizza for entry en:pizza-dough - fr:pate-a-pizza cannot be mapped to entry en:pizza-base

**Comment by teolemon** [comment]
ERROR - fr:cabillaud already is a synonym of fr:morues for entry en:cods - fr:cabillaud cannot be mapped to entry en:cod
ERROR - fr:gratin-de-fruits-de-mer-a-cuire already is a synonym of fr:gratin-de-poissons-a-cuire for entry en:fish-au-gratin-intended-to-be-cooked - fr:gratin-de-poissons-cuit cannot be mapped to entry en:fish-and-shrimp-au-gratin-previously-frozen
ERROR - fr:pate-sablee already is a synonym of fr:pates-sablees for entry fr:pates-sablees - fr:pate-sablee cannot be mapped to entry en:shortbread-dough

**Comment by teolemon** [comment]
Errors in the categories taxonomy definition:
ERROR - en:frozen-surmullet-with-skin is a parent of itself
ERROR - en:frozen-surmullet-with-skin is a parent of itself

**Comment by teolemon** [comment]
Errors in the categories taxonomy definition:
ERROR - en:breakfast-cereals-filled-with-chocolate is a parent of itself
ERROR - en:breakfast-cereals-filled-with-chocolate-hazelnuts is a parent of itself
ERROR - en:pumpkin-seeds is a parent of itself
ERROR - en:unshelled-pumpkin-seeds is a parent of itself
ERROR - en:shelled-pumpkin-seeds is a parent of itself
ERROR - en:sunflower-seeds is a parent of itself
ERROR - en:unshelled-sunflower-seeds is a parent of itself
ERROR - en:shelled-sunflower-seeds is a parent of itself
ERROR - en:broccoli is a parent of itself
ERROR - en:brussels-sprouts is a parent of itself
ERROR - en:green-cabbage is a parent of itself
ERROR - en:breakfast-cereals-filled-with-chocolate-fortified-with-vitamins-and-chemical-elements has an undefined parent 
ERROR - en:breakfast-cereals-filled-with-chocolate-hazelnuts-fortified-with-vitamins-and-chemical-elements has an undefined parent 
ERROR - en:breakfast-cereals-rich-in-fibre-fortified-with-vitamins-and-chemical-elements has an undefined parent 
ERROR - en:chocolate-wheat-grain-flakes-fortified-with-vitamins-and-chemical-elements has an undefined parent 
ERROR - en:breakfast-chocolate-high-fiber-cereals-fortified-with-vitamins-and-chemical-elements has an undefined parent 
ERROR - en:unfilled-breakfast-chocolate-cereals-fortified-with-vitamins-and-chemical-elements has an undefined parent 
ERROR - en:breakfast-cereals-with-chocolate-puffed-rice-fortified-with-vitamins-and-chemical-elements has an undefined parent 
ERROR - en:chocolate-puffed-wheat-grains-fortified-with-vitamins-and-chemical-elements has an undefined parent 
ERROR - en:diet-breakfast-cereals-fortified-with-vitamins-and-chemical-elements has an undefined parent 
ERROR - en:diet-chocolate-breakfast-cereals-fortified-with-vitamins-and-chemical-elements has an undefined parent 
ERROR - en:breakfast-cereals-filled-with-something-other-than-chocolate-fortified-with-vitamins-and-chemical-elements has an undefined parent 
ERROR - en:puffed-wheat-grains has an undefined parent 
ERROR - en:shelled-pumpkin-seeds has an undefined parent 
ERROR - en:sweet-breakfast-cereals-fortified-with-vitamins-and-chemical-elements has an undefined parent

**Review by stephanegigandet — APPROVED** [review]

**Comment by teolemon** [comment]
Errors in the categories taxonomy definition:
ERROR - en:puffed-wheat-grains has an undefined parent 
Errors in the categories taxonomy definition at lib/ProductOpener/Tags.pm line 1634.

**Comment by teolemon** [comment]
Errors in the categories taxonomy definition:
ERROR - en:lamb-brain is a parent of itself
ERROR - en:veal-knuckle is a parent of itself
ERROR - en:calf-brain is a parent of itself

**Comment by teolemon** [comment]
t/store.t ........................ ok
t/products.t ..................... ok
t/text.t ......................... ok
add_tags_to_field - adding en:apples to categories: current: does not exist
add_tags_to_field - adding en:bananas to categories: current: does not exist
add_tags_to_fields value: 

#   Failed test at t/tags.t line 66.
#     Structures begin differing at:
#          $got->{categories_tags}[5] = 'en:tropical-fruits'
#     $expected->{categories_tags}[5] = 'en:apples'
# {
#   'categories' => 'pommes, bananes',
#   'categories_hierarchy' => [
#     'en:plant-based-foods-and-beverages',
#     'en:plant-based-foods',
#     'en:fruits-and-vegetables-based-foods',
#     'en:fruits-based-foods',
#     'en:fruits',
#     'en:tropical-fruits',
#     'en:apples',
#     'en:bananas'
#   ],
#   'categories_lc' => 'fr',
#   'categories_tags' => [
#     'en:plant-based-foods-and-beverages',
#     'en:plant-based-foods',
#     'en:fruits-and-vegetables-based-foods',
#     'en:fruits-based-foods',
#     'en:fruits',
#     'en:tropical-fruits',
#     'en:apples',
#     'en:bananas'
#   ],
#   'lc' => 'fr'
# }

#   Failed test at t/tags.t line 103.
#     Structures begin differing at:
#          $got->{categories_tags}[5] = 'en:tropical-fruits'
#     $expected->{categories_tags}[5] = 'en:apples'
# {
#   'categories' => 'pommes, bananes',
#   'categories_hierarchy' => [
#     'en:plant-based-foods-and-beverages',
#     'en:plant-based-foods',
#     'en:fruits-and-vegetables-based-foods',
#     'en:fruits-based-foods',
#     'en:fruits',
#     'en:tropical-fruits',
#     'en:apples',
#     'en:bananas'
#   ],
#   'categories_lc' => 'fr',
#   'categories_tags' => [
#     'en:plant-based-foods-and-beverages',
#     'en:plant-based-foods',
#     'en:fruits-and-vegetables-based-foods',
#     'en:fruits-based-foods',
#     'en:fruits',
#     'en:tropical-fruits',
#     'en:apples',
#     'en:bananas'
#   ],
#   'lc' => 'fr'
# }
tag: en:plant-based-foods-and-beverages	level: 10
tag: en:plant-based-foods	level: 9
tag: en:fruits-and-vegetables-based-foods	level: 7
tag: en:fruits-based-foods	level: 6
tag: en:fruits	level: 5
tag: en:tropical-fruits	level: 4
tag: en:apples	level: 3
tag: en:bananas	level: 3
add_tags_to_field - adding en:strawberries to categories: current: pommes, bananes
add_tags_to_fields value: <a href="/categorie/aliments-et-boissons-a-base-de-vegetaux" class="tag well_known">Aliments et boissons à base de végétaux</a>, <a href="/categorie/aliments-d-origine-vegetale" class="tag well_known">Aliments d'origine végétale</a>, <a href="/categorie/aliments-a-base-de-fruits-et-de-legumes" class="tag well_known">Aliments à base de fruits et de légumes</a>, <a href="/categorie/fruits-et-produits-derives" class="tag well_known">Fruits et produits dérivés</a>, <a href="/categorie/fruits" class="tag well_known">Fruits</a>, <a href="/categorie/fruits-tropicaux" class="tag well_known">Fruits tropicaux</a>, <a href="/categorie/pommes" class="tag well_known">Pommes</a>, <a href="/categorie/bananes" class="tag well_known">Bananes</a>

#   Failed test at t/tags.t line 143.
#          got: 'Aliments et boissons � base de v�g�taux, Aliments d'origine v�g�tale, Aliments � base de fruits et de l�gumes, Fruits et produits d�riv�s, Fruits, Fruits tropicaux, Pommes, Bananes, fraises'
#     expected: 'Aliments et boissons � base de v�g�taux, Aliments d'origine v�g�tale, Aliments � base de fruits et de l�gumes, Fruits et produits d�riv�s, Fruits, Pommes, Fruits tropicaux, Bananes, fraises'
add_tags_to_field - adding en:raspberries to categories: current: Aliments et boissons à base de végétaux, Aliments d'origine végétale, Aliments à base de fruits et de légumes, Fruits et produits dérivés, Fruits, Fruits tropicaux, Pommes, Bananes, fraises
add_tags_to_field - adding en:plums to categories: current: Aliments et boissons à base de végétaux, Aliments d'origine végétale, Aliments à base de fruits et de légumes, Fruits et produits dérivés, Fruits, Fruits tropicaux, Pommes, Bananes, fraises
add_tags_to_fields value: <a href="/categorie/aliments-et-boissons-a-base-de-vegetaux" class="tag well_known">Aliments et boissons à base de végétaux</a>, <a href="/categorie/aliments-d-origine-vegetale" class="tag well_known">Aliments d'origine végétale</a>, <a href="/categorie/aliments-a-base-de-fruits-et-de-legumes" class="tag well_known">Aliments à base de fruits et de légumes</a>, <a href="/categorie/fruits-et-produits-derives" class="tag well_known">Fruits et produits dérivés</a>, <a href="/categorie/fruits" class="tag well_known">Fruits</a>, <a href="/categorie/fruits-tropicaux" class="tag well_known">Fruits tropicaux</a>, <a href="/categorie/pommes" class="tag well_known">Pommes</a>, <a href="/categorie/bananes" class="tag well_known">Bananes</a>, <a href="/categorie/fruits-rouges" class="tag well_known">Fruits rouges</a>, <a href="/categorie/fraises" class="tag well_known">Fraises</a>

#   Failed test at t/tags.t line 165.
#     Structures begin differing at:
#          $got->[5] = 'en:tropical-fruits'
#     $expected->[5] = 'en:apples'
# [
#   'en:plant-based-foods-and-beverages',
#   'en:plant-based-foods',
#   'en:fruits-and-vegetables-based-foods',
#   'en:fruits-based-foods',
#   'en:fruits',
#   'en:tropical-fruits',
#   'en:apples',
#   'en:bananas',
#   'en:berries',
#   'en:plums',
#   'en:raspberries',
#   'en:strawberries'
# ]
add_tags_to_field - adding en:oranges to categories: current: Aliments et boissons à base de végétaux, Aliments d'origine végétale, Aliments à base de fruits et de légumes, Fruits et produits dérivés, Fruits, Fruits tropicaux, Pommes, Bananes, Fruits rouges, Fraises, en:raspberries, en:plum
add_tags_to_field - adding en:lemons to categories: current: Aliments et boissons à base de végétaux, Aliments d'origine végétale, Aliments à base de fruits et de légumes, Fruits et produits dérivés, Fruits, Fruits tropicaux, Pommes, Bananes, Fruits rouges, Fraises, en:raspberries, en:plum
add_tags_to_fields value: <a href="/categoria/alimentos-y-bebidas-de-origen-vegetal" class="tag well_known">Alimentos y bebidas de origen vegetal</a>, <a href="/categoria/alimentos-de-origen-vegetal" class="tag well_known">Alimentos de origen vegetal</a>, <a href="/categoria/frutas-y-verduras-y-sus-productos" class="tag well_known">Frutas y verduras y sus productos</a>, <a href="/categoria/frutas-y-sus-productos" class="tag well_known">Frutas y sus productos</a>, <a href="/categoria/frutas" class="tag well_known">Frutas</a>, <a href="/categoria/frutas-tropicales" class="tag well_known">Frutas tropicales</a>, <a href="/categoria/manzanas" class="tag well_known">Manzanas</a>, <a href="/categoria/platanos" class="tag well_known">Plátanos</a>, <a href="/categoria/frutas-del-bosque" class="tag well_known">Frutas del bosque</a>, <a href="/categoria/ciruelas" class="tag well_known">Ciruelas</a>, <a href="/categoria/frambuesas" class="tag well_known">Frambuesas</a>, <a href="/categoria/fresas" class="tag well_known">Fresas</a>

#   Failed test at t/tags.t line 190.
#     Structures begin differing at:
#          $got->[5] = 'en:citrus'
#     $expected->[5] = 'en:apples'
# [
#   'en:plant-based-foods-and-beverages',
#   'en:plant-based-foods',
#   'en:fruits-and-vegetables-based-foods',
#   'en:fruits-based-foods',
#   'en:fruits',
#   'en:citrus',
#   'en:tropical-fruits',
#   'en:apples',
#   'en:bananas',
#   'en:berries',
#   'en:lemons',
#   'en:oranges',
#   'en:plums',
#   'en:raspberries',
#   'en:strawberries'
# ]

#   Failed test at t/tags.t line 192.
#          got: 'Alimentos y bebidas de origen vegetal, Alimentos de origen vegetal, Frutas y verduras y sus productos, Frutas y sus productos, Frutas, Frutas tropicales, Manzanas, Pl�tanos, Frutas del bosque, Ciruelas, Frambuesas, Fresas, naranjas, limones'
#     expected: 'Alimentos y bebidas de origen vegetal, Alimentos de origen vegetal, Frutas y verduras y sus productos, Frutas y sus productos, Frutas, Manzanas, Frutas del bosque, Frutas tropicales, Pl�tanos, Ciruelas, Frambuesas, Fresas, naranjas, limones'
add_tags_to_field - adding it:bogus to categories: current: Alimentos y bebidas de origen vegetal, Alimentos de origen vegetal, Frutas y verduras y sus productos, Frutas y sus productos, Frutas, Frutas tropicales, Manzanas, Plátanos, Frutas del bosque, Ciruelas, Frambuesas, Fresas, naranjas, limones
add_tags_to_fields value: <a href="/category/cibi-e-bevande-a-base-vegetale" class="tag well_known">Cibi e bevande a base vegetale</a>, <a href="/category/cibi-a-base-vegetale" class="tag well_known">Cibi a base vegetale</a>, <a href="/category/cibi-a-base-di-frutta-e-verdura" class="tag well_known">Cibi a base di frutta e verdura</a>, <a href="/category/cibi-a-base-di-frutta" class="tag well_known">Cibi a base di frutta</a>, <a href="/category/frutta" class="tag well_known">Frutta</a>, <a href="/category/agrumi" class="tag well_known">Agrumi</a>, <a href="/category/frutti-esotici" class="tag well_known">Frutti esotici</a>, <a href="/category/mele" class="tag well_known">Mele</a>, <a href="/category/banane" class="tag well_known">Banane</a>, <a href="/category/frutti-di-bosco" class="tag well_known">Frutti di bosco</a>, <a href="/category/limoni" class="tag well_known">Limoni</a>, <a href="/category/arance" class="tag well_known">Arance</a>, <a href="/category/en:plums" class="tag well_known" lang="en">en:Plums</a>, <a href="/category/lamponi" class="tag well_known">Lamponi</a>, <a href="/category/fragole" class="tag well_known">Fragole</a>

#   Failed test at t/tags.t line 199.
#     Structures begin differing at:
#          $got->[5] = 'en:citrus'
#     $expected->[5] = 'en:apples'
# {
#   'categories' => 'Cibi e bevande a base vegetale, Cibi a base vegetale, Cibi a base di frutta e verdura, Cibi a base di frutta, Frutta, Agrumi, Frutti esotici, Mele, Banane, Frutti di bosco, Limoni, Arance, en:Plums, Lamponi, Fragole, bogus',
#   'categories_hierarchy' => [
#     'en:plant-based-foods-and-beverages',
#     'en:plant-based-foods',
#     'en:fruits-and-vegetables-based-foods',
#     'en:fruits-based-foods',
#     'en:fruits',
#     'en:citrus',
#     'en:tropical-fruits',
#     'en:apples',
#     'en:bananas',
#     'en:berries',
#     'en:lemons',
#     'en:oranges',
#     'en:plums',
#     'en:raspberries',
#     'en:strawberries',
#     'it:bogus'
#   ],
#   'categories_lc' => 'it',
#   'categories_tags' => [
#     'en:plant-based-foods-and-beverages',
#     'en:plant-based-foods',
#     'en:fruits-and-vegetables-based-foods',
#     'en:fruits-based-foods',
#     'en:fruits',
#     'en:citrus',
#     'en:tropical-fruits',
#     'en:apples',
#     'en:bananas',
#     'en:berries',
#     'en:lemons',
#     'en:oranges',
#     'en:plums',
#     'en:raspberries',
#     'en:strawberries',
#     'it:bogus'
#   ],
#   'lc' => 'fr'
# }
add_tags_to_field - adding en:france to countries: current: does not exist
add_tags_to_field - adding en:spain to countries: current: does not exist
add_tags_to_field - adding fr:deutschland to countries: current: does not exist
add_tags_to_field - adding en:bolivia to countries: current: does not exist
add_tags_to_field - adding en:italy to countries: current: does not exist
add_tags_to_field - adding en:switzerland to countries: current: does not exist
add_tags_to_field - adding en:colombia to countries: current: does not exist
add_tags_to_field - adding fr:bidon to countries: current: does not exist
add_tags_to_fields value: 
add_tags_to_field - adding en:peru to countries: current: france, en:spain, deutschland, fr:bolivie, italie, de:suisse, colombia, bidon
add_tags_to_field - adding es:bogus to countries: current: france, en:spain, deutschland, fr:bolivie, italie, de:suisse, colombia, bidon
add_tags_to_fields value: <a href="/pais/bolivia" class="tag well_known">Bolivia</a>, <a href="/pais/colombia" class="tag well_known">Colombia</a>, <a href="/pais/francia" class="tag well_known">Francia</a>, <a href="/pais/italia" class="tag well_known">Italia</a>, <a href="/pais/espana" class="tag well_known">España</a>, <a href="/pais/suiza" class="tag well_known">Suiza</a>, <a href="/pais/fr:bidon" class="tag user_defined" lang="fr">fr:bidon</a>, <a href="/pais/fr:deutschland" class="tag user_defined" lang="fr">fr:deutschland</a>
add_tags_to_field - adding baba to brands: current: does not exist
add_tags_to_field - adding bobo to brands: current: does not exist
add_tags_to_field - adding bibi to brands: current: Baba, Bobo
tag: en:fruit	level: 5
tag: en:citrus-fruit	level: 4
tag: en:fruit-juice	level: 4
tag: en:salt	level: 4
tag: en:sugar	level: 4
tag: en:orange	level: 3
tag: en:orange-juice	level: 2
tag: en:concentrated-orange-juice	level: 1
add_tags_to_field - adding en:apples to categories: current: does not exist
add_tags_to_fields value: <a href="/categorie/plats-prepares" class="tag well_known">Plats préparés</a>
add_tags_to_field - adding en:bananas to categories: current: Plats préparés, pommes
add_tags_to_fields value: <a href="/category/plant-based-foods-and-beverages" class="tag well_known">Plant-based foods and beverages</a>, <a href="/category/plant-based-foods" class="tag well_known">Plant-based foods</a>, <a href="/category/fruits-and-vegetables-based-foods" class="tag well_known">Fruits and vegetables based foods</a>, <a href="/category/fruits-based-foods" class="tag well_known">Fruits based foods</a>, <a href="/category/meals" class="tag well_known">Meals</a>, <a href="/category/fruits" class="tag well_known">Fruits</a>, <a href="/category/apples" class="tag well_known">Apples</a>
add_tags_to_field - adding en:pears to categories: current: Plant-based foods and beverages, Plant-based foods, Fruits and vegetables based foods, Fruits based foods, Meals, Fruits, Apples, bananas
add_tags_to_fields value: <a href="/category/plant-based-foods-and-beverages" class="tag well_known">Plant-based foods and beverages</a>, <a href="/category/plant-based-foods" class="tag well_known">Plant-based foods</a>, <a href="/category/fruits-and-vegetables-based-foods" class="tag well_known">Fruits and vegetables based foods</a>, <a href="/category/fruits-based-foods" class="tag well_known">Fruits based foods</a>, <a href="/category/meals" class="tag well_known">Meals</a>, <a href="/category/fruits" class="tag well_known">Fruits</a>, <a href="/category/tropical-fruits" class="tag well_known">Tropical fruits</a>, <a href="/category/apples" class="tag well_known">Apples</a>, <a href="/category/bananas" class="tag well_known">Bananas</a>
add_tags_to_field - adding en:peaches to categories: current: Plant-based foods and beverages, Plant-based foods, Fruits and vegetables based foods, Fruits based foods, Meals, Fruits, Tropical fruits, Apples, Bananas, en:pears
add_tags_to_fields value: <a href="/categoria/alimentos-y-bebidas-de-origen-vegetal" class="tag well_known">Alimentos y bebidas de origen vegetal</a>, <a href="/categoria/alimentos-de-origen-vegetal" class="tag well_known">Alimentos de origen vegetal</a>, <a href="/categoria/frutas-y-verduras-y-sus-productos" class="tag well_known">Frutas y verduras y sus productos</a>, <a href="/categoria/frutas-y-sus-productos" class="tag well_known">Frutas y sus productos</a>, <a href="/categoria/comidas-preparadas" class="tag well_known">Comidas preparadas</a>, <a href="/categoria/frutas" class="tag well_known">Frutas</a>, <a href="/categoria/frutas-tropicales" class="tag well_known">Frutas tropicales</a>, <a href="/categoria/manzanas" class="tag well_known">Manzanas</a>, <a href="/categoria/platanos" class="tag well_known">Plátanos</a>, <a href="/categoria/peras" class="tag well_known">Peras</a>

#   Failed test at t/tags.t line 565.
#     Structures begin differing at:
#          $got->[3] = 'en:fruits-based-foods'
#     $expected->[3] = 'en:meals'
# {
#   'categories' => "Alimentos y bebidas de origen vegetal, Alimentos de origen vegetal, Frutas y verduras y sus productos, Frutas y sus productos, Comidas preparadas, Frutas, Frutas tropicales, Manzanas, Pl\x{e1}tanos, Peras, en:peaches",
#   'categories_hierarchy' => [
#     'en:plant-based-foods-and-beverages',
#     'en:plant-based-foods',
#     'en:fruits-and-vegetables-based-foods',
#     'en:fruits-based-foods',
#     'en:meals',
#     'en:fruits',
#     'en:tropical-fruits',
#     'en:apples',
#     'en:bananas',
#     'en:peaches',
#     'en:pears'
#   ],
#   'categories_lc' => 'es',
#   'categories_tags' => [
#     'en:plant-based-foods-and-beverages',
#     'en:plant-based-foods',
#     'en:fruits-and-vegetables-based-foods',
#     'en:fruits-based-foods',
#     'en:meals',
#     'en:fruits',
#     'en:tropical-fruits',
#     'en:apples',
#     'en:bananas',
#     'en:peaches',
#     'en:pears'
#   ],
#   'lc' => 'fr'
# }

#   Failed test at t/tags.t line 587.
#     Structures begin differing at:
#          $got->[5] = 'en:citrus'
#     $expected->[5] = 'en:apples'
# {
#   'categories' => 'pommes, bananes, en:pears, fr:fraises, es:limones',
#   'categories_hierarchy' => [
#     'en:plant-based-foods-and-beverages',
#     'en:plant-based-foods',
#     'en:fruits-and-vegetables-based-foods',
#     'en:fruits-based-foods',
#     'en:fruits',
#     'en:citrus',
#     'en:tropical-fruits',
#     'en:apples',
#     'en:bananas',
#     'en:berries',
#     'en:lemons',
#     'en:pears',
#     'en:strawberries'
#   ],
#   'categories_lc' => 'fr',
#   'categories_tags' => [
#     'en:plant-based-foods-and-beverages',
#     'en:plant-based-foods',
#     'en:fruits-and-vegetables-based-foods',
#     'en:fruits-based-foods',
#     'en:fruits',
#     'en:citrus',
#     'en:tropical-fruits',
#     'en:apples',
#     'en:bananas',
#     'en:berries',
#     'en:lemons',
#     'en:pears',
#     'en:strawberries'
#   ],
#   'lc' => 'fr'
# }
# Looks like you failed 9 tests of 137.
t/tags.t ......................... 
Dubious, test returned 9 (wstat 2304, 0x900)
Failed 9/137 subtests 
t/vitamins.t ..................... ok

Test Summary Report
-------------------
t/tags.t                       (Wstat: 2304 Tests: 137 Failed: 9)
  Failed tests:  17-18, 20-24, 95-96
  Non-zero exit status: 9
Files=34, Tests=2414, 130 wallclock secs ( 0.52 usr  0.11 sys + 178.41 cusr 17.53 csys = 196.57 CPU)
Result: FAIL
Error: Process completed with exit code 1.

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-server/blob/agb-21oct/t/tags.t#L66
https://github.com/openfoodfacts/openfoodfacts-server/blob/agb-21oct/t/tags.t#L103
https://github.com/openfoodfacts/openfoodfacts-server/blob/agb-21oct/t/tags.t#L143
https://github.com/openfoodfacts/openfoodfacts-server/blob/agb-21oct/t/tags.t#L165
https://github.com/openfoodfacts/openfoodfacts-server/blob/agb-21oct/t/tags.t#L190
https://github.com/openfoodfacts/openfoodfacts-server/blob/agb-21oct/t/tags.t#L192
https://github.com/openfoodfacts/openfoodfacts-server/blob/agb-21oct/t/tags.t#L199
https://github.com/openfoodfacts/openfoodfacts-server/blob/agb-21oct/t/tags.t#L565
https://github.com/openfoodfacts/openfoodfacts-server/blob/agb-21oct/t/tags.t#L587

**Comment by teolemon** [comment]
@stephanegigandet has integrated my changes in his own PR, just merged. After rebasing, no diffs. >> closing this PR

**Pull request closed without merging**
