### PR TITLE
Image optimization

### PR DESCRIPTION
**Pull request by hangy**
I ran ran most if not all SVGs through `svgo --multipass`. This yielded 75%-90% file size reduction for some images with no noticeable loss in quality.

### CODE REVIEW

**Comment by stephanegigandet** [comment]
Good idea. Can we store the original SVGs somewhere though? The original files are useful if we want to edit them again. I know they would be in the github history, but it's less convenient.

Or another approach could be to keep the unoptimized SVG files in github, and just to run svgo in a deployment script or something. i.e. we keep the source, not the "binaries". What do you think?

**Comment by hangy** [comment]
Sure, with the Foundation SASS branch, I added gulp anyways, so we could try integrating an image optimizer in that step easily. Just wasn't sure if everyone would want that. 😃

**Comment by teolemon** [comment]
conflict

**Comment by teolemon** [comment]
:kissing_heart:

**Pull request closed without merging**
