### PR TITLE
taxonomy: Fixed paprika issue

### PR DESCRIPTION
**Pull request by moon-rabbitOFF**

### CODE REVIEW

**Comment by stephanegigandet** [comment]
Can you take a look @aleene ? Should we add a "paprika" entry in Dutch? to "bell peppers"?

**Comment by moon-rabbitOFF** [comment]
We can indeed. It was in plural form only "nl:Paprikas", I added the singular.

**Comment by aleene** [comment]
I probably removed the singular paprika, as it is ambiguous. It can also men the spice.

**Comment by moon-rabbitOFF** [comment]
Ah ok, so I remove it again

**Review by stephanegigandet — APPROVED** [review]

**Pull request merged**
