### PR TITLE
Add Sphinx Documentation

### PR DESCRIPTION
**Pull request by tapaswenipathak**
**Checklist:**

Make sure you've done all the following (You can delete the checklist before submitting)

* [ ] Code is well documented
* [ ] Include unit tests for new functionality
* [ ] Code passes Travis builds in your branch
* [x] If you have multiple commits please combine them into one commit by squashing them.
* [x] Read and understood the [contribution guidelines](https://github.com/openfoodfacts/openfoodfacts-server/blob/master/CONTRIBUTING.md)

**Description:**

Describe the changes made and why they were made instead of how they were made.
Add Sphinx Documentation Website hosted on Read The Docs. This has

- Base Sphinx documentation hosted on https://readthedocs.org/
- Build a dedicated documentation site
- Create a developper page for OpenFoodFacts.org
- Write conceptual overviews of the Open Food Facts products
   -  Write a conceptual overview and introduction to the Open Food Facts server - The high level goals, the architecture, the libraries used, the known limitations and the high level wishlist
- Document the Open Food Facts API
- Document how to install the Open Food Facts server
- Extracting knowledge from Slack channels
- Write introduction pages for audiences
   - Users
       - Feature page for Web
       - Feature page for Android
       - Feature page for iOS
       - Producer's page
       - Startups
       - Food companies
       - SMB with 300-400 products
       - Startup with 12 products
       - Global group with processes, different product lines, managed globally
       - Hard discounted, no IT
       - Food distributors
       - Page for journalists with presskits
   - Journalists
      - Scientific journalist
      - Beauty/Healthy/Lifestyle journalist
      - Journalist students
      - Tech journalists
      - Android/iOS/OpenData/Generalists
   - Page for developpers
     - Developpers
     - Indie developpers
     - Corporate developpers
   - Page for Researchers
    - Researchers (AI, Nutrition)
   - Page for Politicians/Government
   - Page for Dieteticians/Nutritionists
   - Build a directory of Open Food Facts reuses

**Related issues and discussion:** #[ISSUE NUMBER]
Hi folks, I am GSoD'19 applicant, I read the tickets labelled as [documentation](https://github.com/openfoodfacts/openfoodfacts-server/labels/documentation) in the repository, mostly they were taken or had a PR in review, were very easy tasks or required discussion (I can't afford having a discussion at this point). I am PRing [few GSoD'19 intern task](https://en.wiki.openfoodfacts.org/SeasonOfDocs), I will use this work in the application. I really liked your project, I would be happy finishing this PR in a day.

### CODE REVIEW

**Comment by tapaswenipathak** [comment]
Hello maintainers: Do you take prs? I opened a pr long back and didn't get any reviews strangely, lol.

cc @teolemon @aleene @stephanegigandet @hangy.

**Comment by tapaswenipathak** [comment]
Hello maintainers: Do you take external prs? I opened a pr long back and didn't get any reviews weirdly and closed few hours before. Thinking my work can be of any use?

cc @teolemon @aleene @stephanegigandet @hangy. (top contributors)

**Comment by VaiTon** [comment]
@openfoodfacts/open-food-facts-contributors any thoughts?

**Comment by teolemon** [comment]
We now have a structured effort at @openfoodfacts/api-documentation 
I propose closing the PR

**Pull request closed without merging**
