### PR TITLE
Logo BBC

### PR DESCRIPTION
**Pull request by teolemon**
Logo BBC

### CODE REVIEW

**Comment by teolemon** [comment]
@stephanegigandet is it ok ?

**Comment by VaiTon** [comment]
@teolemon if you could rename it so that oe is not a single character.

**Comment by stephanegigandet** [comment]
@teolemon: the file name must be the canonical name : bleu-blanc-cœur.svg -> bleu-blanc-coeur.98x90.svg  (note the oe instead of œ)

**Comment by stephanegigandet** [comment]
And the height must be 90 pixels.

**Pull request merged**
