### PR TITLE
ci: Speed up build by using pre-built image from previous stage for `make dev`-like check

### PR DESCRIPTION
**Pull request by hangy**
See https://openfoodfacts.slack.com/archives/C02LDQDDD/p1734814872519649 for discussion.

Pro: Speeds up the `make dev` check by a lot, and it use less disk space, reducing the risk of the build agent running out of space.
Con: While similar, it doesn't run `make build` as part of the `make dev_no_build` check, making it not 100% identical to the local `make dev`

### CODE REVIEW

**Review by teolemon — COMMENTED** [review]
- That's great 👍 
- We could have an option to require a full build on demand.
- Also, any idea of the cases where a full build is necessary, eg the potential holes it creates

**Comment by hangy** [comment]
> Also, any idea of the cases where a full build is necessary, eg the potential holes it creates

Not really. The build is done in nearly the same environment, just in separate steps. It's just not completely identical to a local `make dev`.

> We could have an option to require a full build on demand.

Good idea. That way, the normal CI build could be sped up using this change, and a full `make dev` would (optionally) still be available.

**Review by teolemon — APPROVED** [review]
Approving @hangy

**Comment by alexgarel** [comment]
Thanks @hangy  !

**Pull request merged**
