### PR TITLE
ci: Deployment to all the flavors of Open Food Facts

### PR DESCRIPTION
**Pull request by ocervell**
### What
- WIP
- Automatic deployment to all the flavors of Open Food Facts

### CODE REVIEW

**Comment by teolemon** [comment]
@ocervell do you have a sense of what is left to be done on this one ?

**Comment by ocervell** [comment]
I've left this one as draft for @alexgarel, but potentially we have diverged too much on the deployment to use it as is.

**Comment by teolemon** [comment]
cc @CharlesNepote @alexgarel @stephanegigandet

**Comment by teolemon** [comment]
We're actually in the process of waking up Open Beauty Facts and all @ocervell :-)

**Pull request closed without merging**
