### PR TITLE
chore: polyols

### PR DESCRIPTION
**Pull request by aleene**
### What
added (sugar alcohols) for easier findability

### CODE REVIEW

**Comment by aleene** [comment]
#8335 solved

**Review by stephanegigandet — CHANGES_REQUESTED** [review]
We need to keep "polyols" as a synonym too, otherwise a lot of parsing things / recognizing column names in files from manufacturers etc. won't work

**Comment by CharlesNepote** [comment]
@stephanegigandet @aleene thanks a lot!
1. Will the name change in the CSV export???
2. Is it possible to put "Sugar alcohol" first for us.openfoodfacts.org (and only for this one)?
3. At least Germany does not seem to use "polyols" either (can't remember what).

**Comment by stephanegigandet** [comment]
@CharlesNepote :
> 
> 1. Will the name change in the CSV export???

No, the column name is taken from the canonical entry: zz:polyols

> 2. Is it possible to put "Sugar alcohol" first for us.openfoodfacts.org (and only for this one)?

Not currently, we don't support language variants.

**Pull request merged**
