### PR TITLE
taxonomy: Added German variant of inositol

### PR DESCRIPTION
**Pull request by c-schuhmann**
### What

Added the German variant "Inosit" to inositol, which is often contained in beverages like energy drinks. In German, the word "Inosit" is more common than "Inositol".

### CODE REVIEW

**Review by stephanegigandet — APPROVED** [review]
Thank you!

**Comment by stephanegigandet** [comment]
@c-schuhmann Would you have some pictures of nutrition facts table in German with Inosit or Inositol? If Inosit is much more frequent, then we could make it the main name.

**Comment by c-schuhmann** [comment]
@stephanegigandet Yes, please see this example: https://world.openfoodfacts.org/product/5060639126897/monster-energy-ultra-paradise (bottom left of the ingredients list)

I would say we could set "Inosit" as the main German name of this ingredient, should we swap the two names (like "de:Inosit, Inositol") in this case?

**Comment by stephanegigandet** [comment]
> I would say we could set "Inosit" as the main German name of this ingredient, should we swap the two names (like "de:Inosit, Inositol") in this case?

Yes, we should do that, it's indeed much more frequent in German: https://de.openfoodfacts.org/ingredients?filter=inosit

**Comment by c-schuhmann** [comment]
Sorry for the late reply, thank you for your info & merging!

**Pull request merged**
