### PR TITLE
fix: Update logo of the label V-label

### PR DESCRIPTION
**Pull request by thestarsahil**
2 logos for the vegetarian label :

Végétarien → French
Vegetarian → English

### Related issue(s) and discussion

- Fixes #[ISSUE NUMBER]

### CODE REVIEW

**Comment by alexgarel** [comment]
Hi @thestarsahil thank you for your PR.

Did you tested it ?

I don't think it will work, [as stated in the issue](https://github.com/openfoodfacts/openfoodfacts-server/issues/8214#issuecomment-1476349494):

> they have to be in phase with the name of the label in labels [taxonomy](https://wiki.openfoodfacts.org/Global_taxonomies) + the size (see other logos in this folder)

By the way, if after suceeding you want to add a "how to add a label image" in the docs/ folder, you are more than welcome :-)

**Comment by thestarsahil** [comment]
@alexgarel yes i tested its working on and Sure, I'll add a guide on how to add a label image to the docs folder after successfully completing the task. Thank you for the suggestion!

**Comment by thestarsahil** [comment]
@alexgarel Can you please review this pull request?

**Comment by benbenben2** [comment]
Hi @thestarsahil. 

Few comments from my side, I hope it will help.

You added the images in "html/images/lang/hr/" where "hr" is for Croatian.
The images would be more suitable in "en" (English) and "fr" (French), respectively (but see last comment below).
Don't forget to rename the images according to the convention (name-of-the-label.[width]x90.png)
And it seems that you did not change the taxonomies/labels.txt file at all to point to the path of the image.

Here are some references that may guide you:

wiki doc:
https://wiki.openfoodfacts.org/Global_labels_taxonomy
https://wiki.openfoodfacts.org/Global_labels_taxonomy_logos

other doc:
https://support.openfoodfacts.org/help/en-gb/15-improving-open-food-facts-in-my-language-country/55-i-would-like-to-add-a-new-logo-for-labels

Here is an example how-to-add-labels:
https://github.com/openfoodfacts/openfoodfacts-server/pull/7920/files
https://github.com/openfoodfacts/openfoodfacts-server/pull/7957


Remark that there is already a logo for european-vegetarian-union: https://world.openfoodfacts.dev/label/european-vegetarian-union
It is maybe not needed to add more. Ping @alexgarel and @stephanegigandet for advice there.

**Comment by benbenben2** [comment]
Meanwhile, I just realized that your PR @thestarsahil is related to this issue: Fixes #8214.

So, we can ignore my last remark :)

You will have to (replace <> by appropriate number and file extension everywhere):
- replace html/images/lang/en/labels/european-vegetarian-union-vegan.<>.90.<> (currently it is this one https://world.openfoodfacts.dev/label/european-vegetarian-union-vegan)

- replace html/images/lang/en/labels/european-vegetarian-union-vegetarian.<>.90.<> (currently this one: https://world.openfoodfacts.dev/label/european-vegetarian-union-vegetarian)

- add it for French as well.

Curiously, for French, it is now showing the English version: https://fr.openfoodfacts.dev/label/european-vegetarian-union-vegetarian
But the file is there: html/images/lang/fr/labels/european-vegetarian-union-vegetarian.90.90.svg
But the file is named in English.
I believe that the file should be named like the French label is named in the taxonomy. That would be:
html/images/lang/en/labels/union-vegetarienne-europeenne.<>.90.<>

That is how others labels seems to be done, see for example with PDO and AOP:
https://world.openfoodfacts.dev/label/pdo
https://fr.openfoodfacts.dev/label/aop

You can test it during your dev.

**Comment by alexgarel** [comment]
@thestarsahil do you think you will have time to continue this PR ?

**Comment by thestarsahil** [comment]
@alexgarel yes I can

**Pull request closed without merging**
