### PR TITLE
taxonomy: Add label for MåBra health(y) food award

### PR DESCRIPTION
**Pull request by Freso**
### What

Swedish health periodical [MåBra](https://www.mabra.com/) has a yearly(?) award for the “best” health(y) foods, which these products can display on their packaging, e.g., https://se.openfoodfacts.org/label/m%C3%A5bra-rekommenderar-2023

### Screenshot

[current label page](https://se.openfoodfacts.org/label/m%C3%A5bra-rekommenderar-2023)

### Related issue(s) and discussion

- https://se.openfoodfacts.org/label/m%C3%A5bra-rekommenderar-2023

### CODE REVIEW

**Review by stephanegigandet — APPROVED** [review]
Thanks

**Comment by teolemon** [comment]
Error(Linting): on HASH(0x55c748585c18) (line 824)
Processing taxonomies/labels.txt =============

output is not the same as original, line 824..830
Original --------------------
en: MåBra recommends
xx: MåBra rekommenderar, Må bra rekommenderar
sv: MåBra rekommenderar, Må bra rekommenderar
label_categories:en: en:Food awards
country:en: Sweden
website:sv: https://www.mabra.com/


Linted --------------------
en: MåBra recommends
xx: MåBra rekommenderar, Må bra rekommenderar
sv: MåBra rekommenderar, Må bra rekommenderar
country:en: Sweden
label_categories:en: en:Food awards
website:sv: https://www.mabra.com/

**Review by stephanegigandet — APPROVED** [review]
Thanks

**Pull request merged**
