### PR TITLE
taxonomy: add origins translations

### PR DESCRIPTION
**Pull request by ArturLange**
### What
Added Polish origin translations for some of the most popular origins

### CODE REVIEW

**Review by stephanegigandet — APPROVED** [review]
Thank you!

**Comment by stephanegigandet** [comment]
@ArturLange it seems there is the same translation for both UK and Great Britain, could you change one of them?

ERROR - pl:wielka-brytania already is associated to en:united-kingdom (origins) - pl:wielka-brytania cannot be mapped to entry en:great-britain

**Comment by ArturLange** [comment]
I thought that might be a problem, but I couldn't find it in `origins.txt`. Should be fixed now.

**Comment by stephanegigandet** [comment]
> I thought that might be a problem, but I couldn't find it in `origins.txt`. Should be fixed now.

Thank you!

**Pull request merged**
