### PR TITLE
taxonomy: add descriptions and comments as taxonomy fields

### PR DESCRIPTION
**Pull request by raphael0202**
### What

Add description and comment as taxonomy fields.This way, we can display category description (and optional comments about tricky classification decisions about this category) in Hunger Games.
Category description could be used to on mobile apps and on web.

I only converted comments to taxonomy fields, other descriptions/comments can be added later.

### CODE REVIEW

**Review by teolemon — APPROVED** [review]
Looks good to me 👍

**Comment by teolemon** [comment]
@aleene is that ok with you as well ?

**Comment by aleene** [comment]
Ok for me

**Comment by teolemon** [comment]
Thank you @raphael0202, merging

**Pull request merged**
