### PR TITLE
Update variable_weight_products.txt

### PR DESCRIPTION
**Pull request by TaciteOFF**
Premier jet

### CODE REVIEW

**Comment by hangy** [comment]
As mentioned in https://github.com/openfoodfacts/openfoodfacts-server/pull/2424#pullrequestreview-301063228, I wonder how this approach should work considering these 02 barcodes are in a RCN for a geographic region, and VMN patterns are [different for each GS1 member](https://github.com/openfoodfacts/openfoodfacts-server/issues/1288#issuecomment-460052506).

Additionally, it feels odd having to update a source code-related file if a new product (not product category or label) needs to be added. Couldn't we add a country-dependent pattern to the product _in the database_ instead?

**Comment by stephanegigandet** [comment]
@hangy : this is strange: "Pull Request / test (pull_request) Failing after 8m — test"

**Comment by teolemon** [comment]
``` 
Successfully installed MaxMind-DB-Reader-1.000014
Successfully installed GeoIP2-2.006002
! Installing the dependencies failed: Module 'Mojo::Pg' is not installed
! Bailing out the installation for ..
195 distributions installed
##[error]Process completed with exit code 1.
```

**Comment by teolemon** [comment]
Cool, let's merge :-) 
Thanks @TaciteOFF

**Pull request merged**
