### PR TITLE
taxonomy: corrections yogurts

### PR DESCRIPTION
**Pull request by moon-rabbitOFF**
### Related issue(s) and discussion

- Fixes #[ISSUE NUMBER]

### CODE REVIEW

**Comment by stephanegigandet** [comment]
@moon-rabbitOFF there's an error that prevents the taxonomy from building:

ERROR - en:fat-free-fermented-dairy-desserts-with-sweeteners has an undefined parent 
ERROR - en:flavoured-fermented-dairy-desserts-with-sugar-and-cream has an undefined parent

**Comment by moon-rabbitOFF** [comment]
I corrected it, thank you

**Comment by moon-rabbitOFF** [comment]
I corrected it, thank you

**Review by stephanegigandet — APPROVED** [review]
Thank you!

**Pull request merged**
