### PR TITLE
ci: Exclude generated test results from code analysis

### PR DESCRIPTION
**Pull request by hangy**
### What

The generate integration tests results do not need to be included in the analysis. At best, they'll report redundant issues, at works false positives because of test configuration.

### CODE REVIEW

**Comment by stephanegigandet** [comment]
@hangy well I did find and fix issues thanks to sonarcloud on the generated HTML in the expected results: https://github.com/openfoodfacts/openfoodfacts-server/pull/10050/commits/5a9286e4e227290bbd0968e44b4a6e8eeb9eb940
(in particular there was a big select2 array that was initialized by was not used anymore as we switched to dynamic suggestions for some fields)

So I would prefer to keep them, unless there is a significant downside on keeping them.

**Comment by stephanegigandet** [comment]
> The security tab is littered with [js/functionality-from-untrusted-source](https://github.com/openfoodfacts/openfoodfacts-server/security/code-scanning?query=is%3Aopen+branch%3Amain+rule%3Ajs%2Ffunctionality-from-untrusted-source) warnings. I don't know if it's possible to suppress that rule for the integration tests path specifically

One possibility could be to change the function that compares/saves HTML test results, to turn http://static.openfoodfacts.localhost/js/dist/jquery.js to https://static.openfoodfacts.localhost/js/dist/jquery.js

**Comment by alexgarel** [comment]
@stephanegigandet 
> One possibility could be to change the function that compares/saves HTML test results, to turn http://static.openfoodfacts.localhost/js/dist/jquery.js to https://static.openfoodfacts.localhost/js/dist/jquery.js

Or, better, to "//static.openfoodfacts.localhost/js/dist/jquery.js"

**Comment by alexgarel** [comment]
@hangy I propose we close your PR, I can instead propose a PR to format urls to "//" only prefix.

**Comment by hangy** [comment]
Works for me

**Pull request closed without merging**
