### PR TITLE
chore: Add "xxxxxx-de-France" logos

### LINKED ISSUE #5239: Add "xxxxxx de France" logos
There are official logos for:
* "oeufs de France" label, see: https://agriculture.gouv.fr/oeufs-de-france-un-logo-pour-garantir-lorigine-et-la-tracabilite
* "fruits et légumes de France" et "pommes de terre de France" : https://www.uncgfl.fr/10-actualites-publiques/229-logos-fruits-legumes-de-france-et-pommes-de-terre-de-france

### PR DESCRIPTION
**Pull request by borrokk**
### Checklist

Make sure you've done all the following (You can delete the checklist before submitting)

- [x] Code is well documented
- [x] Include unit tests for new functionality
- [x] Code passes GitHub workflow checks in your branch
- [x] If you have multiple commits please combine them into one commit by squashing them.
- [x] Read and understood the [contribution guidelines](https://github.com/openfoodfacts/openfoodfacts-server/blob/main/CONTRIBUTING.md)

### Description
I have added the 3 official logos as mentioned in the issue. They are the following:
"oeufs de France" label, see: https://agriculture.gouv.fr/oeufs-de-france-un-logo-pour-garantir-lorigine-et-la-tracabilite
"fruits et légumes de France" et "pommes de terre de France" : https://www.uncgfl.fr/10-actualites-publiques/229-logos-fruits-legumes-de-france-et-pommes-de-terre-de-france

### Related issue(s) and discussion
- Fixes #5239

### CODE REVIEW

**Review by stephanegigandet — CHANGES_REQUESTED** [review]
The filenames need to be deaccented and in lowercase.
e.g. fruits-et-legumes-de-france.102x90.png

Could you rename the files?

**Comment by borrokk** [comment]
> The filenames need to be deaccented and in lowercase. e.g. fruits-et-legumes-de-france.102x90.png
> 
> Could you rename the files?

yes, I will make the changes.

**Comment by borrokk** [comment]
hi, I am getting some issues while renaming the files locally, should I instead delete the 3 previously added files and add the renamed ones?

**Review by stephanegigandet — APPROVED** [review]
I'll merge and rename the files, thank you!

**Pull request merged**
