### PR TITLE
Made NOVA score 1 for waters

### LINKED ISSUE #2362: Make water NOVA 1 if not flavoured, sugared etc.
The NOVA classification is currently done through the ingredients list, but for most spring water, mineral water etc. we don't have ingredients listed.

### PR DESCRIPTION
**Pull request by VaiTon**
Fixes #2362

### CODE REVIEW

**Comment by stephanegigandet** [comment]
It looks good to me, but I wanted to check which products would be impacted, and it turns out this query does not work as intended:

https://world.openfoodfacts.dev/category/waters/category/-flavored-waters

The resulting query is

          '$and' => [
                      {
                        'categories_tags' => 'en:waters'
                      },
                      {
                        'categories_tags' => 'en:flavored-waters'
                      }
                    ]

**Comment by stephanegigandet** [comment]
Filed https://github.com/openfoodfacts/openfoodfacts-server/issues/2657

**Comment by stephanegigandet** [comment]
It does work in the reverse order: https://world.openfoodfacts.org/category/-flavored-waters/category/waters

**Comment by stephanegigandet** [comment]
So one issue is that there seems to be around 5% of badly categorized products (e.g. not waters, or waters that should have the category flavoured water).

e.g. https://world.openfoodfacts.org/product/3329120002235/eau-minerale-gazeuse-aromatisee-mandarine-passion
https://world.openfoodfacts.org/product/20400248/lemon-lime-still-water-carrick-glen

Some of them we could probably fix by looking at nutrients: if energy is above 0, then it's not pure water.

**Comment by VaiTon** [comment]
> 
> 
> So one issue is that there seems to be around 5% of badly categorized products (e.g. not waters, or waters that should have the category flavoured water).
> 
> e.g. https://world.openfoodfacts.org/product/3329120002235/eau-minerale-gazeuse-aromatisee-mandarine-passion
> https://world.openfoodfacts.org/product/20400248/lemon-lime-still-water-carrick-glen
> 
> Some of them we could probably fix by looking at nutrients: if energy is above 0, then it's not pure water.

That's another story. Could be added to SiteQuality_off though!

**Pull request merged**
