### PR TITLE
Use npm instead of yarn

### LINKED ISSUE #2476: Cannot build npm 6.12.0
### Description of the bug
`npm install` gives error when building with npm 6.12.0 and node v12.13.0

### To Reproduce
1. Install [Node v12.13.0](https://nodejs.org/en/blog/release/v12.13.0/)
2. Try to build the module
3. See error

### Desktop (please complete the following information):
 - OS: Windows 10 Pro

### Logs
```
PS C:\Users\***\openfoodfacts-server> npm install
npm ERR! code 1
npm ERR! Command failed: git checkout ^2.2.12
npm ERR! error: pathspec '^2.2.12' did not match any file(s) known to git
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\***\AppData\Roaming\npm-cache\_logs\2019-10-23T20_23_03_750Z-debug.log
```

[2019-10-23T20_23_03_750Z-debug.log](https://gist.github.com/VaiTon/2fea096fe4b50f349cdd394e95db99d2)

### PR DESCRIPTION
**Pull request by hangy**
Replaces yarn with npm and avoids old bower-style syntax for frontend packages.

Fixes #2476

### CODE REVIEW

**Comment by hangy** [comment]
@VaiTon I believe this would fix #2476. What do you think?

**Comment by stephanegigandet** [comment]
Trying on the dev server, I'm getting a lot of errors when I run npm install, maybe it's due to outdated versions of npm or nodejs or something.

root@ns3135968:/srv/off# npm install

> node-sass@4.13.0 install /srv/off/node_modules/node-sass
> node scripts/install.js

Unable to save binary /srv/off/node_modules/node-sass/vendor/linux-x64-64 : { Error: EACCES: permission denied, mkdir '/srv/off/node_modules/node-sass/vendor'
    at Object.mkdirSync (fs.js:752:3)
    at sync (/srv/off/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/srv/off/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/srv/off/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/srv/off/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/srv/off/node_modules/node-sass/vendor' }

> node-sass@4.13.0 postinstall /srv/off/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/node /srv/off/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/srv/off/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.15.3 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.13
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 10.15.3
gyp verb command install [ '10.15.3' ]
gyp verb install input version string "10.15.3"
gyp verb install installing version: 10.15.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.15.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/srv/off/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '--node_gyp_internal_noretry', '10.15.3' ]
gyp verb install input version string "10.15.3"
gyp verb install installing version: 10.15.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 10.15.3
gyp verb ensuring nodedir is created /srv/off/node_modules/node-sass/.node-gyp/10.15.3
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.15.3' ]
gyp verb remove using node-gyp dir: /srv/off/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 10.15.3
gyp verb remove removing development files for version: 10.15.3
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.15.3' ]
gyp verb remove using node-gyp dir: /srv/off/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 10.15.3
gyp verb remove removing development files for version: 10.15.3
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/srv/off/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 4.9.158-xxxx-std-ipv6-64
gyp ERR! command "/usr/bin/node" "/srv/off/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /srv/off/node_modules/node-sass
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN blueimp-file-upload@10.2.0 requires a peer of jquery@>=1.6 but none is installed. You must install peer dependencies yourself.
npm WARN leaflet.markercluster@1.4.1 requires a peer of leaflet@~1.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.13.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.13.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-27T11_23_56_598Z-debug.log

**Comment by stephanegigandet** [comment]
root@ns3135968:/srv/off# npm -v
6.4.1
root@ns3135968:/srv/off# nodejs -v
v10.15.3

**Comment by VaiTon** [comment]
> @VaiTon I believe this would fix #2476. What do you think?

Maybe. We should primarly try to make it buildable with the lastest LTS of node & npm in my opinion.

**Comment by VaiTon** [comment]
@stephanegigandet could you try to run the `npm install` as root?
```
[...] Error: EACCES: permission denied, [...]
```

**Comment by stephanegigandet** [comment]
> @stephanegigandet could you try to run the `npm install` as root?

That's what I was doing already. 

/srv/off/node_modules/node-sass does not exist.

**Comment by stephanegigandet** [comment]
I installed a newer nodejs with apt-get:

root@ns3135968:/srv/off# nodejs -v
v10.17.0
root@ns3135968:/srv/off# npm -v
6.11.3

But I still have the same error.

**Comment by VaiTon** [comment]
@stephanegigandet try `sudo npm install --unsafe-perm`

**Comment by hangy** [comment]
> Maybe. We should primarly try to make it buildable with the lastest LTS of node & npm in my opinion.

> root@ns3135968:/srv/off# nodejs -v
v10.17.0

Current Node.js LTS is 12.x. Install *should* work with that … (10.x used to be the current LTS unit a few days ago)

**Comment by stephanegigandet** [comment]
@VaiTon --unsafe-perm worked, thank you!

**Comment by VaiTon** [comment]
@hangy is it ready?

**Pull request merged**
