### PR TITLE
ci: mongo-db org deployment

### PR DESCRIPTION
**Pull request by ocervell**

### CODE REVIEW

**Review by alexgarel — COMMENTED** [review]
Actual Mongodb instance is on off2.free.org using distribution package. 

Do we plan to change this ?

cc @stephanegigandet

**Comment by ocervell** [comment]
@alexgarel this is mainly to test releases / prod deployment. Eventually you could either migrate the prod db to this one, or remove this deployment and point the the current prod database.

**Comment by teolemon** [comment]
small merge conflict

**Comment by alexgarel** [comment]
We can close this, we would be able to make it when needed.

**Pull request closed without merging**
