### PR TITLE
New colors and icons for Eco-Score details + impacts for each LCA step

### PR DESCRIPTION
**Pull request by stephanegigandet**
Added Agribalyse detailed PEF + CO2 impacts for each LCA steps.

image

### CODE REVIEW

**Review by teolemon — APPROVED** [review]
Let it be noted in the record that I am not a fan of the color scheme.

**Comment by teolemon** [comment]
image

**Comment by stephanegigandet** [comment]
> Let it be noted in the record that I am not a fan of the color scheme.

Well we can keep everything green like today:

image

But I think it's useful to have different colors for each of the adjustments. I tried with pastel colors but it doesn't look very good either.

image

**Comment by Ban3** [comment]
I actually prefer the pastel colors over the ones in the first screenshot.

**Comment by stephanegigandet** [comment]
Let's go with pastel colors then. :)

image

**Pull request merged**
