### PR TITLE
fix: remove_warnings

### PR DESCRIPTION
**Pull request by benbenben2**
### What

**Fixed the following**
Use of uninitialized value in uc at /opt/product-opener/lib/ProductOpener/Display.pm line 8006.
Argument "" isn't numeric in sprintf at /opt/product-opener/lib/ProductOpener/Display.pm line 467.

### CODE REVIEW

**Review by hangy — APPROVED** [review]

**Comment by raphael0202** [comment]
Using a '/' in a branch name results in an error when I git pull locally:

```
error: cannot lock ref 'refs/remotes/origin/fix/remove_warnings': 'refs/remotes/origin/fix' existe ; impossible de créer 'refs/remotes/origin/fix/remove_warnings'
```

I've created a `fix-remove-warning` branch using pointing to the latest commit of this branch instead.

**Comment by benbenben2** [comment]
Thank you @raphael0202  for pointing this out.

Here is the PR from your fixed branch: https://github.com/openfoodfacts/openfoodfacts-server/pull/11172

**Pull request closed without merging**
