### PR TITLE
docs: Add OpenSSF Best Practices badge to README

### PR DESCRIPTION
**Pull request by teolemon**
Related to #10666

Add the OpenSSF Best Practices badge to the README file.

* Place the badge near the top of the `README.md` file, next to other existing badges.
* Use the provided markdown for the badge: `[OpenSSF Best Practices](https://www.bestpractices.dev/projects/9345)`.

---

For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/openfoodfacts/openfoodfacts-server/issues/10666?shareId=9b29307e-6f78-4f6e-8359-90cb1a302dd2).

### CODE REVIEW

**Comment by teleboas** [comment]
Would it make sense to place this badge alongside the other badges under the README title, rather than having it alone above the title? I think it would look more cohesive with the rest of the badges. What do you think?

**Review by teleboas — COMMENTED** [review]
Would it make sense to place this badge alongside the other badges under the README title, rather than having it alone above the title? I think it would look more cohesive with the rest of the badges. What do you think?

**Comment by teolemon** [comment]
Blame the ghost in the machine 🙃 
It's an IA generated PR (look at the link at the bottom, it's a new GitHub feature) ;-)
More seriously, I'll move it in the right place

**Comment by teolemon** [comment]
done @teleboas

**Review by teleboas — APPROVED** [review]
LGTM

**Pull request merged**
