### PR TITLE
taxonomy: added some ingredients for crunchy almonds - spar in HR

### PR DESCRIPTION
**Pull request by benbenben2**
taxonomy: 
added some ingredients for crunchy almonds - spar in HR

### CODE REVIEW

**Review by stephanegigandet — APPROVED** [review]

**Comment by benbenben2** [comment]
Hi @stephanegigandet 
I can see that there is conflicts on this PR, but I cannot see the details. Let me know if I can help you.

**Comment by benbenben2** [comment]
@stephanegigandet,
If conflict is over line 3670,
hr:obrano mlijeko u orahu 
vs 
hr:obrano mlijeko u prahu
then, keep the later (hr:obrano mlijeko u prahu) because the other one orahu would be something else (maybe with walnut, orah) unrelated to the other lines of the same bloc.

**Comment by stephanegigandet** [comment]
@benbenben2 it is indeed this line.

I tried to fix the conflict and made a new PR here: https://github.com/openfoodfacts/openfoodfacts-server/pull/7332

Could you review it and approve it if everything looks good?

**Comment by benbenben2** [comment]
@stephanegigandet
yes, it looks good!

**Comment by alexgarel** [comment]
closed as #7332 supersedes it

**Pull request closed without merging**
