### PR TITLE
chore: update French labels logos

### PR DESCRIPTION
**Pull request by stephanegigandet**
continue the PR https://github.com/openfoodfacts/openfoodfacts-server/pull/6515 from @borrokk 

- renamed logo files
- changed the potatoes logo to have less white in the margins
- update labels taxonomy

### CODE REVIEW

**Comment by teolemon** [comment]
Got my hand on the official styleguide with PDF versions
LOGO-POTATOES-FRANCE_RVB
LOGO-POMMES DE TERRE-FRANCE_RVB

**Comment by teolemon** [comment]
LOGO-POMMES DE TERRE-FRANCE_PANT
LOGO-POTATOES-FRANCE_PANT

**Review by teolemon — APPROVED** [review]
I have my hands on the AI/PDF versions, fyi

**Review by alexgarel — APPROVED** [review]
LGTM

**Pull request merged**
