### PR TITLE
[WIP] Adding documentation in Hindi

### PR DESCRIPTION
**Pull request by vanshikaarora**
#### Tasks to be done in this PR
**Translating the following documentations to Hindi**
- [X] code-of-conduct.html
- [ ] contact.en.html
- [ ] contribute.html
- [ ] data.en.html
- [ ] discover.html
- [X] donate.html
- [ ] experimental-nutrition-score-france.html
- [ ] faq.html
- [ ] how-to-add-a-product.html
- [ ] index.en.html
- [ ] index.foundation.en.html
- [ ] legal.html
- [ ] missions.html
- [ ] mobile-app-open-food-facts.html
- [ ] nova-groups-for-food-processing.html
- [ ] nova.html
- [ ] nutriscore-formula.html
- [ ] nutriscore.html
- [ ] nutrition-score-uk.html
- [ ] open-food-hunt.html
- [ ] press-and-blogs.html
- [ ] press.html
- [ ] producers.html
- [ ] products.html
- [ ] rateyourvendingmachine.html
- [ ] scan-parties.html
- [ ] terms-of-use.html
- [ ] traffic-lights.html
- [ ] who-we-are.html

**Description:**
Currently added documentation's for following files in Hindi :
 - code-of-conduct.html
- donate.html

### What more to be added:
Adding documentation for other languages as well in a different PR

**Related issues and discussion:** #[ISSUE NUMBER]
Converting the existing documentation to other languages #1899

### CODE REVIEW

**Comment by teolemon** [comment]
Thanks @vanshikaarora, for translations, you should prefer https://translate.openfoodfacts.org/project/openfoodfacts/hi#
I have no issues merging once it's complete, but the proper workflow is through Crowdin

**Comment by teolemon** [comment]
I'm merging this. Thanks @vanshikaarora

**Comment by VaiTon** [comment]
> 
> 
> Kudos, SonarCloud Quality Gate passed!
> 
> [Bug](https://sonarcloud.io/project/issues?id=openfoodfacts_openfoodfacts-server&pullRequest=1903&resolved=false&types=BUG) [A](https://sonarcloud.io/project/issues?id=openfoodfacts_openfoodfacts-server&pullRequest=1903&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=openfoodfacts_openfoodfacts-server&pullRequest=1903&resolved=false&types=BUG)
> [Vulnerability](https://sonarcloud.io/project/issues?id=openfoodfacts_openfoodfacts-server&pullRequest=1903&resolved=false&types=VULNERABILITY) [A](https://sonarcloud.io/project/issues?id=openfoodfacts_openfoodfacts-server&pullRequest=1903&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=openfoodfacts_openfoodfacts-server&pullRequest=1903&resolved=false&types=VULNERABILITY) (and [Security Hotspot](https://sonarcloud.io/project/issues?id=openfoodfacts_openfoodfacts-server&pullRequest=1903&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/issues?id=openfoodfacts_openfoodfacts-server&pullRequest=1903&resolved=false&types=SECURITY_HOTSPOT) to review)
> [Code Smell](https://sonarcloud.io/project/issues?id=openfoodfacts_openfoodfacts-server&pullRequest=1903&resolved=false&types=CODE_SMELL) [A](https://sonarcloud.io/project/issues?id=openfoodfacts_openfoodfacts-server&pullRequest=1903&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=openfoodfacts_openfoodfacts-server&pullRequest=1903&resolved=false&types=CODE_SMELL)
> 
> [No Coverage information](https://sonarcloud.io/component_measures?id=openfoodfacts_openfoodfacts-server&pullRequest=1903) No Coverage information
> [](https://sonarcloud.io/component_measures?id=openfoodfacts_openfoodfacts-server&pullRequest=1903&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=openfoodfacts_openfoodfacts-server&pullRequest=1903&metric=new_duplicated_lines_density&view=list)

@teolemon I'd love to have this on the android repo? Could you add it for me?

**Comment by teolemon** [comment]
I'm not sure who added it but sure

**Comment by teolemon** [comment]
Ok, merging after some time :-)

**Pull request merged**
