### PR TITLE
refactor: replace perl "shift" prototype in `Display.pm`

### PR DESCRIPTION
**Pull request by dipietroR**
Since https://github.com/openfoodfacts/openfoodfacts-server/pull/7009/files was merged, I figured we should start replacing the Perl prototypes with Perl signatures. I replaced a few of the "shift" prototypes in Display.pm

### CODE REVIEW

**Comment by Ban3** [comment]
Change
https://github.com/openfoodfacts/openfoodfacts-server/blob/e41e2c385bdc1b3acb994b16ce3c30a6019956db/lib/ProductOpener/Display.pm#L38-L39
to

```perl
use ProductOpener::PerlStandards
```
when refactoring modules to use signatures.

**Comment by dipietroR** [comment]
> Change
> 
> https://github.com/openfoodfacts/openfoodfacts-server/blob/e41e2c385bdc1b3acb994b16ce3c30a6019956db/lib/ProductOpener/Display.pm#L38-L39
> 
> to
> 
> ```perl
> use ProductOpener::PerlStandards
> ```
> 
> when refactoring modules to use signatures.

Thank you!

**Comment by Ban3** [comment]
> Though, there were a few that had shifts or `@_`'s but no $'s so I left them alone; ie:

Maybe we should convert those regular subroutines to use signatures as well for uniformity.

**Comment by Ban3** [comment]
> Illegal character following sigil in a subroutine signature

These seem to come from nested prototypes in that region, perl thinks they have signatures. [perlsub](https://perldoc.perl.org/perlsub#Signatures) might aid further debugging.

**Comment by dipietroR** [comment]
> > sub display_structured_response_opensearch_rss {
> > my ($request_ref) = @_;
> 
> Subroutines like this are fine to convert because we are assigning `_` to `$request_ref`, but be careful if `_` is on the left side. 

Alright, thanks!

**Review by alexgarel — APPROVED** [review]
LGTM

**Review by stephanegigandet — APPROVED** [review]
Thank you!

**Pull request merged**
